Makefile, api/numaresourcesoperator/v1alpha1/zz_generated.deepcopy.go, bundle.Dockerfile, bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml, bundle/manifests/numaresources-controller-manager-metrics-service_v1_service.yaml, bundle/manifests/numaresources-controller-manager_v1_serviceaccount.yaml, bundle/manifests/numaresources-manager-config_v1_configmap.yaml, bundle/manifests/numaresources-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, bundle/tests/scorecard/config.yaml, config/manager/kustomization.yaml, config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
appropriate parameters provided
To generate the files in this commit, the following parameters
were used with the command:
VERSION=4.10.0 IMG=quay.io/fromani/numaresource-operator:latest make bundle
Note that when running the command for the first time or when the
bundle files are removed, the command will ask additional questions,
asking for:
operator name
operator description
provider name
provider url
maintainers
operator keywords
NOTE: no controller binary args are set for now, this will be added in another PR
=> manifests: add bundle

bundle/manifests/numaresources-operator.clusterserviceversion.yaml
The image is now stored in quay.io/openshift-kni
=> Rename operator bundle image to use openshift-kni quay repo

api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go, config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml, config/manager/manager.yaml, controllers/numaresourcesoperator_controller.go, main.go, pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1alpha1/fake/fake_numaresourcesoperator.go, pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1alpha1/fake/fake_numaresourcesoperator_client.go, pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1alpha1/numaresourcesoperator.go, pkg/k8sclientset/generated/clientset/versioned/typed/numaresourcesoperator/v1alpha1/numaresourcesoperator_client.go, pkg/objectstate/rte/rte.go, test/e2e/basic_install/install.go
The PR also introduces the functionality to fetch the namespace from pod ENV variables and use fetched namespace for deploying RTE components.
=> Change the NRO CRD scope from namespace to cluster scope

rte/main.go
Under normal circumstances the ```Execute()``` should never return.
But if it did return, it is guaranteed that ```err != nil```, so let's skip this check and just spit the log out.
=> lint: do not check the return value

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/numaresourcesoperator_controller.go
A silly typo in the RBAC tags prevented the platform autodetection to
work. Fix it.
=> autodetection: fix typo

pkg/objectstate/rte/rte.go
a copy/paste mistake was causing a NPE on OCP.
=> objectstate: fix typo leading to NPE

api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go, config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml, controllers/numaresourcesoperator_controller.go, main.go, pkg/objectstate/rte/rte.go
Add a field in our API to optionally allow to override the RTE image to deploy, mirroring wath the secondary-scheduler-operator does.
This gives us flexibiltiy at almost no cost, allowing easier test, enabling troubleshooting and hotfix delivery.
=> API: allow to override rte image

rte/pkg/config/config.go, rte/pkg/podrescompat/client.go, rte/pkg/sysinfo/sysinfo.go, test/e2e/basic_install/install.go, test/e2e/e2e_suite_test.go
it's just ugly to mix `log` and `klog`, and
we have no real reason to be stuck with `log`.
=> rte: move kni-specific packages to klog

Makefile, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/controllers_suite_test.go, controllers/kubeletconfig_controller.go, controllers/kubeletconfig_controller_test.go, controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go, go.mod, go.sum, main.go, pkg/objectstate/cfg/cfg.go, pkg/objectstate/rte/rte.go, pkg/testutils/testutils.go, rte/main.go, rte/pkg/config/config.go, rte/pkg/sysinfo/sysinfo.go, rte/pkg/sysinfo/sysinfo_test.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/rte/rte.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/updates.go, vendor/modules.txt
revamp how we handle the configuration of the RTE.
We need to supply to the RTE a configuration file to tell it:
1. details about the TM configuration, which it cannot figure out otherwise (policy, scope...)
2. parameters needed by the `sysinfo` package, which it cannot determine from the system because they depend on the kubelet configuration.
The second set is going to be phased out when OCP exposed the latest changes in the podresources API, but the first set will always be needed. So we will need some form of configuration management anyway.
So the operator will translate the information from the Kubeletconfig object, if available, to the RTE config.yaml and make it available as configmap.
Most important design decisions:
a. always translate as much configuration as possible, since …
=> Reconcile kubelet config

Dockerfile.openshift.rte, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/rbac/role.yaml, controllers/numaresourcesoperator_controller.go, main.go, pkg/images/fetch.go, pkg/objectstate/rte/rte.go
Revamp the code handling user-supplied RTE image, to streamline the flow and make room for future enhancement needed to fully fix the operator-as-operand flow.
Expose and adjust the environment variables we use to introspect the image.
Important fix: We need to passthrough the ImagePullPolicy in the operator-as-operand flow; this is correct in general, the image needs to be handled consistently, and unbreaks our CI flows.
Change UID/GID when running RTE reusing the same operator image:
The RTE need to access entries in the filesystem which are owned by root - surely the podresources socket, on k8s also the kubelet config.
However the operator should run as non-root, and its configuration reflects so.
When we use the operator image as operand (RTE), this settings "leaks" (positively for a …
=> rte: use operator image as rte image

controllers/controllers.go, controllers/kubeletconfig_controller.go, controllers/numaresourcesoperator_controller.go, test/e2e/basic_install/install.go, test/e2e/e2e_suite_test.go, test/e2e/utils/objects/objects.go
we need to wait longer and explicitely for MCPs to be updated on OCP; otherwise the test is misleading - and prone to false
negatives.
The behaviour of the wait is controlled by env variables, to allow tuning without code changes.
This PR includes some refactoring - code movement - to allow to reuse the same code we have in the controllers.
=> e2e: wait for MCP resources

test/e2e/install/install.go, test/e2e/uninstall/uninstall.go, test/utils/machineconfigpools/machineconfigpools.go, test/utils/objects/objects.go
During the e2e test initialization we should create a kubeletconfig object that will apply all the necessary configuration for a proper functionality of RTE
=> e2e: create kubeletconfig resource

Makefile, go.mod, go.sum, hack/tools.go, main.go, pkg/version/version.go, rte/main.go, vendor/github.com/mdomke/git-semver/.gitignore, vendor/github.com/mdomke/git-semver/LICENSE, vendor/github.com/mdomke/git-semver/README.md, vendor/github.com/mdomke/git-semver/main.go, vendor/github.com/mdomke/git-semver/version/version.go, vendor/modules.txt
Implement local package version, feed with the semantic version automatically generated by (vendored) `git-semver`, and add flags to both the manager and the exporter to report it.
=> build: implement the `version` flag in both exporter and manager

.github/workflows/e2e.yml
The e2e lane is now running the full suite, so
rename it accordingly. No changes in behaviour.
=> gh actions: rename the e2e lane

Makefile, pkg/flagcodec/flagcodec.go, pkg/flagcodec/flagcodec_test.go, pkg/objectstate/rte/rte.go, rte/main.go, rte/pkg/config/watcher.go, rte/pkg/config/watcher_test.go
Add facilities to react to config file changes in turn generated by changes of the `kubeletconfig` objects, which are already being handled by the kubeletconfig controller.
=> RTE: Consume config changes

controllers/numaresourcesoperator_controller.go
Our apply logic compares the whole object and also update the whole object
including metadata and status that can be a reason for additional reconciliation
loops. Instead of improving the comparison and updating logic that will make
the code more complex, we can just filter events for objects that did not
have any change under spec or labels.
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
=> nro controller: use predicates for all resources

.github/workflows/release.yml
We had a stale reference for the bundle repo.
=> gh actions: push bundle to openshift-kni org

rte/main.go
In case the topology manager scope is configured in the conf file we should read the value from it instead of the default.
=> read tm scope from conf file

Makefile, bundle.Dockerfile
Explicitly set channel and default channel information;
relying to defaults and implicit context is too error prone atm.
=> Makefile: bundle: add explicit channel info

bundle/manifests/numaresources-operator.clusterserviceversion.yaml
The operator pod should really not have limits until/unless we have a good rationale and proof the limits will not backfire. 
Apply make bundle to remove limits after https://github.com/openshift-kni/numaresources-operator/pull/71
=> Apply make bundle to remove limits

controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go, pkg/objectstate/rte/rte.go
Provide a backup plan when the targeted machine config pool does not have a machine config
selector with matchLabels field. In the above case, we will generate the label and drop a
warning message under the log.
It should be important for machine config pools that target more than one machine config
label. For example, our worker-cnf machine config pool definition looks, like this:
```
...
machineConfigSelector:
matchExpressions:
- key: machineconfiguration.openshift.io/role
operator: In
values: [worker,worker-cnf]
...
```
It is important to say that the code also validates if the generated labels matched by
MachineConfigPool machine config selector, if it not matches the NRO will have
degraded state until the user will update the machine config pool or NRO object with
correct data. …
=> nro controller: generate the machine config label if it impossible to get labels from the machine config pool

doc/examples/kubeletconfig.yaml
The kubelet start fails if the reserved memory is not equal to
NodeAllocatable(system-reserved + kube-reserved + hard eviction threshold).
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
=> doc: fix reserved memory value to be equal to NodeAllocatable

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, bundle/metadata/annotations.yaml, config/manager/manager.yaml
Add workload annotation to make sure our operator will consume only resources specified for control plane containers.
Add tolerations to make sure our operator will continue to run on the non-schedulable master
=> Add relevant tolerations and annotations

controllers/numaresourcesoperator_controller_test.go, go.mod
Organize NRO tests to avoid some code repetition and help in adding
new tests that could need the same sut setup as the ones already in the
suite
=> Re-organize Numaresources operator tests

controllers/kubeletconfig_controller_test.go, pkg/testutils/testutils.go
Add basic coverage for the events emitted by the kubeletconfig
controller. Being part of the user-visible behaviour, we need
to have at least _some_ test coverage.
=> tests: kubeletconfig: add tests for events

Makefile, hack/run-test-e2e.sh, test/e2e/sched/install/install.go, test/e2e/sched/install/test_suite_install_test.go, test/e2e/sched/sched.go, test/e2e/sched/uninstall/test_suite_uninstall_test.go, test/e2e/sched/uninstall/uninstall.go, test/e2e/sched/utils/deployment.go
We need to control the order of the NUMAResourcesScheduler tests:
1. Install
2. Other tests
3. Uninstall
For that, we need each one of the above to be placed in a separate suite and call the suites in the desired order.
This PR intended to address exactly that.
In addition, the NUMAResourcesScheduler e2e tests are set as an opt-in for the e2e script.
Current behavior stays the same, i.e. NUMAResourcesScheduler e2e tests are not running.
=> Improve E2E coverage

.github/workflows/release.yml
we want to use longer tags to tag milestones (-dev) and pre-releases (-pre),
while we can keep the existing tag model (e.g. v4.10.0) for
official releases.
=> gh actions: add regex to match longer tags

test/e2e/uninstall/uninstall.go
Uninstall test fail due delete MCP object is done before PauseMCP for k8s
In fact PauseMCP doesn't find the object.
Fix implement right logic. PauseMCP - Delete nro and kc object - DeleteMCP
CI test were unstable, sometimes test passed. No root cause found. 
=> Fix uninstall e2e test

Makefile, hack/run-test-e2e.sh, hack/run-test-install-e2e.sh, test/e2e/install/install.go
The following E2E were added:
- Verify that ```NumaResourceTopology``` CRD is deployed.
- Check that nothing happens when ```NUMAResourcesOperator``` CR deployed with the wrong name.
- Check that ```NUMAResourceOperator``` CR is deleted, redeploy with different parameters and without polluting cluster state.
These tests are part of the ```[Install]``` labels tests but should run on a separate lane dedicated for them.
=> Additional e2e tests

controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go, go.mod
We should remove daemon sets  for the node group  that was removed from the NumaResourceOperator spec.
=> Delete DaemonSets for deleted NodeGroups

api/numaresourcesoperator/v1alpha1/numaresourcesscheduler_types.go, bundle/manifests/nodetopology.openshift.io_numaresourcesschedulers.yaml, config/crd/bases/nodetopology.openshift.io_numaresourcesschedulers.yaml, controllers/numaresourcesscheduler_controller.go, pkg/numaresourcesscheduler/objectstate/sched/sched.go, pkg/numaresourcesscheduler/objectstate/sched/sched_test.go
Expose the scheduler name in the NUMAResourcesScheduler Status.
This makes easier for any workload, including e2e tests, to
consume the scheduler.
Workload wishing to be scheduled using the Topology/NUMA aware
scheduler need to be using the same name.
=> sched: report the scheduler name in the status

hack/run-test-e2e.sh
In order to explain the motivation of this PR let's define the following terms:
Clean state: The cluster state, **before** any MC changes and/or TAS components were applied.
Dirty state: The cluster state, **after** any/all MC changes and/or TAS components were applied.
In the ususal test cases, we would always want the cluster to be at clean state, after the test run.
But there are special cases, like local tests and GH action tests, that we would like to keep the cluster in dirty state so we could perform various investigation, exporting logs, events, etc.
For that, we'll introduce the NO_TEARDOWN option, that will allow us to keep the cluster in dirty state after test run.
This is totaly optional and keep the current behavior intact.
=> e2e: introduce NO_TEARDOWN option

.github/workflows/e2e.yml
We always considered the kind e2e flow a extra sanity check
and a tier-2 platform because this operator has -and will have-
a number of unavoidable OCP dependencies.
Since the kind e2e lane is flaking recently and no good
resolution is in sight, we make the kind e2e-lane opt in.
We totally want to keep deploying on kind, and we still
recommend to test also on kind.
gh docs references:
https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#push
inspired by:
https://github.com/veggiemonk/skip-commit/issues/5
=> gh actions: opt in the kind e2e flow

test/e2e/install/install_test.go, test/e2e/sched/install/install_test.go, test/utils/crds/crds.go
Improve verification of deployed resources when NRO use default values.
We need to check if all the resources has been properly deployed. 
There are multiple resources to check but we are going to start checking Deployments, DemonSets And CRDs
=> Verify TAS deployed properly with default values

api/numaresourcesoperator/v1alpha1/numaresourcesscheduler_types.go, bundle/manifests/nodetopology.openshift.io_numaresourcesschedulers.yaml, config/crd/bases/nodetopology.openshift.io_numaresourcesschedulers.yaml, controllers/numaresourcesscheduler_controller.go, controllers/numaresourcesscheduler_controller_test.go, pkg/numaresourcesscheduler/objectstate/sched/sched.go, pkg/numaresourcesscheduler/objectstate/sched/sched_test.go, pkg/testutils/testutils.go
This PR contains the necessary changes in the ```NUMAResourceScheduler``` CR and controller in order for the user to be able to configure the ```SchedulerName``` field.
PR contains both implementation and unit tests.
E2E tests will be added on a separate PR later on since there is a lot of activity in this area atm and there is no point with stepping each other toes.
=> numaresourcesscheduler: configurable scheduler name

Makefile, test/e2e/serial/test_suite_serial_test.go, test/utils/fixture/fixture.go, test/utils/nrosched/nrosched.go, test/utils/objects/consts.go, test/utils/objects/deployment.go
Spinoff from #95: bootstrap the serial lane and add all the utilities which we know we need, because we will use them in #95, but are likely helpful in other related PRs like #100
Spinoff of the spinoff to troubleshoot the unexpcted CI failures
=> E2E serial infra foundations

test/utils/nrosched/nrosched.go, test/utils/objects/deployment.go, test/utils/objects/pod.go, test/utils/objects/wait/deployment.go, test/utils/objects/wait/pod.go
Spin off from #95: bootstrap the serial lane and add all the utilities which we know we need, because we will use them in #95, but are likely helpful in other related PRs like #100
=> e2e: add serial lane skeleton and infrastructure

test/e2e/serial/sched_removal_test.go
Add test to make sure that if the topology-aware
scheduler is undeployed (or is somehow unavailable) while
the workload is running, the aforementioned workload is
unaffected; also new workloads requiring that scheduler
must be kept pending.
=> e2e: serial: initial tests for workload resilience

controllers/kubeletconfig_controller.go, controllers/numaresourcesoperator_controller.go, pkg/machineconfigpools/machineconfigpools.go, test/e2e/uninstall/uninstall.go, test/utils/machineconfigpools/machineconfigpools.go
Create a new package to resolve MCPs by the selector and/or by the NodeGroups configuration, extracting the code
from the controllers package with no intended changes in behaviour.
=> extract machineconfigpools utilities from the controller package

hack/verify-generated.sh
When the verify-generated return with error, it tells the user to run \'make generate\' and commit results.
There are times when it's not enough and the user need to run other make targets.
This new message aims to resolve that.
=> improve verify-generated.sh error message

Makefile, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml
We want, by default, to always use the most updated version existed.
This is new value is a valid semantic version tag that pushed to quay for every new image that gets created.
Also see: https://github.com/openshift/release/pull/25141
=> makefile: change default VERSION parameter value

Makefile
We should actually apply the manifests that got built by Kustomize and not just output them to the console
Regression caused by: https://github.com/openshift-kni/numaresources-operator/pull/98
=> makefile: fix make deploy target

.github/workflows/e2e.yml
This reverts commit 629a7a0f4bbe2870bcd50f79eb05f30a0b0653bf.
this reverted commit not needed anymore due to following reasons:
1. It doesn't seem to work.
2. The original problem it intended to solve, already addressed at: https://github.com/openshift-kni/numaresources-operator/pull/98
=> Revert "gh actions: opt in the kind e2e flow"

pkg/flagcodec/flagcodec.go, pkg/flagcodec/flagcodec_test.go
Up until now, `flagcodec` was reordering the args
before rendering them.
This is not always correct, because it's relatively common
for command line argument to have some ordering requirements.
A key example is the subcommands: some options for a command
may make sense for the global context, while some other options
are subcommand-specific.
flagcodec doesn't aim (yet) to cover all the cases, but this is
simple to fix: instead of force a sorting, just record the order
on which the flags are parsed, and reuse it when rendering.
The end result is still a valid command line, the implementation
is not more complex and the behaviour is more correct.
=> flagcodec: preserve the order of args

pkg/numaresourcesscheduler/manifests/yaml/deployment.yaml
According to the line we took at: https://github.com/k8stopologyawareschedwg/deployer/pull/79
We should also have the same here.
=> manifests: set executable under the command stanza

test/e2e/install/install_test.go, test/e2e/sched/sched_test.go, test/utils/images/consts.go
Use CI test images, built by prow, in all the relevant tests
which want to use test images.
Previously, we used different (and now obsolete) images only because
the e2e tests predated the prow config.
Nowadays prow builds the test images for this specific task.
=> e2e: use CI-provided test images

test/e2e/install/install_test.go
Sometimes NUMAResourcesOperator takes some time creating RTE DaemonSet
so it is better to wait for it in testing to avoid failures.
Split of #131
=> Wait for DaemonSet to be created by NRO

Makefile
Ensure we disable CGO, to avoid depending on glibc,
and ensure we consume the local vendored deps.
=> Makefile: fix build process of binaries

test/deviceplugin/cmd/numacell/main.go, test/deviceplugin/pkg/numacell/api/numacell.go, test/deviceplugin/pkg/numacell/manifests/manifests.go, test/deviceplugin/pkg/numacell/plugin/numacell.go
In order to avoid possible races with the scheduler,
we add an option to configure more fake numacell devices
rather than just 1. We keep producing an infinite amount of them.
=> e2e: numacell dp: configurable device count

go.mod, go.sum, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/topology_updater/topology_updater.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/nodetopology/nodetopology.go, vendor/modules.txt
Latest version contains fixes for some flaky tests we had.
Maybe it is better to create a new tag and only then update the dependencies.
=> vendor: bump k8swg/rte to latest version

test/e2e/install/install_test.go, test/utils/machineconfigpools/machineconfigpools.go, test/utils/objects/wait/errors.go, test/utils/objects/wait/machineconfig.go, test/utils/objects/wait/numaresources.go, test/utils/objects/wait/pod.go
the install suite was flaking with errors similar to
```
Message: "object is being deleted: kubeletconfigs.machineconfiguration.openshift.io \"kc-test\" already exists",
```
This is because the test code was not waiting for the object
to be deleted from the cluster, but it was rather going along
if the deletion *request* was succesfully accepted by the system.
It's more correct to wait for objects to be deleted before to
keep going with the tests, so we do it in this patch, adding
the necessary utilities to enable this flow.
=> e2e: install: wait for objects to be deleted

test/e2e/sched/install/install_test.go, test/e2e/sched/utils/node.go
When running in an OCP environment, the label "node-role.kubernetes.io/control-plane" doesn't exist for the master nodes.
We shall add this label only when running in a K8S environment
=> e2e: fix master node affinity test

hack/run-test-e2e-serial.sh, test/e2e/serial/test_suite_serial_test.go, test/e2e/serial/workload_placement_test.go, test/utils/noderesourcetopologies/noderesourcetopologies.go, test/utils/noderesourcetopologies/resourcelist.go, test/utils/objects/pod.go, test/utils/objects/wait/pod.go
Add test to verify the behaviour of the whole TAS flow, placing guaranteed workloads and checking the placement.
Add utilities to deal with NRT objects.
Partially replaces #95
=> e2e: serial: start workload placement tests

.github/workflows/e2e.yml, Makefile, hack/run-test-e2e.sh, test/e2e/sched/install/install_test.go, test/utils/clients/clients.go, test/utils/crds/crds.go
When the numaresourcesscheduler was implemented initially, we thought it was going to stay with us for a very short time.
This assumption turned out to be wrong, so it's worth enabling the e2e tests for numaresourcesscheduler by default in order to avoid future regression.
=> e2e: stabilize and enable numaresourcesscheduler test-suite

controllers/numaresourcesoperator_controller.go, test/e2e/install/install_test.go, test/utils/machineconfigpools/machineconfigpools.go
After a teardown of the environment at the end of each test, we should wait for all mcps` ```UPDATED``` status to be ``True`` , in order to avoid conflicts before applying new MachineConfig data on the next tests.
=> e2e: wait for MCP UPDATED status

test/utils/noderesourcetopologies/noderesourcetopologies.go, test/utils/padder/padder.go
The padder package allows controlling the number of available resources under the nodes.
It's doing that by padding the nodes with idle pods, until the node reaches the desired amount of available resources.
This package comes very handy on cases when we need specific prerequisites to be apply on nodes,
wrt the amount of available resources they have prior to the test run.
Usage example:
```
pad := New(client, test-ns)
pad.Nodes(2).UntilAvailableReach(corev1.ResourceCPU, 3).UntilAvailableReach(corev1.ResourceMemory, 100Mi).Pad()
```
or
```
rl := corev1.ResourceList {
corev1.ResourceCPU: 10,
corev1.ResourceMemory: 100Mi
}
pad.Nodes(2).UntilAvailableReachWithResourceList(rl).Pad()
```
In an ideal situation, this package would deserve some unit tests, but unit tests are complex to implement …
=> e2e: padder package

test/e2e/serial/workload_placement_test.go
Add e2e test to verify the behaviour of the NUMA aware scheduler by creating a testcase which is expected to foul the default,
NUMA-unaware scheduler. 
We expect to run on a cluster with two or more machines each of which has two NUMA zones. We don't actually support
more than two zones because the resource allocation numbers are hardcoded, not computed on the fly. Given how rare machines with more than 2 NUMA zones, that should not be a problem anytime soon.
We use a guaranteed pod with two containers; we set the required resources such as the total amount of requested resources is available on both the two workers but one of them only has all resources on one NUMA per container.
IOW:
- 2+ nodes have all the required resources availaible at *node* level
- exactly 1 node have all the …
=> e2e: serial: test multi-container placement

test/e2e/serial/workload_placement_test.go, test/utils/noderesourcetopologies/noderesourcetopologies.go, test/utils/nodes/nodes.go, test/utils/padder/padder.go
The test creates a guaranteed pod with toleration.
The cluster has two feasible nodes with taint matching the toleration of the workload, but only one of them has all the requested resources on a single NUMA.
The test verifies the pod land on the correct node, otherwise, it failed
depend on #116
=> e2e: serial: implement test id 47594

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/samples/nodetopology_v1alpha1_numaresourcesoperator.yaml, config/samples/nodetopology_v1alpha1_numaresourcesscheduler.yaml
copy data from doc/examples, which still is our authoritative source.
manual cherry-pick of https://github.com/openshift-kni/numaresources-operator/pull/151
=> [release-4.10] bundle: examples: update CR examples

api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go, api/numaresourcesoperator/v1alpha1/numaresourcesscheduler_types.go, bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml, bundle/manifests/nodetopology.openshift.io_numaresourcesschedulers.yaml, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml, config/crd/bases/nodetopology.openshift.io_numaresourcesschedulers.yaml, config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
add annotations to make the operator-sdk scorecard check happy.
=> api: manifests: add scorecard annotations

Makefile
reorganize the '*-all' targets for better clarity,
and make sure we have the 'binary-e2e-all' target.
=> Makefile: reorder all targets

controllers/numaresourcesoperator_controller.go, pkg/status/status.go, pkg/status/status_test.go, vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go, vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go, vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go, vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go, vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go, vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go, vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go, vendor/modules.txt
We create a new `default` set of conditions to compare with the current
ones. These conditions are created with `now()`	as value for
`LastTransitionTime` field.
This way comparison always return there are differences between
conditions and therefore they are always updated even if it is not
needed.
Update `LastTransitionTime` to have the same value as the current
conditions so it would not modify the comparison.
Note: everything in condition handling is based on the assumption that
the conditions order in the conditions array is always the same.
=> Conditions: avoid unnecessary updates due to wrong timestamp

Dockerfile.openshift.tests, Dockerfile.tests, Makefile, hack/run-test-e2e-serial.sh
reorganize the e2e serial runner script and make sure
it can be shipped in the tests container image.
This means fixing the paths.
=> e2e: serial: revamp the runner script

doc/examples/kubeletconfig.yaml
We only support "TopologyManagerScope"="pod" at this moment,
so fix the example config to suggest that.
=> doc: example: fix kubeletconfig

test/e2e/install/install_test.go, test/utils/objects/objects.go
Add an option (env var) to let the install suite avoid to deploy kubeletconfig. This enables CIs to test different environments and configs easily.
Switch the default scope to "pod" - as is the only one we support atm.
Also add minor fixes to improve the debuggability.
=> e2e: install: enable install lane to reuse existing kubeletconfig

README.md
This informations reflects what's published on
https://quay.io/repository/openshift-kni/numaresources-operator-tests?tab=info
The README becomes now the master source for the above.
=> doc: README: document how to run the e2e suite

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
We need k8s >= 1.23 because of the podresources API.
=> csv: declare minimum kubernetes version

test/e2e/serial/workload_placement_test.go
Fix pod naming issues emerged during the fine tuining of the e2e serial suite.
Please check the individual commits for details.
=> e2e: serial: fix pod generation

controllers/numaresourcesoperator_controller.go, main.go, pkg/objectstate/rte/rte.go
u/s RTE wants to use the google pause container for the
shared pool container. We need to minimize the container image,
so we replace it reusing the same RTE image with a different
entry point.
Since we require anyway the RTE image to be based on a ubi-minimal
(or equivalent) image, and since the shared-pool-container
does not need to reap pids but just to sleep forever peacefully,
we can use just the simplest sleep command.
=> rte: don't use google pause container

test/utils/images/images.go, test/utils/objects/pod.go
Running the tests on disconnected environments might lead to pod crash while pulling images from external registries.
Keep using Pause image as the default test image and allow configuring the image via an environment variable TEST_IMAGE.
=> e2e: make tests pod's image configurable

Dockerfile.openshift.tests, Dockerfile.tests, Makefile, README.md, hack/pause
Add a simplified version of pause entrypoint in the same
location of the google pause image. This is expected to
make the tests image fully compatible with the google pause image.
=> hack: dockerfile: add pause entrypoint

Dockerfile.openshift.tests, Dockerfile.tests, Makefile, hack/pause
Add a simplified version of pause entrypoint in the same
location of the google pause image. This is expected to
make the tests image fully compatible with the google pause image.
=> [release-4.10][manual] hack: dockerfile: add pause entrypoint

test/e2e/serial/workload_placement_test.go
Pod name must be consist of the following letters only: ```'[a-z0-9]'```
The serial test is falling without this change.
=> e2e:serial: use a lowercase letters in pod name

test/e2e/sched/utils/daemonset.go, test/e2e/serial/workload_placement_test.go, test/utils/objects/daemonset.go
Ensure that there is at least one node with guaranteed resources available but cannot be scheduled in a single numa zone.
=> e2e-workload: Workload requests guaranteed pod resources available on one node but not on a single numa

test/e2e/serial/workload_placement_test.go
The test creates a pod, pin it selectively using the nodeName stanza and makes sure that NRT objects are updating respectivley
=> e2e:serial: schedule guaranteed pod in selective way

test/e2e/serial/workload_placement_test.go
Create a deploy with a podSpec having a RuntimeClass assigned, in a
single NUMA zone and check that pod overload resources are no accounted
in NodeResourceTopology.
=> e2e Check pod overhead is not accounted on NRT.

test/e2e/serial/workload_placement_test.go, test/utils/noderesourcetopologies/noderesourcetopologies.go, test/utils/padder/padder.go
Test to check burstable pods with too much required resources to be
scheduled on any NUMA zone but fitting on at least one node, are still
scheduled using Secondary Scheduler with no change in
NumaResourceTopology for that node.
=> e2e test: Burstable pod not fitting any NUMA zone

test/e2e/serial/test_suite_serial_test.go, test/e2e/serial/workload_placement_test.go, test/utils/nodes/nodes.go, test/utils/objects/wait/machineconfig.go
The test modifies every configurable value under the ```NUMAResourcesOperator``` and ```NUMAResourcesScheduler``` CR's and checks that the controller applied the configuration as expected.
The test requires MCP changes, hence nodes reboot, and therefore it's label with a special ```[reboot_required]``` label to denote that.
We also add the ```[slow]``` label to denote this test might take more time than usual.
=> e2e: serial: Modify configurable values

hack/run-test-serial-e2e.sh, test/e2e/install/install_test.go, test/e2e/sched/install/install_test.go, test/e2e/serial/workload_placement_taint_test.go, test/e2e/serial/workload_placement_test.go
Split off tests which deal with taint/tolerations, because
they constraint the scheduler enough to deserve their own go source
(and ginkgo Describe block).
Add `E2E_SERIAL_SKIP` env var to enable skipping some tests in the serial suite
=> e2e: serial: split tests form `workload_placement_test.go` - take 3

test/e2e/serial/resource_accounting_test.go, test/e2e/serial/workload_placement_test.go
Split off test that verifies a burstable pod is properly scheduled and doesn't expect for resources to be accounted in NRT. The test is relevant for both TM policies.
=> e2e: serial: split tests form workload_placement_test.go - take 4

test/e2e/serial/sched_removal_test.go
When having multiple `It` blocks under describe/context each `It` should have unique test id in order for its result to be stored properly and not overridden.
Adjust `It` cases to have unique test ids.
=> e2e: add test_id to It blocks

test/e2e/serial/README.md, test/e2e/serial/e2e_serial_test.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/e2e_suite.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/sched_removal.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_nodesel.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go, test/utils/configuration/configuration.go
The previous reorganization of the e2e tests was
made into the attempt to follow more closely the
go conventions, adding the `_test` suffix for source
files containing test code.
This worked well but made hard to import the testsuite
into external projects (cnf-tests).
Trying to import the existing suite leads to
```
no non-test files found
```
which is not good.
Hence we do another reorganization for the serial suite
only, moving the actual test definition into a utility
package.
No expected change in behaviour for the NROP testsuite
proper (nor test image).
=> e2e: serial: make it easier to integrate

test/e2e/serial/e2e_serial_test.go, test/e2e/serial/tests/e2e_suite.go
the `serial/tests` subpackage should include the actual
logic to be run in the ginkgo `Before/AfterSuite` helpers,
but not the hooks themselves, to make it possible to
integrate with other suites (e.g. cnf-tests) which may
have their `Before/AfterSuite` already.
=> e2e: serial: move away Before/AfterSuite

test/e2e/serial/tests/workload_placement.go
When the test calls outputed by the Skip function, it points to the code location where its caller is located which is ```skipUnlessEnvVar``` function (i.e. ```.../github.com/openshift-kni/numaresources-operator/test/e2e/serial/tests/workload_placement.go:760```)
We less care about the ```skipUnlessEnvVar``` function and more about it's caller which is the actual test code.
Let's add caller skip in order to get more useful code location.
=> e2e: skip with call stack offset

test/e2e/serial/tests/e2e_suite.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/utils/nodes/baseload.go
the interaction between the noderesourcetopology and the noderesource filter plugins highlighted quite few complications.
by design, NRT objects do NOT account for non-esclusive resources; this mean burstable pods do take node resources, but these are not reflected into NRT available fields. This is unfortunate, but due to the fact that non-esclusive resources are not pinned to a NUMA zone, hence are difficult to track and account.
This means the NRT and the noderesource plugin have a different perspective about the available resources.
Note the kubelet has the same picture as the noderesource plugin (bar network delays) hence - noderesource can cause a node to be filtered out "unexpectedly" - just disabling noderesource (debatable) can lead to pod rejections for `OutOfCpu` or …
=> fix and unconditionally enable the workload placement by tm scope tests

test/deviceplugin/cmd/numacell/main.go, test/deviceplugin/pkg/numacell/cmd/numacell.go
Trivial code movement to make it easier to integrate
the numacell plugin into external projects (e.g. cnf-tests)
which also want to integrate the serial suite, which
depends on numacell.
No intended changes on behaviour.
=> e2e: numacell: move logic in packages

Makefile, go.mod, go.sum, hack/envsubst.go, hack/render-e2e-runner.sh, hack/run-test-serial-e2e.sh, test/e2e/serial/e2e_serial_test.go, vendor/github.com/drone/envsubst/.drone.yml, vendor/github.com/drone/envsubst/.gitignore, vendor/github.com/drone/envsubst/LICENSE, vendor/github.com/drone/envsubst/eval.go, vendor/github.com/drone/envsubst/funcs.go, vendor/github.com/drone/envsubst/parse/node.go, vendor/github.com/drone/envsubst/parse/parse.go, vendor/github.com/drone/envsubst/parse/scan.go, vendor/github.com/drone/envsubst/path/match.go, vendor/github.com/drone/envsubst/readme.md, vendor/github.com/drone/envsubst/template.go, vendor/modules.txt
fix non-OCP builds by bundling a local and specialized version of envsubst, which can do partial variable substitution.
=> Dockerfile: fix envsubst dependency

test/e2e/serial/config/config.go, test/e2e/serial/config/fixture.go, test/e2e/serial/config/infra.go, test/e2e/serial/e2e_serial_test.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/e2e_suite.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/sched_removal.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_nodesel.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go, test/utils/fixture/fixture.go, test/utils/padder/padder.go
Move the configuration steps we used to do in the {Before,After}Suite{,Helper} in their own subpackage.
This way, we can keep the current suite behaving like before (bar the necessary mechanical API and import changes) but we
enable better integration with external projects (= cnf-tests)
It goes like this:
cnf-tests want to run the configuration steps in a different suite (configsuite) separated by the test suite proper (e2esuite).
In this model, we will add all the configuration steps in the config suite; in the test suite, we will integrate the tests proper and the minimal configuration support (our own fixture).
=> e2e: add serial config suite

test/utils/nodes/baseload.go
AsInt64 failed to parse cpus millis like 800m, which caused to return 0 value as the CPU consumption on the node.
Use Value() to round up the milli CPUs to complete CPU then continue rounding it up to multiples of 2.
=> utils: baseload: fix GetLoad() to correctly reflect the node load

pkg/kubeletconfig/kubeletconfig.go, test/e2e/serial/tests/configuration.go
This test ensure that TAS knows how to handle and respond to live kubeletconfig changes while it's already running
=> e2e:serial: modify kubeletconfig while TAS is running

internal/baseload/baseload.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/sched_removal.go, test/e2e/serial/tests/workload_placement_nodesel.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go
Add events reporting of the failing pods to simplify debugging test failures when needed.
=> serial: add events reporting for failing pods

.github/workflows/cilint-custom.yml
Since golangci-lint "works on my machine", let's try the same steps on CI.
=> gh actions: add lane avoiding the gh actions lint

test/e2e/serial/tests/workload_unschedulable.go, test/utils/nrosched/nrosched.go
make the unschedulable tests more robust, with no expected changes in behaviour
=> e2e: make `unschedulable` tests more robust

test/e2e/serial/tests/workload_placement_nodesel.go
Add the fixes which allow us to always run this test, so removing the opt-in skip.
See individual patches for details.
=> e2e: remove opt-in skip in the node-selector workload placement test

test/e2e/serial/config/config.go, test/e2e/serial/config/fixture.go
The `config` module is in a bit of awkward state, with functions
partially manipulating the global state and partially trying to
avoid it. However, this module holds and manages global state,
so let's just embrace this requirement and have {Setup,Teardown}Fixture
functions always operating on the global state.
=> e2e: serial: config: clean up config API

test/e2e/serial/config/config.go, test/e2e/serial/config/fixture.go, test/e2e/serial/config/infra.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/sched_removal.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_nodesel.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go
To facilitate the integration with cnf-tests, we need to allow the caller to handle the error, possibly Expect()ing to not happen, unless of always doing that ourselves.
This means we now need a bit more protection to fail with a clear error (and, say, not panic) if this preconditions is not met.
Which should never happen, unless we have bugs.
=> e2e: serial: config module modularization (take 2)

test/e2e/serial/config/config.go
Teardown should exit silently if the fixture is not ready,
which can happen in the cnf-tests integration if no numaresources
tests have been enabled.
=> e2e: serial: config: avoid NPE on teardown

internal/baseload/baseload.go, internal/resourcelist/resourcelist.go, internal/resourcelist/resourcelist_test.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/utils/noderesourcetopologies/noderesourcetopologies.go
fix the pod overhead test. This also allows to remove the last `E2E_SERIAL_STAGING` instance.
=> e2e: serial: remove skip if `E2E_SERIAL_STAGING` variable set

README.md
add instructions (and fixes along the way) about how to run the suite using the CNF tests container image
=> docs: document the CNF-tests integration

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/kubeletconfig_controller.go, test/e2e/rte/rte_test.go
- KubeletConfig deletion event:
**old behavior:** infinite loops trying to fetch the already deleted object.
**new behavior:** do nothing but logging out the fact that the resource got deleted.
- ConfigMap update/deletion event:
**old behavior:** operator didn't detect external/manual tamper and keep the resource in undesired state.
**new behavior:** set KubeletConfig as the OwnerReference which triggers the correct reconciliation loop and keep the resource (ConfigMap) in the desired state
=> kubeletcontroller: minimize and tune reconciliation loop

test/e2e/serial/config/infra.go, test/utils/images/images.go
We don't ever log the pullSpecs we are about to use,
which makes troubleshooting unnecessarily hard.
Fix this adding the logs.
=> e2e: serial: log pullSpec actually used

test/utils/objects/wait/daemonset.go, test/utils/objects/wait/deployment.go, test/utils/objects/wait/errors.go, test/utils/objects/wait/machineconfig.go, test/utils/objects/wait/numaresources.go, test/utils/objects/wait/pod.go
Add helpers to make the logs terser while carrying the same amount of info.
Before:
```
I0426 12:10:45.481323   42652 pod.go:67] pod types.NamespacedName{Namespace:"e2e-test-resource-accounting-6505", Name:"tgtpadpod-node-0"} phase Pending desired Running
I0426 12:10:45.482760   42652 pod.go:67] pod types.NamespacedName{Namespace:"e2e-test-resource-accounting-6505", Name:"tgtpadpod-node-1"} phase Pending desired Running
I0426 12:10:55.581299   42652 pod.go:63] pod types.NamespacedName{Namespace:"e2e-test-resource-accounting-6505", Name:"tgtpadpod-node-1"} reached phase Running
I0426 12:10:55.583247   42652 pod.go:63] pod types.NamespacedName{Namespace:"e2e-test-resource-accounting-6505", Name:"tgtpadpod-node-0"} reached phase Running
```
After:
```
I0426 15:58:55.297050   61132 pod.go:89] …
```
=> e2e: wait: terser logging when wait

test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_taint.go
fixes to make the test which requires taints more robust by removing taints more carefully:
- record the tainted nodes explicitly and do target remove
- keep doing a full sweep to make sure no taints are left
- before to finish, wait for taints to be gone from all worker nodes, fail if it not the case
=> e2e: serial: make untainting more robust

test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_nodelabel.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go
Add the missing NRT checks to the tests to verify the NRT changes after scheduling workloads or modifying resources.
(Another PR is planned for supporting this step for after deleting workloads.)
=> serial: add NRT check after scheduling workloads

pkg/k8sclientset/config.go, rte/main.go
In few places we still use the old-way to construct errors.
Let's make another step towards go 1.13+ error handling.
See https://go.dev/blog/go1.13-errors
=> err: properly wrap errors

test/e2e/serial/tests/workload_unschedulable.go
This patch updates a log message to clearly indicate that
we are waiting for the deployment to reach a certain number
of replicas. The previous log message gave an impression
of a failure causing confusion and making the person running
the test suite question why the test suite passed even though
the log messages indicated failures
=> log: Improve log message to clearly indicate the wait

test/utils/nrosched/nrosched.go
Fetch the scheduler name from the scheduler object from under the Status instead of Specs.
=> utils: fix fetching the scheduler name

internal/baseload/baseload.go, test/e2e/serial/tests/workload_placement_resources.go, test/e2e/serial/tests/workload_placement_tmpol.go
In the e2e serial resource placement tests, we need to consider the baseload when padding nodes.
This was previously missing because a oversight.
=> e2e serial: fix baseload accounting in placement-by-resources tests

README.md
We can lift this limitation. We now support alignment of memory
resources.
=> doc: add support for memory alignment

Dockerfile.tools
Installing binaries was `go get` was actually deprecated
a couple go releases ago. And we don't need ginkgo, actually
(we never did here).
=> Dockerfile: tools: use `go install`

Makefile
Dump the version of the go toolchain before to run the build.
This is cheap and helps troubleshooting CI woes.
=> Makefile: emit go version when building

pkg/numaresourcesscheduler/manifests/yaml/configmap.nrt.yaml
In order to clarify and make explicit the interplay between NRT filter and the noderesourcefit filter, we now explicit spell out the filter chain, instead of relying on the implicit default behaviour.
=> scheduler: force order of filters

Makefile, hack/buildhelper/buildhelper.go, hack/tools.go, main.go, pkg/version/version.go, pkg/version/version_test.go, rte/main.go
Replace git-semver, which we were using in the build step,
with another tailor-made tool superset of it.
What we gain is: we can now report the git commit from which
the build is done, and we can inject the values from outside,
bypassing the autodetection, to be friendlier with isolated build
systems, which would otherwise fail the autodetection.
=> build: introduce buildhelper replacing git-semver

Makefile, hack/buildhelper/buildhelper.go, hack/tools.go, main.go, pkg/version/version.go, pkg/version/version_test.go, rte/main.go
Replace git-semver, which we were using in the build step, with another tailor-made tool superset of it.
What we gain is: we can now report the git commit from which the build is done, and we can inject the values from outside,
bypassing the autodetection, to be friendlier with isolated build systems, which would otherwise fail the autodetection.
=> [release-4.10][manual] fix versioning 4.10

README.md
This patch documents that resources requested by static pods
are not accounted for when per NUMA resource availablity is
calculated.
=> static-pods: Document the behaviour of static pods

test/e2e/serial/tests/resource_accounting.go
verify that once a best-effort or burstable pod is scheduled with the NUMA-aware scheduler, no NRT resources are consumed.
This is again because the NRT only accounts exclusively allocated resources - to guaranteed pods.
=> e2e: serial: tests for non-guaranteed pods

api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go, api/numaresourcesoperator/v1alpha1/numaresourcesscheduler_types.go, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
see: https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/components/descriptors/reference/reference.md
regenerated the manifests with `make bundle`
validated with `operator-sdk scorecard bundle/`
=> api: bundle: add OLM spec desc refs for logLevel

Dockerfile, Dockerfile.tests
Until we find better builder images, we actually want to
use the dockerhub images, so let's be explicit about that.
=> Dockerfile: fully qualified builder images

test/e2e/serial/tests/workload_unschedulable.go
Now that https://github.com/openshift-kni/numaresources-operator/pull/319 merged, we can test with both pod and container scope. Hence let's remove this restriction
=> e2e:serial: remove requirement for scope=pod in unsched tests

controllers/numaresourcesoperator_controller.go, test/e2e/install/install_test.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/workload_placement.go, test/utils/objects/daemonset.go, test/utils/objects/objects.go, test/utils/objects/pod.go, test/utils/objects/wait/daemonset.go
This e2e install test:
```
[Install] durability
/go/src/github.com/openshift-kni/numaresources-operator/test/e2e/install/install_test.go:138
with a running cluster with all the components and overall deployment
/go/src/github.com/openshift-kni/numaresources-operator/test/e2e/install/install_test.go:180
should be able to delete NUMAResourceOperator CR and redeploy without polluting cluster state [It] 
```
started to fail reliably. This PR wants to add troubleshooting aids and, ultimately, the fix. Spawned off from #324
=> e2e: install: minimal fixes

test/e2e/serial/tests/workload_unschedulable.go, test/utils/nrosched/nrosched.go
Test case: Deployment with a gu pod scheduled by default scheduler
requesting resources available on one node but not on a single numa.
=> e2e: serial: default scheduler: deployment with gu pod on a node

test/e2e/serial/tests/workload_placement_tmpol.go
For disconnected environments (like we use in NROP CI) using quay images will cause the pod to fail to start running due to unreachable image url.since we mainly care about the amount of time the init container is alive, change the image to from test-ci to Pause image that would be replaced by the url passed into one of the following env vars: E2E_PAUSE_IMAGE_URL , E2E_NUMACELL_DEVICE_PLUGIN_URL.
=> e2e: change image for init containers

README.md
Thanks to all the fixes and the added e2e tests, we can
support the `scope=container` scheduler plugin mode.
=> docs: limitations: we now support scope=container

test/e2e/serial/tests/resource_accounting.go
We create a burstable pod that occupies node resources.
Subsequently trying to schedule a guaranteed pod fails
as the pod doesn't have sufficient resources and stays
pending till burstable pod is deleting and enough resources
are available on the node to accomodate it.
=> e2e: serial: Resources shared by burstable and guaranteed pods

test/e2e/serial/tests/workload_placement_tmpol.go, test/utils/images/consts.go
The reference pause image is the google's (https://hub.docker.com/r/google/pause/tags) which doesn't ship `/bin/sleep` - but only `/sleep`. The e2e serial suite support images replacements, but all of them must be compatible with the pause container.
Fix usage of the pause container images in the e2e serial suite - use `pause`, not `sleep`.
Otherwise:
```
STEP: waiting for the pod to be scheduled
I0801 12:34:56.034474   39136 pod.go:89] pod e2e-test-workload-placement-tmpol-5840/testpod phase Pending desired Running
I0801 12:35:06.149543   39136 pod.go:89] pod e2e-test-workload-placement-tmpol-5840/testpod phase Pending desired Running
I0801 12:35:16.155004   39136 pod.go:89] pod e2e-test-workload-placement-tmpol-5840/testpod phase Pending desired Running
I0801 12:35:26.161026   39136 …
```
=> e2e: serial: fix usage of the pause container image in the e2e serial suite

test/e2e/serial/tests/workload_placement.go
In case we have more than two workers, but some of them have
inconsistent NUMA zones (e.g. BM + VM workers in the same pool),
we can have a panic due to the void assumptions that all the workers
have the same NUMA zones.
This is arguably more a cluster configuration issue than a test flaw,
but the test should not panic nevertheless.
=> e2e: serial: handle > 2 workers

test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_unschedulable.go, test/utils/noderesourcetopologies/noderesourcetopologies.go
These set of tests deploy pod, deployment and daemonset such that the
workload requests allocatable and not the available resources at a
node level because of which the workload is not scheduled on the node.
=> e2e: serial: unschedulable: requesting allocatable resources on a node

test/e2e/serial/tests/workload_placement.go
The test fails in CI but passes locally. Print the logs of the scheduler pod upon failure to manage troubleshooting the issue causing this step to fail.
=> e2e: print scheduler logs upon failure 

controllers/numaresourcesoperator_controller.go, controllers/numaresourcesscheduler_controller.go, main.go
split safe fixes and improvements from #363. Leave the core changes (use common logger + enable iso8601 format) in #363.
=> logs: improvement split from #363

Makefile
As part of #330, need proper Makefile targets for new must-gather tests created in #339.
=> Add Makefile targets for must-gather tests

.github/workflows/cibuild.yml, .github/workflows/ciformat.yml, .github/workflows/cilint-custom.yml, .github/workflows/cilint.yml, .github/workflows/e2e-tools.yml, .github/workflows/e2e.yml
Add new lane to exercise the helper tools we collected
over time. The new lane will run against a intentionally
unconfigured cluster: we need only the CRDs (and some CRs)
deployed, not the full NROP.
=> gh actions: bootstrap the tools lane

.github/workflows/e2e-tools.yml, .github/workflows/e2e.yml
Among the tools part of the base images the gh actions runners
use, there's kustomize; so let's use it instead of wasting
time downloading and building it.
=> gh actions: reuse host kustomize

main.go
In the regular and expected flows, the operator will own and manage the
API CRD when asked to deploy the main part (NRO object, deploying API +
RTEs). In some cases, most notably to test partial scenarios or
non-regressions, is it handy to have the CRD definition alone, to easily
set up scenarios.
We evaluated adding a trivial, 20-30 lines new helper tool just to emit
the CRD manifests, but while the source code was trivial, the binary
artifact was a whopping 30 megs (k8s deps), so the best compromise
seems to extend the existing render mode of the operator.
=> render: add option to render only the CRD

test/e2e/serial/tests/non_regression_fundamentals.go
Add tests to cover the most fundamental behavior of the
NUMA aware scheduler when no NRT data is available.
The tests declare and verify the expected behavior of
the scheduler in this uncommon and extreme scenario.
=> e2e: serial: add nonregression fundamentals tests

test/e2e/must-gather/must_gather_test.go, test/utils/deploy/deploy.go, test/utils/objects/wait/numaresources.go
Namespace for some of the elements of the NRO cannot be known in advance
so it is better to read it from the NRO status
correction over: #339 
issue: #330 
blocks: openshift/release#31102
=> e2e:must-gather: Get NRO namespace from status

test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/workload_placement.go, test/utils/noderesourcetopologies/noderesourcetopologies.go
Add new test that attempts to schedule a pod requesting resources that are greater than allocatable at numa level, and verifies the pod keeps on pending.
=> serial: check pod requesting unallocatable resources is unschedulable 

test/e2e/must-gather/must_gather_suite_test.go, test/e2e/must-gather/must_gather_test.go
must-gather is only supported on OCP platform so we should skip all the test suite in any other platform
correction over: #339 
issue: #330 
blocks: openshift/release#31102
=> e2e:must-gather: Run must-gather e2e test suite only in OCP Platform

test/utils/fixture/fixture.go
OCP >= 4.12 wants to have stricter podsecurity rules.
In our e2e tests we do a bunch of stuff, including running privileged
pods. We just annotate the test namespace(s) to signal we need top
privileges. Since e2e tests run in very controlled envs (CI mostly),
and since test namespace should be gone anyway once the e2e tests
are finished, this is still fair game.
=> e2e: fixture: add podsecurity labels

test/e2e/serial/tests/workload_placement_tmpol.go
The memory alignment test was expecting to find a message in the pod events indicating that although the pod resources were available on compute node level, alignment of both containers could not be achieved on a single numa node, one container per numa as per the assumption that the tests run only when TMscope=container.
The test failed to find that expected message because there were no candidate nodes in the first place, the reason was a lack of memory resources. The pod was requesting 9Gi, while the free resources left on the target node were only 8. The reason it was set to 8 is because of the false thought that there will be base memory on that node, which is usually 4.5Gi, which makes sense that 4.5Gi + 8Gi is way more than enough, but that is a mistake. because when …
=> serial: fix memory requests and free resources on target node

rte/main.go, rte/pkg/sysinfo/sysinfo.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_unschedulable.go
In the latest internal CI cluster run we have a string of failures:
```
Summarizing 9 Failures:
[Fail] [serial][disruptive][scheduler] numaresources workload placement considering taints when cluster has two feasible nodes with taint but only one has the requested resources on a single NUMA zone [BeforeEach] [test_id:47594][tier1] should make a pod with a toleration land on a node with enough resources on a specific NUMA zone 
/home/fromani/go/src/github.com/openshift-kni/numaresources-operator/test/e2e/serial/tests/workload_placement_taint.go:111
[Fail] [serial][disruptive][scheduler] numaresources workload placement Requesting resources that are greater than allocatable at numa level [It] [test_id:47613][tier3] should not schedule a pod requesting resources that are not allocatable at …
```
=> e2e: serial lane cleanup and fixes

Dockerfile.pause, Makefile, README.tests.md, test/e2e/serial/tests/workload_placement_tmpol.go, test/utils/images/consts.go, test/utils/objects/consts.go
We should never use `pause` as entrypoint in initcnt, because `pause` by design will never terminate, so the init containers
will never terminate, so the pod will never go running.
Now that we have an enhanced pause image (or a image with both pause and sleep in general), we can safely change the entrypoint to just sleep for a tiny bit as entry point.
=> e2e: serial: enhance and use the pause image

test/e2e/serial/README.md, test/utils/fixture/fixture.go
We originally added the cooldown time to allow the cluster state to settle down after a test run. But that was always meant a safeguard. Now we have 50+ specs, and 50+ specs each waiting 30s is now contributing significantly to the suite wall clock execution time.
Let's start to improve. Let's add a env var to override this value, so we can start checking if lower values (ideally zero) are now OK.
=> e2e: fixture: serial: configurable cooldown

test/e2e/serial/tests/workload_placement_tmpol.go
Schedule a pod with 2 containers, where the containers` requests are available under two possible nodes, but only one of them has the devices on a single numa in such a way that each device is available on a different numa. The pod is expected to be scheduled on the feasible node with relevant conditions in terms of availability on single numa nodes.
=> e2e:serial:tmpolicy: test device NUMA alignment

test/e2e/serial/README.md, test/utils/fixture/fixture.go
We continue our quest to cut down the test execution wall clock time begun in 3aed1168f2684f29276bc308890de319e72046eb .
One of the reasons why we introduced the cooldown at all, was to make sure the cluster was settled after the test execution. But this should actually be done at test teardown time.
The test teardown must ensure the cluster is restore at its state before the current test started, or it's a bug in the test fixture.
In practical terms, we add another knob to configure the test *teardown* time, so we can play with lower cooldown but increase the teardown if needed, to improve the execution time without destabilizing (read: uncover too many issues at once) the suite.
The key difference is we always wait for the full cooldown time, inconditionally, while we wait UP TO the …
=> e2e: serial: fixture: configurable teardown time

test/e2e/serial/README.md, test/e2e/serial/tests/workload_placement_tmpol.go, test/utils/fixture/devices.go
Add new environment variables for the devices names E2E_NROP_DEVICE_A, E2E_NROP_DEVICE_B, and E2E_NROP_DEVICE_C, that is to enable running the tests with any device type and not limited to specific types.
Add new tests with pods requesting device resources and check the alignment of these pods to the nodes.
=> serial: add tests with device resources

test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/sched_removal.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement_tmpol.go
- remove padding functionality for pod scope
- add new negative test to check the alignment of 2 containers on different numa zones when tmscope is pod
- reverting commit: https://github.com/openshift-kni/numaresources-operator/commit/fddf6661bfc2f93b11821a7b9f65a27fd6637dc8
=> serial: add negative test with pod scope and devices

test/e2e/serial/README.md, test/e2e/serial/config/config.go, test/e2e/serial/tests/configuration.go
Enable the user to use the RTE image they want in the test by setting this environment variable E2E_RTE_CI_IMAGE. This is especially needed for d/s CI as it is using disconnected environments which cannot pull quay images if they are not mirroredas anticipated.
=> serial: add the new variable E2E_RTE_CI_IMAGE

test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/non_regression_fundamentals.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_nodelabel.go, test/e2e/serial/tests/workload_placement_resources.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go, test/utils/fixture/fixture.go
regardless of the cooldown time, it doesn't make sense to cooldown if the test skipped for unmet prererquisites, which is actually the only reason why we should skip at all in this suite.
=> e2e: serial: avoid cooldown on test skip

test/utils/fixture/fixture.go
NROP tests are failing on OCP 4.12 due to the stricter podsecurity rules as it causes the pods created on the test namespaces to not get created due to the following error message:
```
Message: "pods \"padder-6757\" is forbidden: violates PodSecurity \"restricted:v1.24\": allowPrivilegeEscalation != false (container \"padder-6757-cnt\" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container \"padder-6757-cnt\" must set securityContext.capabilities.drop=[\"ALL\"]), runAsNonRoot != true (pod or container \"padder-6757-cnt\" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container \"padder-6757-cnt\" must set securityContext.seccompProfile.type to \"RuntimeDefault\" or \"Localhost\")",
```
Add missing pod security label …
=> e2e: fixture: add pod-security label

test/e2e/serial/tests/configuration.go
Enhance tests by:
- Remove redundant padding.
- Split a test case into two gaining two independent tests.
- Add more reports clarifying the test's steps
For more details please find the commit messages.
=> serial: enhance test verbosity and reduce execution time

go.mod, go.sum, pkg/numaresourcesscheduler/manifests/yaml/deployment.yaml, pkg/objectupdate/rte/rte.go, rte/main.go, test/e2e/rte/rte_test.go, vendor/github.com/k8stopologyawareschedwg/podfingerprint/README.md, vendor/github.com/k8stopologyawareschedwg/podfingerprint/podfingerprint.go, vendor/github.com/k8stopologyawareschedwg/podfingerprint/tracing.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go, vendor/modules.txt
Create empty directory using tmpfs to hold the NRT cache traces if they are enabled; if not this is not to consume relevant resources, so we can keep it always enabled.
Note this is a NOP at this point in time - the scheduler plugin code is still under development. But the above reasoning still holds: from both operator and scheduler plugin this is a very cheap and backward compatible change.
Enable PFP debugging for  RTEs, consuming the functionality from the latest u/s release. Enable dumping on their PFP status files on tmpfs. Even more than for the scheduler plugin, we can keep this always enabled from storage perspective.
=> rte: sched: manifest: enable sched plugin tracing

rte/main.go, test/e2e/rte/rte_e2e_suite_test.go, test/e2e/rte/rte_local_test.go
We used to have the default TM scope "container".
This works - and it is actually the k8s default, but prevents the overriding from every source.
Fix the code allowing override of TM scope.
Note this now requires the value to be always provided in some form. Since we always provide the configmap with the scope and policy settings, this should be ho harm.
=> rte: config: fix setting of TM scope

test/e2e/rte/rte_e2e_suite_test.go, test/e2e/rte/rte_local_test.go, test/utils/runtime/runtime.go
The prow CI stores the `exporter` binary in a different path when running the e2e tests. Handle different path in the suite setup.
=> test: e2e: rte: fix configuration test

test/e2e/serial/tests/workload_placement_tmpol.go
The test is failing because the test pod was scheduled on a non-target node, hence on a node that was supposed to be unsuitable because it has free resources but are not enough for allocating the test pod.
In order to make the node unsuitable, we must specify the amount of the free resource's type that is being requested by the pod, otherwise, that kind of resource will stay entirely free and will not be padded as expected, making the "unsuitable" nodes as candidates for the test pod, a thing which happened in this test case.
Adjust the unsuitable amount of free devices of Type1 making it impossible to count those nodes as candidates for the test pod.
=> e2e: fix unsuitable free devices amount

rte/pkg/config/config.go, rte/pkg/config/config_test.go, rte/pkg/podrescompat/client.go, rte/pkg/podrescompat/client_test.go, rte/pkg/podresfilter/client.go, rte/pkg/podresfilter/client_test.go, rte/pkg/sysinfo/sysinfo.go, rte/pkg/sysinfo/sysinfo_test.go
tidy up the boilerplate and add tests to the `podresfilter` pkg, which weren't mistakely left out from #457
=> rte: cleanup code

test/e2e/serial/tests/configuration.go
The test fails to set the scheduler name under the test's pod because nroSchedObj.Spec.SchedulerName does not exist, thus it returns an empty value, which later would be translated to the default kube scheduler name instead of the test scheduler name. The scheduler name is defined under Status not under Spec of the numaresourcesscheduler CR.
Modify the scheduler name properly in Status.SchedulerName to check the anticipated test's result.
get it from status instead of spec.
=> serial: update scheduler name properly

test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_nodelabel.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go, test/utils/noderesourcetopologies/noderesourcetopologies.go, vendor/k8s.io/kubernetes/pkg/apis/core/v1/helper/qos/qos.go, vendor/modules.txt
Add new tests involving device resources with burstable pods that are expected to be scheduled.
TC ids: 54024, 55450
=> serial: add new tests with device resources

test/e2e/serial/tests/workload_placement.go
The test with its older version is supporting only TMscope=container, because it creates the test's pods with two containers each expected to be placed on different numa zones of the target node. When running this scenario on a cluster with tmscope=pod the test's pod with TAS scheduler fails to run because of insufficient resource availability on a single numa node, while the pod with default scheduler hits TAE.
Support this TC to run on TMscope=pod by padding the target node zones leaving room only for the one pod resource and adjusting the pod.Spec accordingly.
=> serial: support test for pod TMscope

api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go, bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml, config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml, controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go, pkg/machineconfigpools/machineconfigpools.go, pkg/normalize/normalize.go, pkg/normalize/normalize_test.go, test/e2e/serial/tests/configuration.go
This is another refinement of #431 and a followup of #456 
We want to normalize earlier the NodeGroupConfig (see specific commit) to make sure we do meaningful reports of the observed config, and we want to decouple the NodeGroupConfig reporting from the MCP status reporting. Even though both share the same Status object, they should be updated indpendently and in different places in the flow.
Add cleanups and refactorings to improve testability (and some tests) along the way.
=> RTE: further improvements about node group config status reporting

internal/wait/replicaset.go, test/e2e/serial/tests/workload_placement.go
Test case 47627 was failing on the NRT consumed resources verification after creating the replica set. The expected resources were negative (CPU: -2) although the actual NRT reflects correct consumption on the target node.
Fix the test by:
- Adding missing checks like waiting for replicaset to be ready & for pods to get deleted
- Checking for consumed resources on node level b/c there are several replicas being scheduled and there is no guarantee of placement of all the pods on one numa zone. 
Additionally to other test code cleanup and enhancements, please refer to the commits for more details.
=> serial: fix failing test

internal/wait/deployment.go, internal/wait/replicaset.go, test/e2e/serial/tests/workload_placement.go
The functions are used only in this internal file and not called in other packages, thus unexport them, and rename ForReplicaSetComplete (to areReplicasAvailable) to keep consistent naming.
=> internal: unexport and rename internal helper functions

test/e2e/serial/tests/workload_unschedulable.go
The tests fail when calling corev1qos.GetPodQOS with &pods[0] when pods is a slice of pods resulting in the following error:
```
Test Panicked
In [It] at: /usr/local/go/src/runtime/panic.go:89
runtime error: index out of range [0] with length 0
```
What should be actually passed to the function is the first pod's address in the slice.
=> serial: pass pod's address properly to the function

hack/run-test-e2e.sh, hack/run-test-install-e2e.sh, hack/run-test-must-gather-e2e.sh, hack/run-test-serial-e2e.sh, hack/run-test-tools-e2e.sh, hack/test-e2e-runner.sh
Migrating ginkgo to V2 causes the suites to exit after 1 hour by default: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#timeout-behavior `Finally, the default timeout has been reduced from 24h down to 1h. Users with long-running tests may need to adjust the timeout in their CI scripts.` Serial suite needs more than that, a thing that causes to skip around 18 tests, so increase that timeout to 5 hours for now.
=> hack: add ginkgo v2 timeout for serial

.github/workflows/cibuild.yml, .github/workflows/ciformat.yml, .github/workflows/cilint-custom.yml, .github/workflows/cilint.yml, .github/workflows/e2e-local.yaml, .github/workflows/e2e-tools.yml, .github/workflows/e2e.yml, .github/workflows/release-operator.yaml, Dockerfile, Dockerfile.pause, Dockerfile.tests, api/numaresourcesoperator/v1alpha1/groupversion_info.go, api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go, api/numaresourcesoperator/v1alpha1/numaresourcesscheduler_types.go, pkg/k8sclientset/generated/clientset/versioned/fake/register.go, pkg/k8sclientset/generated/clientset/versioned/scheme/register.go, test/e2e/serial/tests/workload_unschedulable.go
Update the buildchain to golang 1.19, plus the mechanical fixes because gofmt 1.19 is now stricter.
=> build: move to golang 1.19

pkg/objectnames/objectnames.go
This will unlock future backports
=> [release-4.11][manual][partial] objectnames: add default scheduler CR Name

.github/workflows/release-testsuite.yaml, Makefile, README.tests.md, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/numaresources-operator.clusterserviceversion.yaml, config/samples/nodetopology_v1alpha1_numaresourcesscheduler.yaml, doc/examples/sched.yaml, test/utils/objects/objects.go
the 4.13 cycle is started, bump versions and references accordingly.
=> tree: move main to 4.13

test/e2e/serial/README.md, test/utils/fixture/fixture.go
partial backport of https://github.com/openshift-kni/numaresources-operator/pull/434
add facilities to avoid cooldown on skip
partial backport of https://github.com/openshift-kni/numaresources-operator/pull/421
add the option to override cooldown and teardown timeouts using env vars.
=> [release-4.11][manual][partial] avoid cooldown on test skip

go.mod
Now that we have updated all the deps and the toolchain, we can declare golang 1.19 as minimum required version in go.mod.
=> golang: require golang 1.19 in go.mod

Makefile
We had no real reason to be stuck to envtest 1.21
=> Makefile: envtest: bump to 1.24

controllers/kubeletconfig_controller_test.go, controllers/numaresourcesoperator_controller_test.go, internal/objects/objects.go
We use the renamed import `nropv1alpha` to pull in the API package _almost_ everywhere. Fix the few places where we don't, for uniformity's sake and to make the future v1 API transition a little easier.
No intended change in behavior.
=> chore: internal: rename import to nropv1alpha1

controllers/kubeletconfig_controller_test.go, controllers/numaresourcesoperator_controller_test.go, internal/objects/objects.go
We use the renamed import nropv1alpha to pull in the API package almost everywhere. Fix the few places where we don't, for uniformity's sake and to make the future v1 API transition a little easier.
No intended change in behavior.
=> [manual][release-4.12] chore: internal: rename import to nropv1alpha1

controllers/controllers_suite_test.go, controllers/numaresourcesscheduler_controller.go, controllers/numaresourcesscheduler_controller_test.go, pkg/numaresourcesscheduler/objectstate/sched/sched.go, pkg/numaresourcesscheduler/objectstate/sched/sched_test.go, test/utils/clients/clients.go
make sure we rename the api packages always using the same name, which will make transition to newer API easier.
No changes in behaviour
=> chore: make the api package import rename uniform

controllers/controllers_suite_test.go, controllers/numaresourcesscheduler_controller.go, controllers/numaresourcesscheduler_controller_test.go, pkg/numaresourcesscheduler/objectstate/sched/sched.go, pkg/numaresourcesscheduler/objectstate/sched/sched_test.go, test/utils/clients/clients.go
make sure we rename the api packages always using the same name, which will make transition to newer API easier.
No changes in behaviour
=> [release-4.12][manual] chore: make the api package import rename uniform

.github/workflows/release-operator.yaml, .github/workflows/release-testsuite.yaml, Dockerfile.tests
Add provisions to build and upload the tests image alongside the existing flow for the operator images
4.10 specific note:
updated hardcoded version to 4.10
=> [release-4.10][manual] gh actions: add functionality to refresh the testsuite image

controllers/kubeletconfig_controller.go, controllers/numaresourcesoperator_controller.go, controllers/numaresourcesscheduler_controller.go, internal/nodes/nodes.go, nrovalidate/main.go, pkg/validator/noderesourcetopologies.go, test/e2e/sched/install/install_test.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_nodelabel.go, test/e2e/serial/tests/workload_placement_resources.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go
A `context.TODO()`, which is meant as placeholder and prevents cancelation propagation. It's time to clean up our usage of those.
Avoid using `context.TODO()` when calling client functions in our controllers, to enable cancel propagation.
So add explicit context argument to our library functions and update the call sites accordingly.
=> context: wire up context, avoiding TODO

pkg/validator/podstatus.go
In order to make the output clearer and easier to consume, account the non-running pod in the AreaKubelet.
These are node-local issues, not cluster-wide issues.
=> validator: podstatus: use AreaKubelet

test/e2e/serial/tests/workload_placement_tmpol.go
Catch up with u/s https://github.com/kubernetes-sigs/scheduler-plugins/pull/547
We fix the expected message within events when a container/pod is unschedulable. Previously, we had to use custom strings, but now we can leverage the constants declared in the `nrosched` utility package, on which we depend already anyway.
=> e2e: serial: fix expected event on error

api/numaresourcesoperator/v1/numaresourcesoperator_defaults.go, api/numaresourcesoperator/v1/numaresourcesoperator_defaults_test.go, api/numaresourcesoperator/v1/numaresourcesoperator_normalize_test.go, api/numaresourcesoperator/v1/numaresourcesoperator_types.go, api/numaresourcesoperator/v1alpha1/numaresourcesoperator_conversion.go, api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go, bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml, config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml, pkg/objectupdate/rte/rte.go, pkg/objectupdate/rte/rte_test.go, test/e2e/serial/tests/scheduler_cache.go
Add option (new enum value in `NodeConfig`) to compute the PFP using only pods which have exclusive resources allocated, which are also the only kind of resources which can be accounted per-NUMA.
IOW considering all pods actually create unnecessary noise.
Accounting only exclusive resources is the most correct thing to do.
Note this is meant to (greatly) improve the jobs situation, but not completely solve it.
The kubelet is supposed to return the correct set of pods straight on, so it's likely we have a bug in the kubelet side.
=> rte: enable PFP computation considering only pods with exclusive resources assigned

go.mod, internal/schedcache/synced.go, nrtcacheck/main.go, pkg/validator/schedcache.go, vendor/k8s.io/klog/v2/klogr/README.md, vendor/k8s.io/klog/v2/klogr/klogr.go, vendor/modules.txt
Add an option to just dump the node status (provided by RTE).
Differently from the scheduler, which dumps the status only if the resync fails, the RTEs always do.
Knowing the state of RTEs comes almost for free, and makes troubleshooting easier.
=> nrtcacheck: add option to dump node states

test/e2e/serial/tests/configuration.go
Running test 47674 was leaving crashed mcp settings on one of the nodes causing the mcp to stuck in updating status forever, hence incompatible env for the next test to run.
The reason behind this is that the test was not waiting properly for the updates on relevant mcps to start, and then finish updating.
When updating the NROP label to the new mcp, this triggers an update on the old mcp, which takes time for it to finish. Before this PR, the test was only waiting on the new mcp to get updated while ignoring the old mcp status. The test continues to run the later checks and even tearsdown while the old mcp was still in updating status. One part of the teardown is restoring initial labels on the nodes and at last, delete the new mcp that was created for the test purpose. Added all up: …
=> serial: fix reboot testcase and properly wait on mcp updates

api/numaresourcesoperator/v1/numaresourcesoperator_defaults.go, api/numaresourcesoperator/v1/numaresourcesoperator_defaults_test.go, api/numaresourcesoperator/v1/numaresourcesoperator_normalize_test.go, pkg/objectupdate/rte/rte_test.go
the "execlusive-resource" pfp method is not tested well enough yet, it's safer to fall back to the old method for a little more.
=> rte: revert to "method=all" PFP by default

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manager/manager.yaml, internal/nodes/nodes.go, pkg/numaresourcesscheduler/manifests/yaml/deployment.yaml
We can now use the modern node-role labels to identify control plane nodes. No need to use anymore obsolete terms.
=> manifests: drop obsolete node-role labels

internal/wait/noderesourcetopologies.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go, test/utils/noderesourcetopologies/noderesourcetopologies.go, vendor/github.com/k8stopologyawareschedwg/noderesourcetopology-api/pkg/apis/topology/v1alpha2/helper/attribute/attribute.go, vendor/modules.txt
We should in general very, VERY careful when factorizing code in e2e tests.
We totally DO NOT want to add coupling to tests, and when we factor code we need to make really sure we're factoring code which does so general that a failure or a bug _always_ means a critical failure in the context of tests.
Easy candidates are setup helpers and expectations.
Turns out we check quite some expectations about proper NRT resource accounting, so let's reuse expectations for the
most obvious candidate sites.
Previously, we just checked for _A_ change in the NRT list, which was very crude and caused frequent flakes.
Now we wait for a targeted change in the very NRT object we care about, then we check that change is what we expected.
This is more precise, more correct and, at least in the initial runs, …
=> e2e: serial: resacct improve and generalize expectations

.github/workflows/e2e-tools.yml, .github/workflows/e2e.yml
The runners are consuming kind 0.20 now, and we're stuck on kube 1.24 for no good reason. Bump to 1.26.
=> ghactions: kind: update image

internal/wait/job.go, pkg/objectupdate/sched/sched.go, pkg/objectupdate/sched/sched_test.go, test/e2e/serial/tests/scheduler_cache.go, test/e2e/serial/tests/scheduler_cache_stall.go
The default scheduler framework setting watches pod not in terminal phase. On the node, the podresources endpoint does report also pods in  terminal phase, up until are deleted. This mismatch creates differences in PFP value, so the scheduler never reconciles, leading to a so-called "scheduler stall".
While workaround were provided (podExcludes), noone was deemed conclusive. The implemented for the short/mid term is to just have another separate independent informer watching pods in all states, just and only to serve the NRT scheduler plugins.
In this change we add tests to trigger scheduler stalls and exercise the code, making sure stalls are avoided.
The easiest way to create undeleted pods in terminal phase is to use jobs, so this is what we do.
Note this group of tests intentionally …
=> e2e: serial: kickoff tests for scheduler stall

test/e2e/rte/rte_e2e_suite_test.go, test/e2e/serial/e2e_serial_test.go
We reset the random seed, so let's make sure we print what we use. Ideally we should integrate with ginkgo and/or make the seed configurable. Let's at least make it explicit the seed we use as starting point.
=> e2e: print random seed being used

test/e2e/serial/README.md, test/e2e/serial/config/fixture.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/non_regression_fundamentals.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/scheduler_cache.go, test/e2e/serial/tests/scheduler_cache_stall.go, test/e2e/serial/tests/scheduler_removal.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_nodelabel.go, test/e2e/serial/tests/workload_placement_resources.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go, test/utils/fixture/fixture.go
Following https://github.com/openshift-kni/numaresources-operator/pull/598, https://github.com/openshift-kni/numaresources-operator/pull/608 stabilize the e2e tests even more by verifying after each test that the NRT data is settled to the initial. This will help in troubleshooting failures related to to unclean NRT data and in a meaninful cooldown.
PS: we assume that the cluster is clean before running the suite, as in it doesn't have workloads apart from the system and setup workloads that are needed for executing serial. Also, we assume no sudden interrupts, resources consumptions/releases during the run, which was also the case before this update.
=> e2e: verify nrt data after each test

test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_nodelabel.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go
Some tests fail often in CI on inconsistent accounting in NRT data, and pass after rerun. To assure the NRT data is relaible at the checking point, need to wait enough for the data to be settled and only then to compare the outputs.
=> e2e: add missing wait for NRT to settle

pkg/validator/validator.go, test/e2e/serial/config/config.go, test/e2e/serial/e2e_serial_test.go
Enhance the serial suite to fail inmmediately if the topology policies in the NodeResourceTopology objects are not aligned with the TAS prerequisites:
- policy: single-numa-node
- scope: pod/container
=> e2e: serial: Fail fast if policies not aligned

cmd/nrtcacheck/main.go
due to a oversight, the code was not update to use the v1 API.
=> nrtcacheck: use v1 API

test/e2e/serial/config/config.go
The kubelet sets defaults for Topology Manager policy and scope when a value is not explicitely set in the configuration.
Let's support this scenario, copying the kubelet defaults. 
We should get them programmatically and from the right kubelet version, but the saving grace is the values don't change
frequently (if at all).
In addition, starting NRT API v1alpha2, the "topologyPolicies" field is deprecated in favor of Attributes.
Albeit not  needed for the enhancement,  we take the chance to make this code more forward-looking switching to comparing attributes.
=> e2e: serial: support kubelet defaults in validation

test/e2e/serial/tests/non_regression_fundamentals.go, test/e2e/serial/tests/scheduler_cache_stall.go
When running the tests on a cluster with default configuration, the default value of scheduler's CacheResyncPeriod is reflected in the object's status and not in spec. The tests do not change this field so they run on default configuration and when fetching it from spec the value is not found hence skipping tests.
Fetch the scheduler's CacheResyncPeriod from its status instead to enable running the tests. This is also true if the value is not default.
=> serial: fetch CacheResyncPeriod from Status

hack/run-test-e2e.sh
In the early days of the operator we disable the scheduler tests by default to keep the CI stable.
Now when the project is mature enough, we should always run those tests for maximum coverage.
=> e2e: run scheduler tests by default

Makefile
In some cases we don't really need the fully static compilation and we can depend on system libraries.
=> Makefile: build: use shared libraries

internal/schedcache/synced.go
was kept only because incomplete replace
=> internal: drop stale v1alpha1 API ref

test/e2e/serial/config/config.go
In case NRTs don't exist that will return an error and the node name should be logged based on what's there in kconfig map, because nrt list will be empty, and addressing an item in an empty list will cause the program to panic.
=> serial: fix nil pointer in log

Dockerfile, Dockerfile.must-gather, Dockerfile.openshift, Dockerfile.openshift.rte, Dockerfile.openshift.tests, Dockerfile.pause, Dockerfile.tests, Dockerfile.tools, test/deviceplugin/cmd/numacell/Dockerfile
For RHAOS 4.14 we should rebase on ubi9 for binary artifacts
=> base image: ubi8 to ubi9

Dockerfile.tools
The package got renamed in ubi9, and that prompted the question: do we still need it? It seems we don't.
=> Dockerfile: tools: drop python2

Makefile
The serial suite is NOT meant to be distribute outside CI and NOT supported anyway, so we can use fully static build for this suite executable.
=> e2e: build: use fully static build for serial

Makefile
add more focused targets:
test-controllers: controllers-only integration tests test-unit-pkgs: pkgs unit tests proper
keep the `test-unit` target with the old semantics for backward compatibility.
=> Makefile: split test-unit

internal/noderesourcetopology/attributes.go, internal/noderesourcetopology/tostring.go, internal/noderesourcetopology/tostring_test.go, test/e2e/serial/config/config.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_nodelabel.go, test/e2e/serial/tests/workload_placement_resources.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go, test/utils/noderesourcetopologies/noderesourcetopologies.go, test/utils/nrosched/nrosched.go, test/utils/padder/padder.go
`topologyPolicies` field is deprecated and should not be used. 
The new recommended approach is to use the attributes. 
Update our codebase to use an attribute instead of that field.
Fixes #630
=> Deprecate topology policies

.github/workflows/e2e.yml, Makefile, hack/kind-config-e2e-no-registry.yaml, hack/run-test-e2e.sh, rte/hack/deploy-devices.sh, rte/hack/manifests/sample-devices/configmap-dpa.yaml, rte/hack/manifests/sample-devices/daemonset-dpa.yaml, rte/hack/manifests/sample-devices/namespace.yaml, rte/hack/manifests/sample-devices/role.yaml, rte/hack/manifests/sample-devices/rolebinding.yaml, rte/hack/manifests/sample-devices/serviceaccount.yaml, rte/hack/undeploy-devices.sh, test/e2e/rte/rte_e2e_suite_test.go, test/e2e/rte/rte_local_test.go, tools/catkubeletconfmap/catkubeletconfmap.go
We previously failed to bail out early if the RTE lane was failing.
The runner script ultimately returns the exit code of the last executed command. Problem is: also the latest `if` block
is a command, and the evaluation of the command was successful, swallowing the RTE lane failure (if any).
The test per se seems to be failed because we incorrectly always check for the exporter binary availability. But the exporter binary is not meant to be here, in this lane: it is tested explicitely in the separate RTE local lane.
=> e2e: fix RTE lane

doc/examples/sched.debug.yaml, doc/examples/sched.nocache.yaml, doc/examples/sched.yaml
the `cacheResyncPeriod` is enabled by default since d4be591b
=> doc: sched: fix examples

.github/workflows/e2e-local.yaml, Makefile, test/e2e/rte/local/local.go, test/e2e/rte/local/local_suite_test.go, test/e2e/rte/rte_e2e_suite_test.go
The local rte tests are cluster-independent.
Although we're using ginkgo focus for running only the local tests,
the suite still tries to initialize the code in the other tests.
The test passed so far only becuase of the fact that
k8s e2e framework knows how to deal with the absence of kubeconfig file.
Therefore, we should have a sperate suite for the local tests
which doesn't import other tests that are depending on the
presence of a cluster.
=> e2e:rte: run local test separately

rte/hack/manifests/sample-devices/daemonset-dpa.yaml
Consume the enhanced sample device plugin image that allows reregistration of the devices in case of kubelet restart.
P.S: there is no failure noted before this change but seems more right to consume the enhanced version.
=> rte manifests: update sample-devices image

internal/podlist/deployment.go, internal/wait/deployment.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/workload_placement.go
The test fails in CI and passes locally. The test modifies the pod resources under the deployment and do some checks on the new pod. The part that is causing the test to fail is that it doesn't wait "long enough" for the new pod to get created, causing the automation to pick an old pod, hence failing in later node name check.
Investigating it deeper, even with same oc client the test kept passing locally. Yet managed eventually to reproduce it by running it using an ssh connection to the cluster. Not clear about the root cause at the moment, but it seems that when the automation is connected to the cluster actually matters in terms of how quick the check can be, as via exporting the KC the test had no chance of failing, but via ssh the test continuously failed, possible indicator that ssh …
=> e2e: fix flaky test 47591

internal/noderesourcetopology/equality.go, internal/noderesourcetopology/equality_test.go, internal/wait/noderesourcetopologies.go, test/e2e/serial/tests/configuration.go, test/utils/fixture/fixture.go
The cooldown is performed at the end of the test and its main goal is to validate that the NRT is reset to the initial value.
On reboot scenarios, this check always fails because it turns out that the memory distribution across the same numa zones of the same node is not similar after the reboot, but is always found the same on the node level.After investigation, it turns out that new capacities after reboot are reported as so by the kernel. Since this is a behavior we cannot control, we need to adapt it, and thus here we suggest relaxing the equality check of memory resources. We allow a deviation of 52Mi which should cover these differences.
=> Relax condition on reboot and a cleanup

test/utils/fixture/fixture.go
Several tests (+10) fail when waiting for NRT objects to settle due to timeout. The reason behind that is that the old unsettled values take a while to settle thus leaving insufficient time for the real settled data to count as needed as per the threshold (default 5).
To enhance this we have 3 options:
* increase the default timeout
* decrease the interval time
* lower the threshold to 4 (3 is too risky)
We do not want to lower the threshold count because it might be risky because the failing tests show that unsettled data can get to 3 or 4 count when measuring the threshold. Thus omitting this option. We go with a combination of adjusting the timeout and the interval. As per the tests, it looks like at the first ~25 seconds leftover data can still be there. We want to guarantee that in …
=> serial: adjust NRT settle timeout and interval

test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/scheduler_cache.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go
Some tests were skipped for unexpected reasons, fix that and fix the flakiness by waiting enough time for the NRTs to settle. See commits for more details on each change.
=> enable skipped tests & stabilize flaky tests

main.go
add command line flags and options to disable
the functionality, and disable it by default.
=> operator: metrics: hooks: add disabling options

test/utils/noderesourcetopologies/noderesourcetopologies.go
Attributes should be used when checking for NRT mutation.
This PR fixes #609
=> e2e: Check Attributes when checking NRT mutation

rte/main.go
served insecurely, and approaching EOL.
4.12 still supported and will have metrics re-enabled later.
=> [release-4.11] rte: disable metrics

main.go
and disable by default because served unsecurely.
4.11 is approaching EOL; 4.12 will restore correct support.
=> [release-4.11] metrics: add option to toggle on/off

main.go
webhooks are unneeded and expected to be disabled by default; for extra safety, force them on loclahost.
=> [release-4.11] nrop: webhook: serve on localhost

.snyk
these deps are pulled indirectly by test code,
used by mocking code.
=> snyk: exclude stretchr testify-related repos

.snyk
used only in optional validation tools,
not in the main operator binary
=> snyk: exclude deployer kubeletconfig package

test/e2e/serial/tests/workload_placement_taint.go, test/utils/k8simported/taints/LICENSE, test/utils/k8simported/taints/README.md, test/utils/k8simported/taints/helper.go, test/utils/k8simported/taints/taints.go, test/utils/k8simported/taints/taints_test.go
to remove the last dependency from k8s.io/kubernetes, we import (soft-fork) the taints package, and we fix our imports to use the bundled version.
backport notice: more backport is needed to be able to fully remove the `k8s.io/kubernetes` dependency
=> [release-4.13][manual] test: e2e: import and use the taints pkg from k8s

.golangci.yaml
let's exclude only code pseudo-vendored from k8s
=> lint: e2e: e2e tests should be linted

controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go
the `oc adm inspect` machinery tries first to gather the related objects, then gathers the object itself: https://github.com/openshift/oc/blob/release-4.15/pkg/cli/admin/inspect/resource.go#L188 Thus, if any of the the related objects can't be collected, neither can the parent object.
In our case, the nfs object were meant as forward-looking extra, but our attempt backfired. Let's remove them from the list, focusing only on what the operator is guaranteed to provide.
=> controller: minimize related object list

test/e2e/serial/e2e_serial_test.go
We tried to make serial suite runs reproducible,
but the effort was half baked:
- we emit the seed WE configure, but we don't allow to set it
- there's no way to ensure any other package resets the global seed
turns out this code is more harmful than useful, so we remove it and we reset to a clean slate.
=> e2e: serial: remove half-baked randomSeed

test/e2e/serial/tests/scheduler_removal.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/wait/daemonset.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/wait/deployment.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/wait/wait.go, vendor/modules.txt
the linter complains about code in this tests; rather than add a trivial patch, we take the chance to rewrite the wait loop using facilities gained by libs since the test was first introduced.
No intended change in behavior.
=> e2e: serial: rewrite deployment wait

test/e2e/serial/e2e_serial_test.go
Linter is warning about using depricated ginkgo reporter code to create polarion report. Looking deeper the reporter is not used while publishing the tests report, as we use the junit file which has its own autogenerated ReporterAfterSuite.Thus removing the related code which cuase the noise in linter check.
=> serial: remove ReporterAfterSuite to fix linter

internal/noderesourcetopology/attributes.go, internal/noderesourcetopology/tostring.go, internal/noderesourcetopology/tostring_test.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_nodelabel.go, test/e2e/serial/tests/workload_placement_resources.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go, test/utils/noderesourcetopologies/noderesourcetopologies.go, test/utils/nrosched/nrosched.go, test/utils/padder/padder.go
topologyPolicies field is deprecated and should not be used. The new recommended approach is to use the attributes.
Added two new attributes to handle policy and scope.
manual backport of #652
=> [release-4.13][manual] Deprecate TopologyPolicies field

test/utils/fixture/fixture.go
fix our helper to report which e2e code is skipping
- not where the actual ginkgo.Skip is ultimately invoked.
=> e2e: serial: more precise skip location

controllers/numaresourcesoperator_controller_test.go
In test code, when updating a non-instance (e.g. NROP, NRSCHED) object, we should use the main client update ('client.Update') not the status subresource update which is meant, well, only for status updates. This was likely sneaked in early on and gone unnoticed because the fake client is too permissive, but is going to blow on >= 1.27.
=> controller: test: don't update objects  via status()

hack/run-test-e2e.sh, test/e2e/rte/local/local.go, test/e2e/rte/local/local_suite_test.go, test/e2e/rte/rte_e2e_suite_test.go, test/e2e/rte/rte_local_test.go
move local exoporter tests in their own suite, backporting from 4.14
partial backport of #653
=> [release-4.13][manual] e2e: rte: backport local tests

controllers/numaresourcesoperator_controller_test.go
since e8432043 we have e2e test coverage, so we can relax this condition and tolerate the case on which we miss daemonsets.
=> controller: test: relax condition

pkg/numaresourcesscheduler/manifests/yaml/configmap.nrt.yaml, pkg/numaresourcesscheduler/objectstate/sched/sched_test.go, pkg/objectupdate/sched/fakeconfs.go
upstream is about to remove v1beta2, let's do the long-due upgrade to v1beta3.
No intended changes in behavior.
=> sched: manifests: move to v1beta3 for the config

go.mod, go.sum, pkg/loglevel/loglevel.go, pkg/loglevel/loglevel_test.go, pkg/objectupdate/rte/rte.go, test/e2e/rte/rte_test.go, test/e2e/serial/tests/workload_placement.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/flagcodec/flagcodec.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/schedparams.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/objectupdate/sched/render.go, vendor/modules.txt
this enables us to remove a longstanding ambiguity about `--v` vs `-v` and to fix a silent bug on which we BOTH set `--v` and `-v`, with the latter winning, opening the door for surprising bugs.
=>  flagcodec: always use flag normalization

go.mod, go.sum, internal/noderesourcetopology/equality.go, internal/wait/noderesourcetopologies.go, test/e2e/serial/config/fixture.go, test/e2e/serial/tests/resource_accounting.go, test/utils/fixture/fixture.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/sysinfo/hugepages.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/sysinfo/memory.go, vendor/modules.txt
Previously, the test fixture took its NRT snapshot before padding.
But padding is an essential component of testing, and requires guaranteed class pods to actually consume numa-local resources.
If we later check that conditions match, we will never ever converge because padding pods will be (correctly) counted to assess the node resource consumption.
The correct approach is then to take the expected state AFTER padding, considering padding pods as part of the cluster state, and right before any test-specific pod is scheduled.
Or, alternatively, to check the state excluding the padding pods which will make the test more complex (and thus fragile), and/or of questionable value.
The only remaining question is why this failure was gone unnoticed up until now.
=> e2e: serial: resource accounting: take cluster snapshot post padding

test/utils/fixture/fixture.go
Before this, if NRTs were failing to settle in the provided cooldown
time, we were hitting context.deadlineExceededError following the
updates done in
https://github.com/openshift-kni/numaresources-operator/commit/14c6bcb10c24aa6783b5293927eedd4b5baf27cb.
Clarify the failure to help better understand the issue, by providing
error reporting.
Additionally, increase the default cooldown timeout to allow the NRTs a proper stabilization time. 
see commits for more details.
=> support error reporting & increae default cooldown timeout

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
If we release our newer operator version without the correct metadata, it will release that new version just fine but at the same time it will unpublish all earlier versions in the channel, making the new version effectively the only entry in that channel.
This happens when a new operator bundle ships with a "skipRange" annotation but without the "replaces" property in the operators OLM metadata (CSV)
This PR adds the "replaces" property in addition to the "skipRange" property.
=> OCPBUGS-25763: Set base CSV replaces field

Dockerfile.openshift.tests
Initially, the numaresources-operator-tests image was configured exclusively for executing the serial test suite, which posed a challenge in achieving our goal of enabling it to run both serial and must-gather test suites. The modification of this image is driven by our intent to broaden its usage within our testing-related CI process. We aim to encompass as many test suites as possible under our CI pipeline.
To support our goal, we have introduced a must-gather runner script derived from the 'hack/run-test-must-gather-e2e.sh.' Note that we deliberately avoided bootstrapping the must-gather script to adhere to 'test-e2e-runner.sh,' as our objective is to provide flexibility beyond the constraints defined by ginkgo flags.
Signed-off-by: Sargun Narula <snarula@redhat.com>
=> runner: enable custom execution of test suites

hack/run-test-serial-e2e.sh
Enhance the runner script to support hierarchical tiers, abusing --focus for now, labels in the future.
What is "hierarchical tiers"?
Currently running tier2 tests means we run ONLY tier2 tests, not tier1 and tier2 tests. This is strictly speaking correct but is inconvenient. Introducing hierarchy means that if we select a tier (and enable hierarchy modes) then the tests which will run are the ones belonging to that tier and to all higher tier)
IOW the selected tier will mean "run all tiers up to this one, included".
Fixes: #815
=> hack: e2e: support hierarchical tiers in the runner

go.mod, go.sum, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/assets.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.14.cil, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.15.cil, vendor/modules.txt
bump deployer dep to consume selinux fixes for OCP >= 4.15
=> deps: deployer: consume ocp415 selinux fixes

Dockerfile.openshift.tests
The CMD command has been replaced with the ENTRYPOINT, the motive behind this is change was to consider the serial test runner as default.
Signed-off-by: Sargun Narula [snarula@redhat.com](mailto:snarula@redhat.com)
=> runner: replaced CMD

go.mod, go.sum, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/assets.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.14.cil, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.15.cil, vendor/modules.txt
consume updates in selinux policies.
=> [release-4.14][manual] deps: bump deployer to v0.17.1

test/e2e/install/install_test.go, test/e2e/serial/tests/non_regression_fundamentals.go, test/e2e/serial/tests/scheduler_cache.go, test/e2e/serial/tests/scheduler_cache_stall.go, test/e2e/serial/tests/workload_placement_resources.go, test/e2e/serial/tests/workload_placement_tmpol.go
Now that we have a simple way to run all tests up to a given tier, included (see: f69ac68a6375fec6ec355c44bd1c6d02a36a7593) we can review our tiers.
The ter1 tests had 47 tests, roughly, which is great on a hand but bad on the other hand, because the very purpose of tiering was to have a strict and well delimited set of tests.
We promote the most critical tier1 tests to tier0 tests. Tiering is not set in stone - tests will be moved among tiers.
But tier size should always kept at bay in the coming changes. As rule of thumb, no tier should contain more than 20-25% of total tests; and this is especially true for high (tier0/tier1) tests.
Fixes: #814
=> serial: tests: introduce tier 0

controllers/numaresourcesoperator_controller.go, main.go
Reflecting MCP conditions in the NRO object conditions is heavyweight and gives little extra value. Let's stop do that - the nested conditions are optional anyway, but let's add a command line option to re-enable it if really needed.
Note: "heavyweight" has to be put in context
=> controller: stop reflecting MCP conditions

internal/wait/daemonset.go
If a ds is updated and the current method is used to wait for the ds to be ready, the check will pass but in reality the ds pods will still need to be updated. this is because the check doesn't ensure the pods are updated.
Ensure that by adding the condition that the number of up to date pods under the daemoonset equals to the expected and ready number pods.
=> internal: verify ds pods are updated

pkg/objectupdate/rte/rte.go
If we replace the RTE image spec, that's an important event to make sure it is logged at the default verbosiness level (2).
We don't recommend set the verbosiness lower then 2 anyway.
=> rte: be louder when we replace the image

controllers/numaresourcesoperator_controller.go
This is almost certainly a relic of pre-historic times. It should be harmless, but also useless. Good riddance.
=> controller: nrop: remove useless context

.snyk
Added this file to be consumed by the snyk static analysis check.
Thereby, we can exclude packages that raise vulnerability warnings to silence them.
=> snyk: add exclude list for 4.13

.snyk
Added this file to be consumed by the snyk static analysis check. 
Thereby, we can exclude packages that raise vulnerability warnings to silence them.
=> snyk: add exclude list for 4.12

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml, pkg/loglevel/loglevel.go, test/e2e/rte/rte_test.go, test/e2e/serial/tests/configuration.go
Follow the convention by referring to single-letter identifier, -v here, with single hyphen.
A scheduler and deployer with similar PR will follow as well as bumping the versions.
=> flags: identify -v with single hyphen

Makefile, main.go, pkg/version/discover.go, pkg/version/version.go, test/e2e/serial/README.md, test/e2e/serial/e2e_serial_test.go, test/utils/configuration/configuration.go
Generalize the platform and version discovery and
move it into a function; the gaol is to have common code to discover **and log** and use it both in the operator and in the serial suite entry point, so in the latter we have clear logs.
=> version: generalize discovery

.golangci.yaml
Adding `depguard` linter to check for unwanted dependencies
Check https://golangci-lint.run/usage/linters/#depguard for more info
fix: #748
=> add check to prevent addition of k8s.io/kubernetes as dep

ARCHITECTURE.md, README.md
add a section in the README to sketch the future plans, and start an ARCHITECTURE document to describe in
broad strokes how the operator is designed.
=> docs: add architecture and roadmap

controllers/kubeletconfig_controller.go, controllers/kubeletconfig_controller_test.go, internal/objects/objects.go, pkg/kubeletconfig/kubeletconfig.go, pkg/kubeletconfig/kubeletconfig_test.go
MCO's KubeletConfig can be sent with empty payload, for example when configuring autosizing:
```
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
name: autosizing-master
spec:
autoSizingReserved: true
machineConfigPoolSelector:
matchLabels:
pools.operator.machineconfiguration.openshift.io/master: ""
```
In general there's not much we can do when obeserving these kubeletconfig objects anyway, so we skip them.
Please note: the control loop still depends on the fact there
1. is just one kubeletconfig object *with payload*
2. there's no merge logic
as it stands today both still should be core assumptions regarding how MCO works.
=> OCPBUGS-30236: controller: kubelet: skip config with empty payload

controllers/numaresourcesoperator_controller.go, pkg/objectstate/objectstate.go, pkg/objectstate/rte/rte.go
When computing RTE objectstate, distinguish between load error, which is mostly benign and can be safely tolerated, and update error, which means we can send garbage to the cluster, and if so it should be avoided.
In addition, revisit the logging to avoid swallowing errors.
=> controller: nrop: objstate: rte more granular error check

controllers/kubeletconfig_controller.go, controllers/kubeletconfig_controller_test.go, internal/machineconfigpools/machineconfigpools.go, internal/machineconfigpools/machineconfigpools_test.go, internal/objects/objects.go, internal/wait/kubeletconfig.go, rte/pkg/config/config.go, test/e2e/serial/tests/configuration.go
In #863 (https://github.com/openshift-kni/numaresources-operator/commit/3caa8294757cf4b98d554f0af813b7c77e5ed454) we added support to handle gracefully payload-less kubeletconfig objects. There's however another issue lurking: we can have multiple kubeletconfig objects.
Previously, the code was incorrectly assuming there is at most one kubeletconfig object in the cluster, targeting the MCP
worker pool.
But we can actually have more kubeletconfig objects as long as they don't target overlapping MCPs (e.g. with 2 MCPs we can have 2 kubeletconfig objects, say, or perhaps even 4 considering payloadless objects).
Thus, we need to fix our matching logic to handle this occurrence.
The fix is simple: just look for kubeletconfig which we target NodeGroups we are interested into, silently skipping …
=> kubeletconfig: ignore nonmatching kubeletconfig objects

api/numaresourcesoperator/v1/numaresourcesoperator_normalize.go, api/numaresourcesoperator/v1/numaresourcesoperator_normalize_test.go, api/numaresourcesoperator/v1/numaresourcesoperator_types.go, api/numaresourcesoperator/v1/zz_generated.deepcopy.go, api/numaresourcesoperator/v1alpha1/numaresourcesoperator_conversion.go, bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml, config/manifests/bases/numaresources-operator.clusterserviceversion.yaml, controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go, pkg/objectupdate/rte/rte.go, pkg/objectupdate/rte/rte_test.go, test/e2e/serial/tests/configuration.go
add support to inject (and override) the RTE tolerations.
The user-provided tolerations will completely override the manifests tolerations.
If the user removes the tolerations, then the operator will enforce again the manifest ones (possibly, no tolerations).
The recommended flow to add/change the default tolerations (if any) is to
1. find the owned daemonsets: nrop.Status.DaemonSets
2. lookup the owned daemonsets using the namespace/name pair found in
the previous step
3. inspect the DS manifests to learn about the current tolerations
4. set new tolerations in nrop.Spec.NodeGroup[*].Config.Tolerations
taking into account the existing ones
=> RFE-5013: RTE: add support to add extra tolerations

Dockerfile.tools, Makefile
never use floating tags in the build system, not
even for CI tests. Always pin explicit versions.
=> build: golang: remove 'latest' floating tag refs

api/numaresourcesoperator/v1/numaresourcesoperator_normalize.go, api/numaresourcesoperator/v1/numaresourcesoperator_normalize_test.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/tolerations.go
Make sure we compare sorted tolerations in the e2e tests, so we minimize flakes.
No intended changes in behavior.
=> e2e: api: add and use support to sort tolerations

test/e2e/serial/tests/tolerations.go, test/e2e/serial/tests/workload_placement_taint.go
add e2e test to cover invalid tolerations in the spec - NROP will act as passthrough here, by design
add e2e test to cover un-toleration while RTE is running, let's ensure the expected behavior
=> RFE-5013: RTE: more e2e tests

.github/workflows/cibuild.yml, .github/workflows/ciformat.yml, .github/workflows/cilint-custom.yml, .github/workflows/cilint.yml, .github/workflows/e2e-local.yaml, .github/workflows/e2e-tools.yml, .github/workflows/e2e.yml, .github/workflows/golangci-lint.yaml, .github/workflows/release-operator.yaml
no reason to be stuck on golang 1.20.z, not even on CI
=> toolchain: ghactions: bump toolchain to 1.21.z

controllers/kubeletconfig_controller.go, controllers/kubeletconfig_controller_test.go, internal/machineconfigpools/machineconfigpools.go, internal/machineconfigpools/machineconfigpools_test.go, internal/objects/objects.go, internal/wait/kubeletconfig.go, rte/pkg/config/config.go, test/e2e/serial/tests/configuration.go
This is a manual cherry-pick of #885
=> [release-4.14][manual] kubeletconfig: ignore nonmatching kubeletconfig objects

internal/nodes/nodes.go, internal/podlist/node.go, test/e2e/rte/rte_test.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_nodelabel.go, test/e2e/serial/tests/workload_placement_resources.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go
This functionality was already used scattered across the codebase, let's consolidate in a single function.
=> internal: expose function to list all pods on a node

controllers/kubeletconfig_controller.go, controllers/kubeletconfig_controller_test.go, internal/machineconfigpools/machineconfigpools.go, internal/machineconfigpools/machineconfigpools_test.go, internal/objects/objects.go, internal/wait/kubeletconfig.go, rte/pkg/config/config.go, test/e2e/serial/tests/configuration.go
This is a manual cherry-pick of #903
=> [release-4.13][manual] kubeletconfig: ignore nonmatching kubeletconfig objects

controllers/kubeletconfig_controller.go, controllers/kubeletconfig_controller_test.go, internal/machineconfigpools/machineconfigpools.go, internal/machineconfigpools/machineconfigpools_test.go, internal/objects/objects.go, internal/wait/kubeletconfig.go, rte/pkg/config/config.go, test/e2e/serial/tests/configuration.go
This is a manual cherry-pick of https://github.com/openshift-kni/numaresources-operator/pull/906
=> [release-4.12][manual] kubeletconfig: ignore nonmatching kubeletconfig objects

api/numaresourcesoperator/v1/numaresourcesoperator_normalize.go, api/numaresourcesoperator/v1/numaresourcesoperator_normalize_test.go, api/numaresourcesoperator/v1/numaresourcesoperator_types.go, api/numaresourcesoperator/v1/zz_generated.deepcopy.go, api/numaresourcesoperator/v1alpha1/numaresourcesoperator_conversion.go, bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml, config/manifests/bases/numaresources-operator.clusterserviceversion.yaml, controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go, internal/wait/daemonset.go, pkg/objectupdate/rte/rte.go, pkg/objectupdate/rte/rte_test.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/tolerations.go, test/e2e/serial/tests/workload_placement_taint.go
add support to inject (and override) the RTE tolerations.
The user-provided tolerations will completely override the manifests tolerations.
If the user removes the tolerations, then the operator will enforce again the manifest ones (possibly, no tolerations).
The recommended flow to add/change the default tolerations (if any) is to
1. find the owned daemonsets: nrop.Status.DaemonSets
2. lookup the owned daemonsets using the namespace/name pair found in
the previous step
3. inspect the DS manifests to learn about the current tolerations
4. set new tolerations in nrop.Spec.NodeGroup[*].Config.Tolerations
taking into account the existing ones
cumulative backport of #808 #887 #894 #901
=> CNF-11848: [release-4.15][manual] RTE: add support to add extra tolerations

test/e2e/serial/tests/tolerations.go
The test deletes ds and immediately checks for it to be ready using its object key. When there is no ds yet the test would fail because the object it is trying to search is not found on the cluster.
To prevent this from happening, add wait after the ds is deleted to make sure it is recreated with the expected pod count (not ready yet though).
This was also driving another failure in the next test (72861) where when it checks the number of pods owned by ds it retrieves a double count because of the terminating pods that still exist on the cluster:
```
shajmakh@shajmakh-thinkpadt590 ~ $ oc get ds,pod
NAME                                          DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                     AGE
daemonset.apps/numaresourcesoperator-worker   2 …
```
=> e2e: wait for ds creation before checking it is ready

.github/workflows/e2e-tools.yml, .github/workflows/e2e.yml, Makefile, hack/deploy-mco-crds.sh
catch up with MCO https://github.com/openshift/machine-config-operator/pull/4315
=> openshift: crd: update to deal with latest CRDs

test/e2e/serial/tests/resource_hostlevel.go, test/e2e/serial/tests/workload_placement_resources.go, test/utils/noderesourcetopologies/noderesourcetopologies.go
Add initial e2e coverage to make sure the
scheduler can deal with the ephemeral storage resource.
Fixes: #931
=> e2e: add tests for hostlevel resources

pkg/numaresourcesscheduler/manifests/yaml/configmap.nrt.yaml, pkg/numaresourcesscheduler/objectstate/sched/sched_test.go, pkg/objectupdate/sched/fakeconfs.go
The v1beta3 scheduler configuration is being phased out from the scheduler plugin repo (at least), so let's jump to v1. There are non functional changes anyway.
=> sched: api: generate config v1

test/utils/fixture/fixture.go
cleanup the function. Remove unused helper to narrow down the API surface. No intended change in behavior.
=> e2e: utils: cleanup MustSettleNRT

test/e2e/serial/config/fixture.go, test/e2e/serial/tests/resource_hostlevel.go, test/utils/fixture/fixture.go, test/utils/noderesourcetopologies/noderesourcetopologies.go, test/utils/noderesourcetopologies/noderesourcetopologies_test.go
Before this change, each test used the data of NRT list that was
gathered at the beginning of the suite and compared it with the NRT data gathered after each test to ensure the NRTs are settled. This is fine as long as the resources topology is guaranteed not to be updated in a way that messes up the teardown comparison.
Since we cannot specify the tools used to set up the resources in the
testing environment, hence no guarantee the topology would stay the same from the beginning of the suite till the end; we record the NRT data on each test fetching it directly from the cluster, independent from the data gathered at the start of the suite.
=> e2e serial: initiate NRT list in each test independently

go.mod
not really necessary because how we use golang
xref: https://go.dev/doc/toolchain
=> go.mod: remove `toolchain` directive

hack/run-test-serial-e2e.sh, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/non_regression_fundamentals.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/resource_hostlevel.go, test/e2e/serial/tests/scheduler_cache.go, test/e2e/serial/tests/scheduler_cache_stall.go, test/e2e/serial/tests/scheduler_removal.go, test/e2e/serial/tests/tolerations.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_no_nrt.go, test/e2e/serial/tests/workload_placement_nodelabel.go, test/e2e/serial/tests/workload_placement_resources.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go
reflect all tags but `testtype` and `test_id` into labels. From now on we should always add together labels and tags, if we add tags. Label is now the preferred way, but tags aren't forbidden yet, just deprecated.
=> e2e: align tags and labels

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manager/manager.yaml
In order to discover the deployment and/or the operator pod, filtering by `app` label is the recommended way.
We add the label to enable so.
=> manifests: label: add `app` label

doc/examples/pod.ctrreschk.yaml, doc/examples/pod.lshwinfo.yaml
ctrreschk is the successor of numalign.
Let's start using it, even if it's still in heavy development.
=> doc: examples: add ctrreschk examples

Makefile, tools/lstopics/lstopics.go
enable offline generation of topics.json, to enable bundle it into the tests image, or anywhere it is useful.
=> topics: add target and machinery to generate offline

Dockerfile.openshift.tests, Dockerfile.tests
`topics.json` belongs more to share than var (more akin to pci.ids) and, most important, `/usr/local/var` doesn't seem to exist by default.
=> Dockerfile: tests: move to share

api/numaresourcesoperator/v1/numaresourcesscheduler_defaults_test.go, api/numaresourcesoperator/v1/numaresourcesscheduler_normalize_test.go, cmd/nrtcacheck/main.go, internal/baseload/baseload.go, internal/nodes/nodes.go, pkg/objectnames/nodes.go, pkg/validator/schedcache.go, test/e2e/sched/install/install_test.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/tolerations.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_nodelabel.go, test/e2e/serial/tests/workload_placement_resources.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go, test/utils/fixture/fixture.go
`deployer` >= 0.19 provides most of the functionalities in `internal/nodes`. So we dissolve the latter and we move the code to use the former, to reduce the duplication, even if the API of the deployer package can use some refinement.
In addition, we get rid of another internal duplication by moving to `k8s/utils/ptr`
Fixes: #715 (probably)
=> cleanup: remove `internal/nodes`

internal/wait/machineconfig.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/tolerations.go, test/e2e/serial/tests/workload_placement.go
The PR is mainly targetting test 47674 stabilization distributed across few commits. so for more details please see each commit. 
The test goal is to check if updating configurable values under the
numaresourcesoperator CR is done successfully with the anticipated
affects.
The test is flaky in the ci because of mainly 2 issues:
1. waiting improperly for the mcp updates (see commit )
2. not handling the mcp errors on time but instead continuing with the
test steps
In this commit, we reorder the steps and simplify the test while
retaining the goal of it.
The initial scenario was like this:
1. pick target node
1.1. label it with new role "mcp-test"
1.2. remove the worker role
2. create new mcp targeting both roles: mcp-test & worker
2.1. wait on the mcp mcp-test to get updated
2.2. wait for …
=> e2e: simplify reboot test 47674 and minor fix

controllers/numaresourcesscheduler_controller.go, controllers/numaresourcesscheduler_controller_test.go
So far the scheduler priority is set to default which is 0 this is risky especially when the preemtion of pods is needed to fit more important pods.
The NRS is important enough to deserve the most critical priority class system-node-critical which is the same priority for the kube-scheduler.
addresses https://github.com/openshift-kni/numaresources-operator/issues/974
=> sched: controller: set scheduler priority

Dockerfile.tests
Fixes:
```
[1/2] STEP 1/6: FROM docker.io/golang:1.22 AS builder
[1/2] STEP 2/6: WORKDIR /go/src/github.com/openshift-kni/numaresources-operator
--> Using cache 4f2b3c666f19d45eeed07af4e62c7c8beeb21eea27661161549417ee3498a500
--> 4f2b3c666f19
[1/2] STEP 3/6: COPY . .
--> a1295d77765e
[1/2] STEP 4/6: RUN make build-topics
mkdir -p bin && go run tools/lstopics/lstopics.go > bin/topics.json
--> 3fe26ff2ccb9
[1/2] STEP 5/6: RUN make build-e2e-all
go fmt ./...
go vet ./...
go version go1.22.4 linux/amd64
go test -v -c -o bin/e2e-nrop-install.test ./test/e2e/install && go test -v -c -o bin/e2e-nrop-sched-install.test ./test/e2e/sched/install
go test -c -v -o bin/e2e-nrop-rte-local.test ./test/e2e/rte/local
go test -c -v -o bin/e2e-nrop-rte.test ./test/e2e/rte
go test -c -v -o …
```
=> build: build helper tools in the tests image

Dockerfile.openshift.tests
PR https://github.com/openshift-kni/numaresources-operator/pull/686 updated the non-OCP Dockerfile only. To preserve/increase image compatibility, we do now the same change for OCP Dockerfiles.
=> Dockerfile: align OCP/non-OCP

Makefile
This is needed by d/s builds to allow passing tags like `-tags strictfipsruntime`. If the env variable is not set, passing empty string as in `-tags ""` (not empty value as in `-tags `) will run the command without no disturbing.
=> Makefile: binary-all: support build with -tags

test/e2e/serial/tests/configuration.go
This PR follows #962 for adding the performance profile dependencies for reboot test cases.
It adapts to changes in the kubeletconfig through performance profile if it exists. This PR also adds test id to that test which is 75354.
This test is a reboot test case that is changing the kubeletconfig configuration. The changes here are for adapting the test to make the necessary changes to the kubeletconfig through performance profile if it exists in the first place otherwise if the system which is testing this has a performance profile and it tries to change it directly through kubeletconfig the test will fail.
=> e2e: adapt performance profile existence and stabilize test 

.github/workflows/e2e-tools.yml, doc/features/README.md, internal/api/features/_topics.json, internal/api/features/topics.go, internal/api/features/topics_test.go, internal/api/features/types.go, internal/api/features/types_test.go, main.go, test/e2e/serial/README.md, test/e2e/tools/mkginkgolabelfilter_test.go, test/e2e/tools/tools_test.go, tools/mkginkgolabelfilter/mkginkgolabelfilter.go
manual backport of several commits related to tests features introspection:
https://github.com/openshift-kni/numaresources-operator/pull/958
https://github.com/openshift-kni/numaresources-operator/commit/21b38df54dc28449b2c4b4da2e842008683e35e4
=> [4.16] add features introspection for e2e tests

test/e2e/serial/tests/configuration.go
[schedrst] is also a test tag/label and also a feature label for the serial suite. Add that tag where it's missing in the relevant tests.
=> e2e: add missing schedrst labels

test/e2e/serial/tests/configuration.go
This PR addresses a flaky issue on this test case where we are creating a deployment right after we have changes in the kubeletconfig and right after that we assert the number of pendingPods and taking the first pod in the list.
The test assumes that there should always be one pod that is pending. And on some of the test cases this fails exactly on that assumption which in some cases the pods list is more than 1. Below is an example of such a test case that was debugged and catched the issue.
```
NAME                       READY STATUS                 RESTARTS AGE
pod/testdp-9c6dc4b7d-4pqwf 0/1   ContainerStatusUnknown 0        31s
pod/testdp-9c6dc4b7d-67zxr 0/1   ContainerStatusUnknown 0        33s
pod/testdp-9c6dc4b7d-6gtxc 0/1   ContainerStatusUnknown 0        28s …
```
=> e2e: fix reboot test case 75354 flaky issue

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manager/manager.yaml
In 055d665ea54a3aeadc24 we added new labels AND we immediately used them to match  components in our deployment. Turns out this breaks upgrades because the old image getting replaced can't possibly have the matching label, for starters. So the proper way is to add labels, let them sit for few releases, then start consuming them. This should work in all the flows, including upgrade.
In this commit we unblock upgrades removing the matching requirement, which will be introduced again later in the future.
=> manifests: labels: don't match using new labels

doc/examples/pod.ctrreschk.yaml, doc/examples/pod.lshwinfo.yaml, doc/examples/pods.testgroup.yaml
let's use releases instead of snapshots, and
the first available release is v0.0.3.
=> doc: examples: use ctrreschk releases

.github/workflows/cibuild.yml, .github/workflows/ciformat.yml, .github/workflows/cilint-custom.yml, .github/workflows/cilint.yml, .github/workflows/civerify-commit.yml, .github/workflows/e2e-local.yaml, .github/workflows/e2e-tools.yml, .github/workflows/e2e.yml, .github/workflows/golangci-lint.yaml, .github/workflows/release-operator.yaml, .github/workflows/release-testsuite.yaml, .github/workflows/support-tools.yml
bump to v4:
https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
=> gh actions: bump more action versions

hack/deploy-mco-crds.sh
OCP changed the manifests location, change our URLs accordingly. Relevant PR: https://github.com/openshift/machine-config-operator/pull/4597
=> deps: deploy: mco: crd: catch up with ocp/mcp/pull/4597

Makefile
Introduce GOTAGS environment variable. This is needed by d/s builds to allow passing tags like `-tags strictfipsruntime`. If the env variable is not set, passing empty string as in `-tags ""` (not empty value as in `-tags `) will run the command as if nothing added with no disturbing.
=> [release-4.15] Makefile: binary-all: support build with -tags

controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go, go.mod, go.sum, internal/api/annotations/annotations.go, internal/objects/objects.go, main.go, pkg/objectstate/rte/rte.go, pkg/objectupdate/rte/rte.go, test/e2e/install/install_test.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/tolerations.go, test/utils/deploy/deploy.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/consts.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/platform/detect/detect.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/manifests.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/rte/rte.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/objectupdate/rte/rte.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/options/options.go, vendor/modules.txt
Starting from 4.18 RTE pods can use a built-in SELinux policy instead
of custom one.
This means that MachineConfig deployment is not mandatory anymore.
However, it is still an option to deploy a custom policy using MachineConfig.
This commit updates the MahcineConfig reconciliation logic.
By default when upgrade is done from 4.1X -> 4.18 the controller
tries to remove the redundant MahcineConfig, unless user state
explicitly that custom policy is needed.
=> CNF-14084: controller: update MachineConfig reconciliation

controllers/numaresourcesoperator_controller.go, pkg/apply/apply.go, pkg/apply/apply_test.go, pkg/objectstate/objectstate.go, pkg/objectstate/objectstate_test.go, pkg/objectstate/rte/rte.go, test/utils/deploy/deploy.go
Push down the logic to manage the deletion of machineconfig into library packages, streamlining the controller.
This PR is meant to do code movement and reorganize the packages, no intended changes in behavior
=> rte: controller: push down machineconfig deletion support into library packages

controllers/kubeletconfig_controller.go, controllers/numaresourcesoperator_controller.go, controllers/numaresourcesscheduler_controller.go, go.mod, pkg/apply/apply.go, pkg/hash/configmap.go
we can just use the `%w` format specifier in `fmt.Errorf` and in the stdlib in general. One less (direct) dependency, no expected changes in behavior, even though some error messages can have been slightly changed.
=> tree: stop using `errors.Wrapf`

api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go, bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml
Back in 4.16.0 we changed defaults and added options to both operator and scheduler objects. Due to the sharing of the config objects between spec and status and due to the fact we still serve v1alpha1, we may end up with fields values in the status which are not declared in the API definition.
The most obvious offender is the enum values, but this actually affects all the values we set explicit defaults for and we expose in the status.
This is what OLM complained about.
To fix this, we align the status definition from v1 to v1alpha1, until we deprecate the v1alpha1 and we stop serving it.
xref: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/dependency-resolution.md
=> api: fix v1alpha1 backward compatibility

api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go, bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml, config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml
Back in 4.16.0 we changed defaults and added options to both operator and scheduler objects. Due to the sharing of the config objects between spec and status and due to the fact we still serve v1alpha1, we may end up with fields values in the status which are not declared in the API definition.
The most obvious offender is the enum values, but this actually affects all the values we set explicit defaults for and we expose in the status.
This is what OLM complained about.
To fix this, we align the status definition from v1 to v1alpha1, until we deprecate the v1alpha1 and we stop serving it.
xref: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/dependency-resolution.md
Manual backport of #1040
=> [release-4.17][manual] api: fix v1alpha1 backward compatibility

hack/run-test-e2e.sh, hack/run-test-install-e2e.sh, test/e2e/install/install_test.go, test/e2e/uninstall/uninstall_test.go
this cleanup spawned from #1029.
the idea is to review and streamline what we do in the e2e lanes.
In the main e2e lane the uninstall test(s) don't make much sense, but they make a lot of sense in the (un)install lane.
So let's move code around.
Overall, running wall clock time should not increase, hopefully actually decrease.
=> e2e: review CI lanes

api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go, api/numaresourcesoperator/v1alpha1/numaresourcesscheduler_types.go, bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml, bundle/manifests/nodetopology.openshift.io_numaresourcesschedulers.yaml, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml, config/crd/bases/nodetopology.openshift.io_numaresourcesschedulers.yaml
The API v1alpha1 was not only deprecated before GA, but never advertised. It's time to deprecate. Later we will stop servingf it in 4.18, and remove in 4.19/20.
This change can and should be backported back to 4.16 or perhaps even below
Key references:
- https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#version-deprecation
- https://book.kubebuilder.io/reference/markers/crd
- https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/dependency-resolution.md#deprecateremove-a-version-of-crd
=> api: deprecate v1alpha1

controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go
Complementary unit tests coverage for #1018 in addition to fixing other deficient behaviors; see the commits messages for more info.
=> Report created RTE daemonsets in operator status and fix status sync issue

api/numaresourcesoperator/v1/namespacedname.go, controllers/numaresourcesoperator_controller.go, test/e2e/serial/tests/configuration.go
Using map to store the daemonset of the targeted MCPs turned out to be a not the best data structure especially when we would like to conserve a consistent order of the elements that aligns with the rest of the slices in the operator status.
The problem with map is that it cannot be guaranteed that the elements will be ordered in the same order they were placed. To fix that, define a new struct of an MCP and its respective created RTE daemonset and replace the map with a slice of this struct which ensures that same data will produce same output every time.
ref: https://groups.google.com/g/golang-nuts/c/YfDxpkI34hY/m/4pktJI2ytusJ
=> controller: use slice instead of map to conserve consistent order

controllers/numaresourcesoperator_controller.go, internal/dangling/dangling.go
Move the dangling object removal code in its own package. This is useful because
- we have now a clear recorded explicit rationale about why we need this code
- this code is in essence a workaround for a questionable design choice, and we now isolate from the regular controller code.
- [future] we enable future reuse (maybe) in the validator.
The main benefit is the added `doc.go`.
this PR salvages the good parts of #1029 
Adding validation support is also a nice idea, but is deferred for later.
=> nrop: cleanup dangling objects removal

api/numaresourcesoperator/v1/numaresourcesoperator_types.go, api/numaresourcesoperator/v1/numaresourcesoperator_types_test.go, internal/api/features/_topics.json, internal/wait/daemonset.go, test/e2e/serial/tests/configuration.go
Now that API of NodeSelector under the NodeGroup of the numareosurcesoperator CR is supported, extend the e2e coverage by adding more tests covering the scenarios when NodeSelector is set/deleted.
=> e2e: add tests for PoolName and NodeGroupStatus

controllers/controllers.go, controllers/numaresourcesoperator_controller.go, controllers/numaresourcesscheduler_controller.go, pkg/status/status.go, pkg/status/status_test.go
Simple and safe cleanup/refactoring preparation to the real upcoming cleanup of how controllers compute the status of their objects.
These changes have some (little, admittedly) value on their own and simplify the main PR (#1032).
=> Prepare for cleaning up status computation

controllers/numaresourcesoperator_controller.go, internal/dangling/dangling.go, pkg/validation/validation.go, test/utils/padder/padder.go, tools/verify-commit/verify-commit.go
Instead of using a slice of error texts and converting it back to error
type or using a slice of errors, use the `errors` go library to `Join`
multiple errors into one.
=> pkg: use `errors.Join` instead of appending to slice

controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go, internal/api/annotations/annotations.go, internal/api/annotations/annotations_test.go, pkg/validation/validation.go, pkg/validation/validation_test.go
Because of historical accident we have a 1:N mapping between NodeGroup and MCPs (MachineConfigPool*s* is a slice!). One of the key design assumptions in NROP is the 1:1 mapping between NodeGroups and MCPs.
Since we want to conserve the backward compatibility we still need to support multiple MCP matches per tree; however, since by design the intention was to have a single matching MCP per node group, make this the default behavior. To re-enable the old behavior permitting multiple pools matches, use the following annotation: `experimental.multiple-pools-per-tree: enabled`
Experiment the effects of the new default for the next 2 releases. If there are no complaints, we shall remove the multiple MCP match logic.
=> OCPBUGS-42523: allow single MCP match per node group by default

test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_unschedulable.go, test/utils/padder/padder.go
The test 47591 is expecting the testing pod to land on the target node that is unpadded. The problem is with the CPU request amount of 2, which is available on the target node but also on the other nodes although they are padded. Thus, the test fails because the pod landed on a node other than the target when TMScope is a container.
Ultimately, the reason is the way the padding function works. It creates a guaranteed pod on each numa zone and each pod with the same allocation resources that were set in the Padder field. This means the whole compute the node will have available resources equivalent to `<# numa cells per node> * p.allocationTarget`.
This is a quick fix for this test flakiness and other possible instances
to reduce the amount of resources forwarded as the allocation target …
=> e2e: fix padder allocationTarget to ensure unfeasible nodes

config/manager/manager.yaml, pkg/numaresourcesscheduler/manifests/yaml/deployment.yaml
For local deployment (not via OLM), we configure the controller manager using yaml files instead of CSV. These yamls use requiredDuringSchedulingIgnoredDuringExecution affinity but on hypershift it was agreed that controller and scheduler be scheduled on the hosted cluster which contains worker nodes only.
related to
https://github.com/openshift-kni/numaresources-operator/pull/1059.
=> manifests: relax node affinity for hypershift

internal/dangling/dangling.go, pkg/validation/validation.go, pkg/validation/validation_test.go
We wanted to have this validation, but we didn't actually add it yet :)
So, if the user supplies a PoolName, it must be non-empty string: the rest of our code expects
it that way, and it's a pretty reasonable restriction anyway.
Add validation to enforce this, and simplify code after the validation.
=> validation: ensure non-empty poolName

test/e2e/must-gather/must_gather_test.go
So far the CI worked with the default node labels which is "worker" and
the NodeGroups of the numaresourcesoperator CR we expected to target the
`worker` mcp. However, this isn't always the case and the test should be
smarter to determine which nodes it should look for their folders in the
collected must-gather.
Adjust the step of building the expected CRs paths to include only nodes
that the operator targets.
=> e2e: mustgather: fix test to verify TAS enabled nodes only

pkg/numaresourcesscheduler/manifests/yaml/configmap.nrt.yaml
Defaults for leader election are questionable at best and likely harmful. So, we should default the leader election to off and enable it only if user sets so, because this will make us to tune all the leader election parameters and set sane values.
=> sched: manifests: disable leader election by default

controllers/kubeletconfig_controller.go, controllers/kubeletconfig_controller_test.go, controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go, internal/objects/objects.go, main.go
Kubelet controller is responsible for extracting the TM configuration from the 
`KubeletConfig` object, craft a `ConfigMap` from it so it could be consumed later on
by the RTE workload.
On HyperShift there's no plain `KubeletConfig` object but a `ConfigMap` that encapsulate it instead,
This PR contains all the changes that were needed for the controller to be able to provide
similar functionality when it's running on HyperShift platform.
=> CNF-11193: controller:hypershift: add support in for Kubelet controller

api/numaresourcesoperator/v1/helper/nodegroup/nodegroup.go, api/numaresourcesoperator/v1/helper/nodegroup/nodegroup_test.go, controllers/numaresourcesoperator_controller.go, pkg/objectstate/rte/rte.go, pkg/validation/validation.go, pkg/validation/validation_test.go
Adapt the possibility of running the operator on Hypershift platform by
replacing MCP context with PoolName where relevant; In addition to extra
NodeGroup validation on hypershift.
=> ctrl: HCP adaptations for NodeGroup validation and RTE

controllers/numaresourcesoperator_controller_test.go, internal/objects/objects.go
The PR includes cleanups and reorganizing the controller tests code by splitting the tests into groups based on what's relevant to be executed on what platforms. 
Please check the commits for more details.
=> Support NROP controller tests on hypershift

Dockerfile.must-gather
Initially, must-gather for NROP was built by grabbing the latest openshift-ose-must-gather image, copying the required binaries for running must gather and override the collection scripts and base that on rhel-minimal.
While this works, there is no need for extra dependencies on images when all we need is the openshift clients to gather the must-gather collection which is available in the CLI image.
=> mustgather: Dockerfile: use ocp CLI base image

controllers/numaresourcesoperator_controller_test.go
add missing test for empty pool name and extra verification for Available condition
=> Add missing controller test for PoolName

controllers/numaresourcesscheduler_controller.go, controllers/numaresourcesscheduler_controller_test.go, pkg/numaresourcesscheduler/consts.go, pkg/status/status.go
Because of a overlook, we used to set the leader election params only if replicas > 1 was requested. This left the key *and default* corner case of replicas=1 with compiled in defaults, which are questionable at best and most likely harmful for our use case.
Make sure to always set sane parameters, obviously taking into account the user desires from the spec (Replicas field).
Add more logs to make troubleshooting easier
manual cherry-pick of #1080 
(cherry picked from commit d83cc70c8bf61722899c228aa019ccfbe27f5a0b)
=> [release-4.17][manual] sched: always set the leader election parameters

internal/wait/kubeletconfig.go, internal/wait/machineconfigpool.go, test/e2e/install/install_test.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/tolerations.go, test/e2e/uninstall/uninstall_test.go, test/utils/deploy/deploy.go, test/utils/deploy/openshift.go
instead of chasing the MCP status transition updated -> updating -> updated, which is fragile and hard to get right both in theory and in practice, let's try a different approach.
When we change a MCP status (e.g. sending a new MachineConfig and/or pausing/unpausing)
1. we record the current MCP resourceversion
2. we ask for our desired state
3. we wait for the MCP desired state to be `updated` again *but with
different resourceversion*
this should allow us to capture the conditions which describe our desired state while waiting for a stable state in a more robust way.
Add minorish cleanups along the way.
=> e2e: more robust wait for MCP updates

controllers/numaresourcesoperator_controller.go, internal/reconcile/step.go, pkg/status/conditioninfo/conditioninfo.go
The API spec requires the condition.Reason to always contain a non-empty CamelCase string. We added the infra to do so but we forgot for the Progressing case.
This change fixes that.
This becomes evident if RTEs fail to start, otherwise it's easy to miss, like it probably happened till now.
=> controller: nrop: always populate reason (progressing)

.snyk, internal/workarounds/interface.go, internal/workarounds/prom.go, internal/workarounds/prom_test.go, test/e2e/install/install_test.go
formalize workarounds we need to add to unblock CI.
We should strive to keep this list short, but a sad
reality is that we need workarounds from time to time.
=>  e2e: test: introduce workarounds

Makefile, hack/run-test-install-e2e.sh, hack/run-test-uninstall-e2e.sh
Invoking make test-install-e2e currently handles both the installation and uninstallation of NROP and its components. We propose separating this into two distinct suites, introducing a dedicated script for the uninstallation process. This separation would be beneficial in scenarios where we need to install and test the operator, upgrade it, and only then proceed with its deletion.
For example, this work will be needed in the [NROP upgrade test lane](https://github.com/openshift/release/pull/58457),
As we wish to:
Install the operator with 4.17 version, run e2e install suite, upgrade to 4.18 and only then uninstall. 
Note, after merging this PR I'll create a PR in the release repo to ensure both calls ([first](https://github.com/openshift/release/blob/master/ci-operator/config/openshift-kni …
=> Separated NROP uninstall from install script

Makefile, pkg/objectupdate/sched/fakeconfs.go, rte/pkg/config/config.go, rte/pkg/config/config_test.go
initial support to run gosec scanning over the source tree
notes:
1. no automated download yet - assume is present. This will be implemented when we make the flow mandatory
2. add the minimal set of fixes found running the `gosec` tool.
=> gosec: initial scaffolding

Dockerfile, Dockerfile.openshift, Dockerfile.openshift.rte, Makefile, main.go, pkg/version/version.go, rte/main.go, tools/buildhelper/buildhelper.go
add static buildinfo rather than determine that at last stage of the build process. This data is expected to be frozen when we build our artifacts, so collect all the infos when we start and add this to our artifacts is actually simpler and safe.
shipping `buildinfo.json` alongside `topics.json` in our test images would also enable better tests introspection, yet to be implemented.
=> add static buildinfo information

.gitignore, Makefile, internal/api/buildinfo/types.go, main.go, pkg/version/version.go, rte/main.go, tools/buildhelper/buildhelper.go
use the buildinfo.json data for `pkg/version` instead of injecting the values at link time.
This simplifies the builds and enables better introspection capabilities.
=> build: buildinfo: move buildinfo struct in internal api

controllers/kubeletconfig_controller.go, main.go
move platform-specific code as much as possible at initialization stage vs peppering the code with `if platform == `.
In addition, remove small repetitions.
=> controllers: kubelet: cleanup platform code

test/e2e/install/install_test.go, test/e2e/must-gather/must_gather_suite_test.go, test/e2e/must-gather/must_gather_test.go, test/utils/deploy/deploy.go, test/utils/deploy/hypershift.go, test/utils/deploy/kubernetes.go, test/utils/deploy/openshift.go
In case we are skipping the setup, make sure to fetch the existing scheduler data, failing loudly if that resource is not actually present.
Along the way, cleanup the deploy API and package to make sure context and timeout are properly passed down the call chain.
=> e2e: must-gather: fix the setup process

test/e2e/install/install_test.go, test/e2e/must-gather/must_gather_suite_test.go, test/e2e/must-gather/must_gather_test.go, test/utils/deploy/deploy.go, test/utils/deploy/hypershift.go, test/utils/deploy/kubernetes.go, test/utils/deploy/openshift.go
In case we are skipping the setup, make sure to fetch the existing scheduler data, failing loudly if that resource is not actually present.
Along the way, cleanup the deploy API and package to make sure context and timeout are properly passed down the call chain.
manual backport of #1120
=> [release-4.18][manual] e2e: must-gather: fix the setup process

internal/api/buildinfo/types.go, internal/buildinfo/buildinfo.go, tools/buildhelper/buildhelper.go
try first to fetch the version from the master location (Makefile) before to deduce from the branch name.
The immediate benefit is we have a much higher chance to always report a version number, because we must have a version number in the master location in the Makefile.
Also: report git raw branch name
=> buildhelper: try harder to get version

README.md, bundle/manifests/numaresources-controller-manager-metrics-service_v1_service.yaml, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/numaresources-operator.clusterserviceversion.yaml, config/prometheus/kustomization.yaml, config/prometheus/monitor.yaml, config/prometheus/rbac.yaml, config/rbac/kustomization.yaml, config/rbac/service.yaml, main.go
This PR encompasses all the required changes to reintegrate NROP metrics with Prometheus.  This implementation uses the metrics server API from the controller-runtime.
The majority of the changes in this PR follow the guidelines outlined in the following guide:
https://rhobs-handbook.netlify.app/products/openshiftmonitoring/collecting_metrics.md/
The difference between this implementation and the guide's is that we use a `bearerTokenFile` for Prometheus authentication instead of tls.crt and tls.key. This approach uses TLS but does not implement mTLS.
A follow-up PR will be issued to ensure we implement this for RTE metrics as well.
Moreover, will issue a PR adding an e2e test to the CI, for this functionality.
To validate that this PR is functioning correctly, please follow these steps: …
=> CNF-10142: Enable NROP metrics to be to scraped securely by Prometheus

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go, main.go, pkg/metrics/manifests/manifests.go, pkg/metrics/manifests/manifests_test.go, pkg/metrics/manifests/monitor/monitor.go, pkg/metrics/manifests/monitor/monitor_test.go, pkg/metrics/manifests/yaml/service.yaml, pkg/objectupdate/rte/rte.go, pkg/objectupdate/rte/rte_test.go
This is a follow-up PR for [Enable NROP metrics to be to scraped securely by Prometheus ](https://github.com/openshift-kni/numaresources-operator/pull/1106).
This PR encompasses and integrates all the needed infrastructure to enable secured communication for scraping metrics by Prometheus, now for **RTE**.
A follow-up PR will be posted for e2e tests later.
To validate that this PR is functioning correctly, please follow these steps:
1. build image of the operator (`make docker-build docker-push`)
2. run: `make deploy` 
3. Attach to one of the prometheus pods `oc exec -it prometheus-k8s-0 -n openshift-monitoring /bin/bash`
4. run:
```
curl -v \
--cacert /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt \
-H "Authorization: Bearer $(cat …
```
=> CNF-11234: Enable RTE metrics to be scraped securely by Prometheus

Makefile, hack/run-test-upgrade-e2e.sh, test/e2e/upgrade/test_suite_upgrade_test.go, test/e2e/upgrade/upgrade_test.go, test/utils/deploy/find.go
Starting in version 4.18, NROP MachineConfigs containing the custom SELinux policy are expected to be removed unless a specific annotation is set in the NUMAResourcesOperator CR to enforce the use of the custom (legacy) SELinux policy. To ensure this behavior, we added a test that verifies MachineConfigs are removed when the annotation is absent in the CR.
=> e2e: introduce upgrade suite

controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go, main.go, pkg/objectstate/rte/rte.go
instead of having very custom processing of RTE metrics manifests, generalize the current RTE manifests handling and merge the metrics manifests in this flow. Benefits are more common code and less special cases. No expected changes in the operator behavior.
=> rte: metrics: merge manifests into existing manifests handling

controllers/numaresourcesoperator_controller.go, pkg/objectstate/api/api.go, pkg/objectstate/cfg/cfg.go, pkg/objectstate/rte/machineconfigpool.go, pkg/objectstate/rte/nodegroup.go, pkg/objectstate/rte/rte.go
isolate per-platform specific code in their own types and source code, to reduce the clutter without intentional changes of behavior.
The idea is to gradually move towards full isolation and containment of the platform-specific code, and this change is a step in that direction.
Actually, we dopn't really care about the platform but rather about how we find the nodes, but the method (poolName vs machineconfigpool) is still tied to the platform, hence the ambiguity.
In the long run we want to support only the newer pool approach introduced with HCP.
=> objstate: rte: isolate platform-specific code

README.md, bundle/manifests/numaresources-controller-manager-metrics-service_v1_service.yaml, bundle/manifests/numaresources-manager-role_rbac.authorization.k8s.io_v1_role.yaml, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manager/manager.yaml, config/manifests/bases/numaresources-operator.clusterserviceversion.yaml, config/prometheus/kustomization.yaml, config/prometheus/monitor.yaml, config/prometheus/rbac.yaml, config/rbac/kustomization.yaml, config/rbac/role.yaml, config/rbac/role_binding.yaml, config/rbac/service.yaml, controllers/numaresourcesoperator_controller.go, main.go
This PR is a combined backport of #1106 and #1133.
This PR encompasses all the required changes to reintegrate NROP metrics with Prometheus.  This implementation uses the metrics server API from the controller-runtime.
The majority of the changes in this PR follow the guidelines outlined in the following guide:
https://rhobs-handbook.netlify.app/products/openshiftmonitoring/collecting_metrics.md/
The difference between this implementation and the guide's is that we use a `bearerTokenFile` for Prometheus authentication instead of tls.crt and tls.key. This approach uses TLS but does not implement mTLS.
A follow-up PR will be issued to ensure we implement this for RTE metrics as well.
To validate that this PR is functioning correctly, please follow these steps:
1. build image of the operator …
=> [release-4.18] Enable NROP metrics to be to scraped securely by Prometheus

controllers/numaresourcesoperator_controller.go
We used to get the current cluster state both when attempting to sync the machine config state in the OpenShift flow, and when attempting to sync the RTE daemonsets in both flows.
Due to the way `rtestate.FromClient` works, we end up reading the full cluster state twice in the openshift flow, which is unnecessary and wasteful.
The fix is to get the cluster state once in the higher level function and pass the state in the specific reconcile step functions. The machine config and daemonset functions touch not overlapping objects (bar bugs) so sharing the state between them is expected to be fine.
In other words, we happen to fetch the state twice most likely because of oversight, not because a deliberate decision about data sharing/unsharing (which, should that be the case, would need some …
=> [release-4.18] nrop: controller: get rtestate from cluster just once

api/numaresourcesoperator/v1alpha1/numaresourcesoperator_types.go, api/numaresourcesoperator/v1alpha1/numaresourcesscheduler_types.go, bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml, bundle/manifests/nodetopology.openshift.io_numaresourcesschedulers.yaml, config/crd/bases/nodetopology.openshift.io_numaresourcesoperators.yaml, config/crd/bases/nodetopology.openshift.io_numaresourcesschedulers.yaml
use kube mechanism to make it really loud and obvious this API version is deprecated
xref: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#version-deprecation
=> [release-4.17][manual]  api: deprecate v1alpha1

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/numaresourcesoperator_controller.go
This PR removes the Service-related RBAC permissions previously granted in the ClusterRole.
This should have been removed as part of the #1140 backport, but it seems to have been unintentionally left behind, likely due to rebase issues.
@ffromani @Tal-or
=> Remove cluster role service RBAC permission leftover

test/e2e/serial/tests/metrics.go
This is a follow-up PR for #1106 and #1107, adding e2e tests to test their functionality.
The tests verify that secured metrics fetching can be established, for both the manager pod and rte workers.
=> CNF-14833: E2E: metrics exposed securely 

controllers/numaresourcesoperator_controller.go, pkg/objectstate/api/api.go, pkg/objectstate/cfg/cfg.go, pkg/objectstate/rte/machineconfigpool.go, pkg/objectstate/rte/nodegroup.go, pkg/objectstate/rte/rte.go
isolate per-platform specific code in their own types and source code, to reduce the clutter without intentional changes of behavior.
The idea is to gradually move towards full isolation and containment of the platform-specific code, and this change is a step in that direction.
Actually, we dopn't really care about the platform but rather about how we find the nodes, but the method (poolName vs machineconfigpool) is still tied to the platform, hence the ambiguity.
In the long run we want to support only the newer pool approach introduced with HCP.
manual backport of #1114
=> [release-4.18][manual] objstate: rte: isolate platform-specific code

internal/kloglevel/kloglevel.go, internal/kloglevel/kloglevel_test.go, pkg/objectnames/nodes_test.go
=> add missing unit tests

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/numaresourcesoperator_controller.go, go.mod, go.sum, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/assets.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.17.cil, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.18.cil, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/platform/detect/detect.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/deployer/platform/platform.go, vendor/modules.txt
=> [release-4.17] deps: bump deployer dep

.konflux/Dockerfile.must-gather
This Dockerfile will be used by konflux.
=> konflux: add a dockerfile to must gather

go.mod, go.sum, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/images/consts.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/schedparams.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/objectupdate/sched/render.go, vendor/modules.txt
=> [release-4.16] deps: bump deployer dep

api/numaresourcesoperator/v1/helper/namespacedname/namespacedname.go, api/numaresourcesoperator/v1/helper/namespacedname/namespacedname_test.go, api/numaresourcesoperator/v1/namespacedname.go, controllers/numaresourcesoperator_controller.go, internal/wait/job.go, pkg/numaresourcesscheduler/objectstate/sched/sched.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/scheduler_cache_stall.go
Minor adjustments and cleanups that wrap helper functions for
NamespacedName under api/v1/helper/namespacedname.
Signed-off-by: Shereen Haj <shajmakh@redhat.com>
=> add namespacedname helper pkg

.github/workflows/e2e-tools.yaml
The E2E_NAMESPACE_NAME environment variable is used but never defined.
That would lead to empty value which causes to unexpected behavior.
=> ghaction: define E2E_NAMESPACE_NAME env

api/v1/helper/nodegroup/nodegroup.go, api/v1/helper/nodegroup/nodegroup_test.go, api/v1/numaresourcesoperator_types.go, api/v1/numaresourcesoperator_types_test.go, pkg/validation/validation.go
Instead of pointers display readable string.
```
found multiple pools matches for node group 0xc00467dca0 but expected one. Pools found [0xc00129aa08 0xc00129ac78]
```
To:
```
found multiple pools matches for node group &{&LabelSelector{MatchLabels:map[string]string{test: common,},MatchExpressions:[]LabelSelectorRequirement{},} <nil> <nil> map[]} but expected one. Pools found [test1 test2]
```
=> validation: fix error string

pkg/objectstate/cfg/cfg_test.go
Add another set of tests to cover pkg/objectstate/cfg package.
=> pkg: add unit tests for machine config state

.golangci.yml, internal/controller/numaresourcesoperator_controller_test.go, internal/controller/numaresourcesscheduler_controller_test.go, test/e2e/sched/sched_test.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/metrics.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/scheduler_cache.go, test/e2e/serial/tests/scheduler_cache_stall.go, test/e2e/serial/tests/tolerations.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_no_nrt.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/tools/nrovalidate_test.go, test/e2e/upgrade/upgrade_test.go, test/internal/deploy/hypershift.go
enable the ginkgo linter and address the first batch of complaints.
=> linter: enable checks for ginkgo and gomega

api/v1/numaresourcesoperator_types.go, api/v1/numaresourcesoperator_types_test.go, pkg/validation/validation.go
Problems with the current `NodeGroup.ToString()` method:
1. string representation of annotations, being them maps, is not stable, and we had no test coverage
2. the string representation can be very long, and in some places (e.g. conditions) we need a much more concise representation.
Fix both issues:
1. make representation of annotations stable
2. shorten a tiny bit `ToString()` but most notably add a concise `GetName()` method; use it on validation.
=> api: helper: fix NodeGroup Name

.konflux/Dockerfile.must-gather
This PR updates the Konflux Dockerfile with the following changes:
* Removed a redundant cpass label.
* Added a required label for Konflux.
=> Update konflux dockerfile

pkg/objectstate/merge/merge.go, pkg/objectstate/merge/merge_test.go
Add missing unit tests for the merge package.
=> pkg: add unit tests for merge

internal/api/features/_topics.json, test/e2e/serial/tests/metrics.go
exposing metrics is supported on 4.18 and forward, label the relevant specs that cover this topic and add it to the list of actiuve topics for this branch.
=> internal: include `metrics` in active topics

go.mod, go.sum, vendor/github.com/golang/glog/glog.go, vendor/github.com/golang/glog/glog_file.go, vendor/github.com/golang/glog/glog_file_nonwindows.go, vendor/github.com/golang/glog/glog_file_windows.go, vendor/golang.org/x/oauth2/LICENSE, vendor/golang.org/x/oauth2/README.md, vendor/golang.org/x/oauth2/oauth2.go, vendor/golang.org/x/oauth2/pkce.go, vendor/golang.org/x/oauth2/token.go, vendor/modules.txt
bump deps to proactive remove possible vulnerabilities. Note in both cases our production code is NOT AFFECTED ( we either don't even include the code in our vendor tree or not use in production code, but in test code).
Still, bump deps to be proactive and make the risk exactly zero
glog   -> Vulnerability GO-2025-3372
oauth2 -> Vulnerability GO-2025-3488
=> [release-4.18] deps bump: glog, x/oauth2

go.mod, go.sum, vendor/github.com/golang/glog/glog.go, vendor/github.com/golang/glog/glog_file.go, vendor/github.com/golang/glog/glog_file_linux.go, vendor/github.com/golang/glog/glog_file_nonwindows.go, vendor/github.com/golang/glog/glog_file_other.go, vendor/github.com/golang/glog/glog_file_posix.go, vendor/github.com/golang/glog/glog_file_windows.go, vendor/github.com/golang/glog/glog_flags.go, vendor/github.com/golang/glog/internal/logsink/logsink.go, vendor/modules.txt
bump glog dep to proactive remove possible vulnerabilities. Note our production code is NOT AFFECTED, because we do not use in production code, but only in test code.
Still, bump deps to be proactive and make the risk exactly zero.
glog   -> Vulnerability GO-2025-3372
=> [release-4.15] deps bump: glog

test/e2e/install/install_test.go, test/e2e/serial/README.md, test/e2e/serial/config/config.go, test/e2e/serial/config/envs.go, test/e2e/serial/e2e_serial_test.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/tolerations.go, test/internal/deploy/deploy.go, test/internal/deploy/openshift.go
another grab bag of internal (dev UX) and external (user UX) improvements:
- make sure to init logger, and let it be configured using env vars
- dump environs at startup
- simplify a bit the waitForMcpUpdate API (no change in behavior)
=> e2e: serial: minor usability improvements

internal/devices/devices.go, internal/noderesourcetopology/equality.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/tolerations.go, test/internal/deploy/deploy.go, test/internal/fixture/devices.go
please see commits for more details.
=> serial tests fixes

internal/api/annotations/annotations.go, internal/api/annotations/annotations_test.go, internal/api/features/_topics.json, internal/controller/numaresourcesoperator_controller.go, internal/controller/numaresourcesoperator_controller_test.go
Add custom annotation to stop reconciling the NRT API.
This annotation is semi-public and will be used strictly on a case-by-case way if there are multiple operators which
claim ownership of the NRT CRD.
With this annotation, NROP goes above and beyond and trusts blindly whatever NRT CRD is found in the cluster instead of owning the API.
Stop owning the NRT CRD greatly weakens the stability of the NUMA-aware scheduling and it is dangerous and definitely NOT recommended. But can be necessary in circumstances on which other operator claim ownership of the CRD, and we can't reconcile the differences.
=> api: allow to skip reconciliation of NRT CRD 

go.mod
we are a top-level package, so we can require a more recent version wrt our deps, until the go 1 backward promise is respected. This will help with next dep bumps.
We build already with golang 1.23 anyway
=> go: bump package to 1.23

test/e2e/install/install_test.go, test/e2e/label/label.go, test/e2e/sched/install/install_test.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/non_regression_fundamentals.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/resource_hostlevel.go, test/e2e/serial/tests/scheduler_cache.go, test/e2e/serial/tests/scheduler_cache_stall.go, test/e2e/serial/tests/scheduler_removal.go, test/e2e/serial/tests/tolerations.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_no_nrt.go, test/e2e/serial/tests/workload_placement_nodelabel.go, test/e2e/serial/tests/workload_placement_resources.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go
The label package contains a list of labels that can be used in
the e2e and serial tests to indicate and point certain behavior or characteristics
of the various tests.
Those can be filtered/focused by ginkgo before the test runs.
Example:
`ginkgo --label-filter="!slow"` means avoid any specs labelled `slow`
The types defined in the package are type aliases and not new defined
types. This is done in order to avoid casting every time the labels are
being used.
This package allow greater readability, prevent typos (what can easily
happen while using plain-text) and
a common place to hold and documents every label that is being
used in the tests.
=> e2e: classifying tests using labels

test/e2e/serial/tests/version.go
add a bogus (because it cannot fail) test to report both e2e serial suite version and cluster version.
=> e2e: serial: abuse ginkgo to report involved version

test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/scheduler_cache.go, test/e2e/serial/tests/scheduler_cache_stall.go, test/e2e/serial/tests/tolerations.go
The suite is running on hypershift and some tests that involves MCP
checks fails because MCO is not supported on HCP. Mark these tests with
the `openshift` label so they can be skipped when running the suite on
hypershift for now.
Note that part of these tests with slight adjustments can run on both
platforms; adapting this should be handled in later PRs.
=> serial: add openshift labels

test/e2e/serial/tests/configuration.go
The previous version was fragile and maintained several times already.
This fact means that the test should be rewritten and once the known bugs
are fixed, new tests will be added to cover the e2e full scenario.
The test goal is to verify that adjustments to NROP CR are done as
expected and reflected in the RTE daemonsets. Previously, this was done
via creating a new MCP for the test and associating to it one of the
worker nodes that were part of the initial NROP node groups. This was
causing a reboot when running on a cluster that is:
a. < 4.18 or
b. >= 4.18 and has the custom RTE selinux policy enabled
In the new version of the test, we keep checking the same functionality
while completely avoiding reboot. That is acheived by creating the new MCP,
keeping it empty (no nodes are …
=> serial: rewrite test 47674

test/e2e/serial/tests/workload_placement_tmpol.go
This PR addresses a correction for a typo involving the incorrect placement of a comma within a Ginkgo label.
=> serial: fix comma typo under Label

pkg/objectstate/rte/machineconfigpool.go, pkg/objectstate/rte/rte.go, test/e2e/uninstall/uninstall_test.go
In order to facilitate the transition to the MCO APIs after the merge in `openshift/api`, reduce where it is cheap our usage of the MCO types. Less dep surface, less porting effort.
No intended changes in behavior.
=> deps: reduce MCO dependencies

test/e2e/serial/tests/configuration.go
This test is specific to OpenShift, as it depends on MCP creation and updates. We need a similar test case for HCP, therefore, this one is categorized with adding label OpenShift.
=> e2e: serial: Add Openshift label to MCP specific test

test/internal/deploy/find.go
The `Status.NodeGroup` API is supported starting 4.18. Code that uses this function and anticipated to run on < 4.18 will fail because there will be no node groups reported in the status. Use `Status.Daemonset` instead for backward compatibility.
=> internal: make function backward compatible

test/e2e/serial/tests/scheduler_removal.go, test/internal/nrosched/nrosched.go
The test can be flaky sometimes when the new deployment that is created post the scheduler deletion succeeds to be scheduled instead of pending. Add a wait period after the scheduler deletion to ensure it got deleted before creating new pods and moving forward with the test.
=> e2e:serial: add wait on deployment deletion

tools/verify-commit/verify-commit.go
Konflux bot started filing chore PRs and they are failing on commits verification. Failures:
```
eb72d24a Red Hat Konflux update numaresources-must-gather-4-20 Signed-off-by: red-hat-konflux <konflux@no-reply.konflux-ci.dev>
---
CHECK: eb72d24a
start verifying commits from stdin
commit: {"commit":"eb72d24afef55d47c314ff7d4e48e11b6895411c","author":"red-hat-konflux","authorEmail":"\u003ckonflux@no-reply.konflux-ci.dev\u003e","authorEmailLocal":"\u003ckonflux\u003e","dcoSignTag":"","dcoCoauthorTag":""}
read: 1 commits
done verifying commits from stdin
error: invalid commit: DCO signoff trailer missing
or
start verifying commits from stdin
error: invalid commit: DCO signoff malformed: "Signed-off-by: red-hat-konflux <126015336+red-hat-konflux[bot]@users.noreply.github.com>" does not contain …
```
=> tools: pass on konflux bot commit

api/v1/helper/nodegroup/nodegroup.go, api/v1/helper/nodegroup/nodegroup_test.go
The CloneList function previously created a slice with length 0 and only set capacity, which led to a runtime panic when accessing ret[idx].
replaces: #1274
=> api: e2e: serial: initialize slice with correct length in CloneList

rte/main.go
controller-runtime log package has an interesting deferring log mechanism which require initialization within a timeout. Otherwise a scary stacktrace is emitted and no logs are shown.
Make sure to initialize this log rerouting to the main klog logger.
=> CNF-18077: rte: log: initialize controller-runtime

api/v1/numaresourcesscheduler_defaults.go, api/v1/numaresourcesscheduler_defaults_test.go, api/v1/numaresourcesscheduler_normalize_test.go, cmd/main.go, internal/controller/numaresourcesscheduler_controller.go, internal/controller/numaresourcesscheduler_controller_test.go, test/e2e/sched/install/install_test.go
Changing the topology-aware scheduler behavior to have HA by default.
Starting from OCP 4.20 the scheduler HA is enabled by default (previously it was not)
and replicas number is equal to the number of control-plane nodes.
In case the user wants to disable HA (retaining the old behavior)
he needs to explicitly set `spec.Replicas` to 1.
=> CNF-17778: CNF-17779: schedulercontroller: High availability by default

renovate.json
- Set packageRules to ignore all chore(deps) updates for minor versions. We currenly want control over the minor versions of base images and go versions and we also do not want to use the latest minor version of a package in all branches
- Set auto lgtm and approve for tekton file digest updates
=> Konflux: update renovate configuration

.konflux/must-gather/must-gather.konflux.Dockerfile, .konflux/must-gather/rpms.in.yaml, .konflux/must-gather/rpms.lock.yaml, .tekton/numaresources-must-gather-4-16-pull-request.yaml, .tekton/numaresources-must-gather-4-16-push.yaml
* Add Dockerfile for NROP must gather for konflux builds.
* Add initial tekton files for build pipelines.  
* Add rpm locking for must gather container (to be enabled with hermetic builds)
* Add cel expressions to run the pipeline only on Tekton or must-gather image content changes.
=> [release-4.16]: Onboard numaresources must-gather to konflux

.konflux/must-gather/must-gather.konflux.Dockerfile, .konflux/must-gather/rpms.in.yaml, .konflux/must-gather/rpms.lock.yaml, .tekton/numaresources-must-gather-4-15-pull-request.yaml, .tekton/numaresources-must-gather-4-15-push.yaml
* Add Dockerfile for NROP must gather for konflux builds.
* Add initial tekton files for build pipelines.  
* Add rpm locking for must gather container (to be enabled with hermetic builds)
* Add cel expressions to run the pipeline only on Tekton or must-gather image content changes.
=> [release-4.15]: Onboard numaresources must-gather to konflux

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, cmd/main.go, config/manager/manager.yaml
streamline command line parameters handling.
- remove deprecated option, as the command line parameters are not part of stable API promise. So we can just remove deprecated options
- switch the default for options we always use.
=> operator: fix and clean commandline

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/rbac/role.yaml, internal/controller/numaresourcesscheduler_controller.go
recent changes made the scheduler controller watch nodes to recompute the replica count.
Fix RBAC permissions.
=> rbac: controller: sched: add permission to watch nodes

.konflux/catalog/bundle.builds.in.yaml, .konflux/catalog/catalog-template.in.yaml
Configure catalog to include next z stream build (4.19.1) as a Konflux quay image
=> [release 4.19] konflux: z stream update 4.19.1

.konflux/catalog/bundle.builds.in.yaml, .konflux/catalog/catalog-template.in.yaml
replace url to image digest instead of manifest list digest
=> [release 4.18] konflux: set 4.18 bundle to image digest

Makefile, hack/sort-imports.py
add a helper script which reads the sort ordering expectation from our .golangci.yml (source of truth) and automatically constructs the recommended command line to run to conform.
Depends on python3 and gci: https://github.com/daixiang0/gci
=> hack: add a script to reformat the imports

.konflux/must-gather/rpms.lock.yaml
This commit includes the tar source rpm in the lockfile which was missed. This is needed for nrop must-gather to
function correctly.
=> [release-4.19] konflux: must-gather: restore `tar` rpm 

.konflux/must-gather/redhat.repo, .konflux/must-gather/rpms.lock.yaml
A follow-up cleanup of https://github.com/openshift-kni/numaresources-operator/pull/1546, please see commits for details.
=> [release-4.17] cleanup: konflux: mustgather: remove redundant lines and restore `tar`

go.mod, go.sum, vendor/golang.org/x/oauth2/pkce.go, vendor/modules.txt
`go mod tidy` automatically updates the Go directives to point to the minimum golang version that is required by the dependencies. Ideally this should run on every update that involves `go.mod` updates.
oauth2 v0.27.0 requires at least Go v1.23 hence runnig `go mod tidy` would automatically bump Go directive and toolchain to the minimum Go version needed, v1.23. This conflicts with openshift conventions of dependencies for related containers.
The bump to v0.27 was originally done in
https://github.com/openshift-kni/numaresources-operator/pull/1211
but didn't have the bump of Go directive.
Since we want to proceed with 1.22 for 4.18 we want to downgrade oauth2 version to v0.26 at most while preserving goal of
https://github.com/openshift-kni/numaresources-operator/commit/a553b30b580b6b789b3 …
=> deps: downgrade oauth2 from 0.27 -> 0.26

test/e2e/serial/tests/tolerations.go
Changing the depricated reboot_required labels to use the new reboot label.
=> e2e: serial: change deprecated reboot labels to new reboot label

hack/verify-commits.sh
We still need to track down sporadic and apparently random failures. Can be API throttling?
=> hack: verify commit: more debug logs

test/e2e/serial/tests/network_policy.go
We should initialize the outer context in the `BeforeAll()` but it was masked instead, which means a `nil` context was passed to all the functions.
=> NO-JIRA:e2e:networkpolicy: do not mask context

internal/api/annotations/annotations.go
we should document when our magic annotations are introduced and when and if we plan to remove them; this is especially important for pseudo-feature gates.
=> internal: api: annotations: document lifecycle

internal/api/annotations/annotations.go, internal/api/annotations/annotations_test.go, internal/controller/numaresourcesscheduler_controller.go, internal/controller/numaresourcesscheduler_controller_test.go, pkg/numaresourcesscheduler/manifests/yaml/deployment.yaml, pkg/objectupdate/sched/sched.go, pkg/objectupdate/sched/sched_test.go
update the secondary scheduler resource requests according to scalability requirements.
In a nutshell, this means removing the resource caps, which was set initially and never challenged till now.
=> review scheduler resources requests

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/rbac/role.yaml, internal/controller/numaresourcesoperator_controller.go, internal/controller/numaresourcesscheduler_controller.go, internal/controller/numaresourcesscheduler_controller_test.go, pkg/objectstate/rte/rte.go
Add support for scheduler high availability when running on HyperShift platform. On HyperShift, scheduler replicas are deployed on worker nodes, as opposed to standard OpenShift where replicas run on control-plane nodes.
Implement intelligent replica management with the following logic:
- Use worker nodes for replica count calculation on HyperShift
- Use control-plane nodes for replica count calculation on OpenShift
- Prefer odd-sized replica counts (1 or 3) to avoid split-brain scenarios
- Cap maximum replicas at 3 to prevent resource overconsumption
- Return error when no target nodes are found for the platform
The automatic replica detection can be overridden by explicitly setting the replicas field in the NUMAResourcesScheduler custom resource.
Includes comprehensive unit tests …
=> CNF-17780:numaresourcesscheduler: support HA for HyperShift platform

test/e2e/serial/tests/scheduler_removal.go, test/internal/nrosched/nrosched.go
The function either succeeds and returns a pointer to the found
NUMA-aware scheduler, or the calling test fails. The function returned
value was asserted in some places as an attempt to ensure the functionality passed,
while that is inaccurate considering that the function already verifies its
self by being marked as ginkgo helper.
Clarify the intent of the function and remove redundant assertions.
=> test: nrosched: clarify docstring for CheckNROSchedulerAvailable()

internal/api/annotations/annotations.go, internal/api/annotations/annotations_test.go, internal/controller/numaresourcesscheduler_controller.go, internal/controller/numaresourcesscheduler_controller_test.go, pkg/numaresourcesscheduler/manifests/yaml/deployment.yaml, pkg/objectupdate/sched/sched.go, pkg/objectupdate/sched/sched_test.go
update the secondary scheduler resource requests according to scalability requirements.
In a nutshell, this means removing the resource caps, which was set initially and never challenged till now.
manual backport of #1689
=> [release-4.19][manual] review scheduler resources requests

internal/controller/numaresourcesoperator_controller.go, internal/controller/numaresourcesscheduler_controller.go, pkg/status/status.go, pkg/status/status_test.go, test/e2e/serial/tests/configuration.go
This PR fixes status reporting issues and is a preliminary for adding scheduler informer reporting under status conditions.
please see commits for details.
=> scheduler controller: resource status cleanup 

hack/run-test-compact-e2e.sh, test/internal/objects/objects.go
test: introduce E2E_NODE_ROLE
For compact cluster configuration, we need to differentiate between
the MCP pools on which to do the installation. For compact cluster we
would be interested to use the `master` pool because worker pool is
empty (machine count is 0).
=> test: introduce E2E_NODE_ROLE

internal/controller/numaresourcesoperator_controller.go, internal/controller/numaresourcesoperator_controller_test.go, pkg/objectupdate/rte/rte.go, pkg/objectupdate/rte/rte_test.go
controller: add PodAntiAffinity to RTE DS
We want to avoid having more than 1 RTE pod deployed on node when there
are overlapping nodeGroups specified in the NRO CR.
We cannot prevent the misconfiguration of the cluster node labels with
respect to MCO (e.i a node may match to more than one MCP's node
selector field) but we can mitigate having duplicated RTEs on the same
node.As a result, the order of RTE pods being created following
configuration modifications, like nodes labels, MCP node selectors or any
other adjustments that may relate to the specified nodeGroup(s), will
keep the pod pending starting the second one.
Important note: this change doesn't prevent running the RTE pod on nodes that do not
belong to the specified MCP but still match their nodeSelectors. The
only way to manage …
=> controller: add `PodAntiAffinity` to RTE DS

controllers/numaresourcesscheduler_controller.go, controllers/numaresourcesscheduler_controller_test.go, internal/api/annotations/annotations.go, internal/api/annotations/annotations_test.go, pkg/numaresourcesscheduler/manifests/yaml/deployment.yaml, pkg/objectupdate/sched/sched.go, pkg/objectupdate/sched/sched_test.go
update the secondary scheduler resource requests according to scalability requirements.
In a nutshell, this means removing the resource caps, which was set initially and never challenged till now.
manual backport of https://github.com/openshift-kni/numaresources-operator/pull/1695
=> [release-4.18][manual] review scheduler resources requests

internal/controller/numaresourcesscheduler_controller.go, internal/controller/numaresourcesscheduler_controller_test.go, pkg/status/status.go, pkg/status/status_test.go
We want to be able to see the informer mode of the scheduler as a preparation step for having the informer default change according to the kubelet version.
This commit enables reflecting the informer value (default or configured) as part of the status conditions which is less direct than reporting it in spec and is valid.
=> controller: sched: report DedicatedInformerActive behavior

test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/tolerations.go
This PR assigns unique IDs to previously un-tagged tests in the serial suite.
=> e2e: Serial: Add test case ids to the leftover tests

cmd/main.go, internal/controller/numaresourcesscheduler_controller.go, internal/controller/numaresourcesscheduler_controller_test.go, internal/platforminfo/platforminfo.go, internal/platforminfo/platforminfo_test.go, internal/platforminfo/supportversion.go, internal/platforminfo/supportversion_test.go
The fix has landed in OCP nightly 4.20, make sure this is reflected to consume the new default of schedulerInformer in case it is not set by the user.
Previously the version parsing relied on the assumption that the platform version is of type stable (e.i 4.20.1, 4.20.2 ..) but this is in correct because the cluster may be deployed with different types of builds and each requires its own processing logic, which must know the first supported build for each type. Ensure that the different types are recognized and processed as required.
Design notes:
moved platforminfo in a separate package, still internal. Previously, it was a private controller helper. Moved into a new packge mostly because didn't want to pollute controllers with version check.
Added a Properties sub-struct vs add straight …
=> OCPBUGS-60848: controller: sched: detect and use cluster properties

test/e2e/serial/tests/configuration.go
The defer function incorrectly restores ```topologyManagerPolicy``` to ```"none"``` instead of ```initialTopologyManagerPolicy```
=> e2e: fix: changing wrong topologyManagerPolicy in defer func

.devcontainer/devcontainer.json, .github/workflows/ci.yaml, .github/workflows/e2e-local.yaml, .github/workflows/e2e-tools.yaml, .github/workflows/e2e.yaml, .github/workflows/govulncheck.yaml, .github/workflows/release-operator.yaml, .github/workflows/support-tools.yaml, .konflux/Dockerfile.catalog, .konflux/operator/konflux.Dockerfile, Dockerfile, Dockerfile.pause, Dockerfile.tests, Dockerfile.tools, test/deviceplugin/cmd/numacell/Dockerfile
Follow Openshift and bump to go v1.24.
Note: the below AI-Attribution tag was genereted using the https://aiattribution.github.io/create-attribution to interpret it please paste its value in
https://aiattribution.github.io/interpret-attribution.
Assisted-by: Cursor v1.2.2
AI-Attribution: AIA PAI Ce Hin R Cursor v1.2.2 model:gpt-5 v1.0
=> AA: go: bump to 1.24

api/v1/numaresourcesscheduler_types.go, cmd/main.go, internal/controller/numaresourcesscheduler_controller.go, internal/controller/numaresourcesscheduler_controller_test.go, internal/platforminfo/platforminfo.go, internal/platforminfo/platforminfo_test.go, internal/platforminfo/supportversion.go, internal/platforminfo/supportversion_test.go, pkg/status/status.go, pkg/status/status_test.go
https://github.com/openshift/kubernetes/pull/2391 has landed in
openshift, which means that the behavior described is enabled by default and we want
the scheduler to adapt to this behavior by default iff the user didn't
explicitly set the informer mode in the CR.
Until now, the scheduler works in a dedicated informer mode which is meant to take into
account the pods in terminal state (such as pods that ran and completed)
in the PFP computation to ensure it matches the PFP computed by the RTE
and reported in NRT.
The intended behavior which the new kubelet behavior is about ignoring
such pods and accounting only for active pods, so if this behavior is
enabled in the RTE-NRT, while kept the default dedicated in the
scheduler there will be misalignment in the computed vs the expected PFP …
=> OCPBUGS-61355: [release-4.19] controller: sched: conditionally enable Shared informer by default 

api/numaresourcesoperator/v1/numaresourcesscheduler_types.go, controllers/numaresourcesscheduler_controller.go, controllers/numaresourcesscheduler_controller_test.go, internal/platforminfo/platforminfo.go, internal/platforminfo/platforminfo_test.go, internal/platforminfo/supportversion.go, internal/platforminfo/supportversion_test.go, main.go, pkg/status/status.go, pkg/status/status_test.go, test/e2e/sched/install/install_test.go
manual cherry-pick of https://github.com/openshift-kni/numaresources-operator/pull/1932
=> OCPBUGS-61409: [release-4.18]: controller: sched: conditionally enable Shared informer by default

internal/controller/numaresourcesscheduler_controller.go, test/e2e/sched/install/install_test.go
The problem with the current implementation is that if the status condition A is updated to `True` (like Progressing or Degraded condition) it will never be updated again if the reconcilation interation is not updating that exact condition. This creates accumulated status conditions as follows:
```
conditions:
- lastTransitionTime: "2025-09-09T10:24:02Z"
message: ""
reason: AsExpected
status: "True"
type: Available
- lastTransitionTime: "2025-09-09T10:24:02Z"
message: ""
reason: Upgradeable
status: "True"
type: Upgradeable
- lastTransitionTime: "2025-09-09T10:23:47Z"
message: ""
reason: AsExpected
status: "True"
type: Progressing
- lastTransitionTime: "2025-09-09T10:23:47Z"
message: 'could not apply (apps/v1, Kind=Deployment) openshift-numaresources/secondary-scheduler:
could not update …
```
=> [release-4.19] sched: status: reset the status conditions to defaults

test/e2e/serial/tests/non_regression_fundamentals.go, test/e2e/serial/tests/scheduler_cache_stall.go
add more test coverage for scheduler stalls, using targeted naked (= not managed by a controller) pods.
the key trigger for scheduler stall turned out to be guaranteed pods with `restartPolicy` != `Always`
=> CNF-18275: CNF-18276: e2e: serial: more cache stall tests

.konflux/must-gather/must-gather.konflux.Dockerfile
For https://issues.redhat.com/browse/KONFLUX-6210, clair needs access to a name and cpe label that it can use to look up the image in VEX statements.
See also release-engineering/rhtap-ec-policy#149
Signed-off-by: Ralph Bean <rbean@redhat.com>
Assisted-by: Gemini
=> chore(KONFLUX-6210): fix and set name and cpe label for numaresources-must-gather-4-14

.konflux/bundle/overlay/pin_images.in.yaml
Replace image pinning to manifest list digest instead of single image digest
=> [release-4.19] Konflux: pin operator image to manifest list

.konflux/bundle/overlay/pin_images.in.yaml
Replace image pinning to manifest list digest instead of single image digest
=> [release-4.18] Konflux: pin operator image to manifest list

.konflux/bundle/overlay/pin_images.in.yaml
Replace image pinning to manifest list digest instead of single image digest
=> [release-4.17] Konflux: pin operator image to manifest list
