openshift-kni/numaresources-operator

.github/workflows/release.yml
=> gh actions: release: fix outdated repo ref

Makefile
=> Add deps-update make target

controllers/numaresourcesoperator_controller.go, pkg/objectstate/rte/rte.go
minor cleanups emerged during the review of #13
=> Nodegroups minor cleanups

Makefile
=> Makefile: fix typo in target

Makefile
Generalize the container-related commands, allowing to
use podman and not necessarily docker.
To replace the container engine just do
`export CONTAINER_ENGINE=podman`
before to run `make ...`
=> Makefile: generalize container engine

doc/examples/nrop.yaml
=> doc: add example CR

bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml, bundle/manifests/numaresources-operator.clusterserviceversion.yaml
update to incorporate the latest changes
=> manifests: bundle: refresh manifests

main.go
Since we decided to use `klog` in our own code,
let's complete the switch removing all the remaining
instances of setupLog in `main.go`.
=> klog: switch in main.go

bundle/manifests/nodetopology.openshift.io_numaresourcesoperators.yaml
usual round of `make manifests bundle`
=> manifests: refresh

bundle/manifests/numaresources-operator.clusterserviceversion.yaml
Adding a placeholder icon.
An icon is required by operatorhub.
Please suggest a better icon if you can, the one below is just a quick draft.
Base64 image: iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABHNCSVQICAgIfAhkiAAADThJREFUeJztmnlwVNeVxn/3Lf16k4RaC1rYbbMvQhhjAxZbjJcUEMwwZhNgxzOpSirxeKpmSVHGMVQ8DCmPx04qGcaTMWIbwOAhplzIY2zDhLhsGRMCGCM22+yCFkLqvV/3u/NHozai1a0WqEqZgq/qlVrn3HPud8+7991z7ntCSim5g6F0N4Huxt0AdDeB7sbdAHQ3ge6G1lWOLEuyZ98nXPQ2p20jgIH9yxhTMQIhRIre23iVj/btJxq30vrQFZhWNQ5Pfo92fXQWoiu2QSklv1z739QeNVEduek7AyLXLvLTp0YwecLYNrpI1GTh375C1DOKTISEBEfLF/z2n36M22ncLvWuWwK1n5zE5i5E1Yy0l6IZ2Av6svezL1Psj5/8iialFCWDvaoZKLpBIz05/dXpLuGdXAJHvvgTzS3pp297uO/egRQXlQBgRoLYspiSQggsmdrOjMVRlOzuh253EY+Gr9uZRKKhTrAGVVFx2F3A9QDs+d/dvLz6RSy9iWuNIaSE/EI7l876KemdQ0tTGFVTcOXYuHIhQFGpkx75ucyZ/jfMmzcvMbBOUeg67 …
=> Add operator icon placeholder

doc/examples/mcp.yaml, doc/examples/nrop.image.yaml
Useful to try out quickly things on kind, at least.
=> doc: more example manifests

Makefile, go.mod, go.sum, hack/run-test-e2e.sh, test/utils/objects/objects.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/rte/rte.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/updates.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/rte/daemonset.yaml, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/nrtupdater/nrtupdater.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/conditions.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/metrics.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/topology_updater/topology_updater.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/testenv/testenv.go, vendor/modules.txt
Changes are documented in the commits themselves.
=> Align RTE E2E tests

pkg/apply/apply.go
Let's use consistent importing. No intended change in behaviour.
=> apply: remove client/k8sclient ambiguity

hack/run-test-e2e.sh
=> e2e:skip test including the [StateDirectories] label

main.go
=> logs: init klog flags

controllers/numaresourcesoperator_controller.go, doc/examples/kubeletconfig.yaml, doc/examples/pod.numalign.yaml, main.go, pkg/status/status.go
Miscelanea of minor cleanups emerged while experimenting with the scheduler plugin controller.
Created a cumulative PR because each fix is tiny, so most likely not worth a separate PR for each of them.
=> minor cleanups

.github/workflows/release.yml
fix yet another stale information. Problem is testing this flow outside of the release process is hard.
=> gh action: fix bundle image name

bundle/metadata/annotations.yaml
explicit is (a little better than) implicit
=> bundle: metadata: add default channel

config/manager/manager.yaml
Remove limits according to:
https://issues.redhat.com/browse/CNF-3592
=> Remove limits

doc/examples/kubeletconfig.yaml
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
=> doc: fix kubelet config example to include memory manager policy

.githooks/pre-push, .github/workflows/go.yml, Makefile, hack/verify-generated.sh
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
=> Provide a way to verify generated content via git hook and via our CI

bundle/metadata/annotations.yaml
This annotation was lost because of a (seemingly) bad rebase
on a previous PR.
=> bundle: regenerate annotations

controllers/numaresourcesscheduler_controller.go, controllers/numaresourcesscheduler_controller_test.go, doc/examples/sched.yaml, pkg/apply/apply_test.go, pkg/numaresourcesscheduler/objectstate/sched/sched_test.go, pkg/status/status_test.go, pkg/testutils/testutils.go, test/utils/objects/objects.go
This PR is intended to improve our unit tests coverage.
Unit tests were added to the following packages:
```pkg/controllers```
```pkg/apply```
```pkg/objectstate/sched```
```pkg/status```
=> Improve unit-tests coverage

controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go, main.go
In order to improve state observability, let's add events for the user to understand why (and if) certain actions/operations failed and to notify in case of success.
=> Observability  enhancement

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manager/manager.yaml
Add nodeAffinity to run only on master
=> Add nodeAffinity to run only on master

go.mod, go.sum, rte/main.go, vendor/github.com/andres-erbsen/clock/.travis.yml, vendor/github.com/andres-erbsen/clock/LICENSE, vendor/github.com/andres-erbsen/clock/README.md, vendor/github.com/andres-erbsen/clock/clock.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/notification/notification.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/nrtupdater/nrtupdater.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/ratelimiter/ratelimiter.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcetopologyexporter/resourceobserver.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcetopologyexporter/resourcetopologyexporter.go, vendor/go.uber.org/ratelimit/.gitignore, vendor/go.uber.org/ratelimit/CHANGELOG.md, vendor/go.uber.org/ratelimit/LICENSE, vendor/go.uber.org/ratelimit/Makefile, vendor/go.uber.org/ratelimit/README.md, vendor/go.uber.org/ratelimit/limiter_atomic.go, vendor/go.uber.org/ratelimit/limiter_mutexbased.go, vendor/go.uber.org/ratelimit/ratelimit.go, vendor/modules.txt
=> rte: update to k8swg/rte v0.4.1

controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go
Delete the corresponding MachineConfig for any already deleted NodeGroup
in NRO
=> Delete MachineConfigs for deleted NodeGroups

test/e2e/sched/install/install_test.go
Follow-up for https://github.com/openshift-kni/numaresources-operator/pull/100#discussion_r786541738 where it was found this check could fail due to timeout.
Wrapping scheduler deployment check in an Eventually block make it more resilience to a slow CI
=> Make sched deployment checking more time robust

README.md
Add mention we can deploy scheduler plugins.
=> docs: acknowledge scheduler support

test/utils/clients/clients.go, test/utils/noderesourcetopologies/noderesourcetopologies.go
Will be used at least on https://github.com/openshift-kni/numaresources-operator/pull/110
split to facilitate other incoming tests being written
=> e2e: utils: add functions to get and compare NRTs

test/e2e/install/install_test.go, test/e2e/serial/test_suite_serial_test.go, test/utils/objects/wait/daemonset.go
We wanna check RTE daemonset is restarted and image updated whenever NRO is upgraded.
All these things were almost already done in this test case. I just added a new check to ensure the daemonset is a new one.
=> Check RTE daemonset is restarted

test/e2e/rte/rte_test.go
In the current behavior, we're changing the ```LogLevel``` field under the CR and then checking the change results under the container.
There might be times when the reconciliation loop hasn't occurred yet (thus the pod didn't get updated) and we're already checking for the pod changes under the test.
With the new behavior using Eventually we'll have until timeout to check if the test condition were met.
=> e2e: fix potential race between controller and assertion check

test/e2e/sched/install/install_test.go
The subject in the error messages is NRO Scheduler and not RTE
=> e2e: fix error messages for NRO Scheduler

Makefile, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
- Makefile: bump VERSION to 4.11
- Run ```make bundle```
=> bundle: bump to 4.11

test/e2e/serial/workload_placement_test.go
In order to test workloads are properly scheduled in the right node
taking into account the NUMA Zones resources, testing environment should
fulfill some requirements:
- to have at least two working nodes.
- to have at least one working node with at least more than one NUMA zone
Once those requirements are cheked, we should create a Pod with such a resource requirements that it could
be scheduled into one NUMA zone of one node but also into another node using the combined NUMA zone resources. 
This way we can check the scheduler uses the resources in one NUMA zone instead the other ones.
=> Check guaranteed pod is properly scheduled into a NUMA zone

test/e2e/serial/workload_placement_test.go
Using a deployment with a guaranteed pod as workload, ensure that
if there is one node with at least one NUMA zone with
enough resources to have a pod scheduled into it,
the scheduler will use that NUMA zone even if there are
some other nodes with enough resources at node level to schedule the pod
Checking for at least two nodes with two NUMA zones with enough
resources and padding all but one of those nodes
so they would not have enough resources in only one NUMA zoone
to handle the pod
----
This is similar to #124 but using a deployment as workload
=> e2e: deploy with gu pod scheduled in NUMA zone

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/samples/nodetopology_v1alpha1_numaresourcesoperator.yaml, config/samples/nodetopology_v1alpha1_numaresourcesscheduler.yaml, doc/examples/sched.yaml, test/utils/objects/objects.go
copy data from doc/examples, which still is our authoritative source.
=> bundle: examples: update CR examples

controllers/numaresourcesoperator_controller.go, controllers/numaresourcesscheduler_controller.go, pkg/status/status.go, pkg/status/status_test.go
Use status package to properly compare conditions.
Also avoid code repetition between NRO and SS as much as possible.
handing #169
=> Update SS Conditions cmp to avoid unnnedded update

Makefile, hack/render-e2e-runner.sh, hack/run-test-e2e-serial.sh, test/e2e/serial/workload_placement_test.go, test/utils/noderesourcetopologies/noderesourcetopologies.go, test/utils/resourcelist/resourcelist.go
grab bag of fixes emerged during the fine-tuning of tests
=> e2e: serial: misc fixes

README.md
Add "known limitations" sections
=> docs: document the current limitations

go.mod, go.sum, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/nrtupdater/nrtupdater.go, vendor/modules.txt
fetch fix to update tm policy changes in NRT objects.
=> deps: rte: consume latest changes from u/s

test/e2e/serial/workload_placement_test.go
Having two different nodes which fulfill the pod node selector
check the pod is scheduled in the node having enough resources
in one NUMA zone
=> e2e node selector and resources in one NUMA zone

test/e2e/install/install_test.go, test/e2e/sched/install/install_test.go, test/e2e/serial/non_regression_test.go, test/e2e/serial/sched_removal_test.go, test/e2e/serial/workload_placement_test.go, test/e2e/serial/workload_unschedulable_test.go
Add label [tierX] representing the test's priority:
tier1 -> critical set tests
tier2 -> high priority tests
tier3 -> everything else
=> e2e: add [tierX] labels

test/e2e/serial/tests/configuration.go
this was caused by a forced rushed merge.
=> e2e: serial: fix rebase glitch

go.mod, go.sum, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/rte.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/pods/rtepod/rtepod.go, vendor/modules.txt
=> vendor: bump rte deps 20220405

controllers/kubeletconfig_controller_test.go, controllers/numaresourcesoperator_controller_test.go, controllers/numaresourcesscheduler_controller_test.go, internal/baseload/baseload.go, internal/baseload/baseload_test.go, internal/objects/objects.go, internal/resourcelist/resourcelist.go, internal/resourcelist/resourcelist_test.go, pkg/status/status_test.go, pkg/validation/validation_test.go, pkg/version/version_test.go
grab bag of minor cleanups gathered over the last week or two
=> project: misc cleanups

test/e2e/serial/tests/workload_placement_taint.go
To prevent errors like
```
Status: "Failure",
Message: "Operation cannot be fulfilled on nodes ABC: the object has been modified; please apply your changes to the latest version and try again",
```
Let's make sure to wrap the untaint operation in a `Eventually` block,
and also let's make sure to get a fresh copy of the object before any
update attempt.
=> e2e: serial: more robust untainting

test/e2e/serial/tests/workload_unschedulable.go
Given a cluster with multiple nodes and multiple numa zones per node
When a Daemonset, with guaranteed pods, ask for resources only available
on some of the nodes
Then all the daemonset pods are scheduled by Secondary Scheduler but
only those in the nodes with resources end in  Running state while the
other keep Pending.
=> e2e_test Daemonset partial available resources

test/e2e/serial/tests/workload_unschedulable.go
Given topology-manager-scope=pod
When trying to schedule a pod with two containers and each of them fits on different numa zones
then pod is not scheduled.
=> e2etest: TopoManager scope=pod two containers not sched

test/e2e/serial/tests/workload_unschedulable.go
This test creates a deployment with multiple replicas with a pod that is not fit into a node at the numa-level, meanning that there are enough resources in all numa nodes together, but not enough in each one of them, so all pods` replica scheduling must be failed.
In the next step we're reducing the amount of resources requests by the pod and expect at least some of the replicas to be running.
=> e2e:serial: unschedulable numa level test

README.tests.md
Grab bag of documentation fixes. No code changes.
=> docs: fixes

.github/workflows/release.yml
=> gh actions: trigger release also with -rc tags

OWNERS_ALIASES
=> update OWNERS 20220421

test/e2e/serial/README.md, test/e2e/serial/config/config.go, test/e2e/serial/config/infra.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement_nodelabel.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go, test/utils/images/images.go, test/utils/objects/consts.go, test/utils/objects/daemonset.go, test/utils/objects/deployment.go, test/utils/objects/objects.go, test/utils/objects/pod.go, test/utils/objects/wait/daemonset.go, test/utils/objects/wait/deployment.go, test/utils/objects/wait/errors.go, test/utils/objects/wait/machineconfig.go, test/utils/objects/wait/numaresources.go, test/utils/objects/wait/paddingpods.go, test/utils/objects/wait/pod.go
grab bag of fixes after validating the tests on a multi-numa multi-node cluster
=> e2e serial fixes (20220421)

.github/workflows/release-operator.yaml, .github/workflows/release-testsuite.yaml, Dockerfile.tests
Add provisions to build and upload the tests image alongside the existing flow for the operator images
=> gh actions: add functionality to refresh the testsuite image

README.tests.md, hack/run-test-serial-e2e.sh
Explicitely document that we can (and in the developer flow we probably should) run the tests from a local tree
=> documentation: explain how to run from the local tree

test/e2e/serial/tests/workload_placement_tmpol.go
To track the results of each test and properly update the tests' report.
=> serial: add missing test ids

README.tagging.md
Let's clarify how we do tags, and let's start implementing
this model once this development cycle ends.
=> doc: document the tagging model

README.md, test/e2e/serial/tests/workload_placement_resources.go
Periodic grab bag of fixes and cleanups
=> e2e: serial: cleanups and fixes 20220517

Dockerfile.tools
We need to set an explicit (albeit generic) version
=> Dockerfile.tools: fix as suggested by the tool

main.go, rte/main.go
Make sure we report this information for troubleshooting purposes.
=> project: log program/runtime version at startup

go.mod, go.sum, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/rte/rte-notifier.sh, vendor/modules.txt
consume notifier script fixes u/s
=> deps: bump deployer to v0.6.1

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
=> olm:csv: add skipRange annotation

internal/noderesourcetopology/tostring.go, internal/noderesourcetopology/tostring_test.go, internal/resourcelist/resourcelist.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/sched_removal.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_nodelabel.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go, test/utils/noderesourcetopologies/noderesourcetopologies.go, test/utils/objects/wait/deployment.go
e2e tests improvement to support `scope=container` to complement #308
=> e2e: serial tests fixes and tuning

internal/objects/objects_test.go, pkg/objectnames/objectnames_test.go
Bootstrap coverage for two packages with high-ROI tests
=> testing: improve unit tests coverage

controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go, main.go, test/e2e/install/install_test.go, test/e2e/rte/rte_test.go, test/e2e/sched/install/install_test.go, test/e2e/sched/sched_test.go, test/e2e/sched/uninstall/uninstall_test.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_nodelabel.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go, test/e2e/uninstall/uninstall_test.go, test/utils/fixture/fixture.go
Another grab-bag of mixed improvements and cleanups emerged during the deflaking attempt tracked inhttps://github.com/openshift-kni/numaresources-operator/pull/323. The real issue seems to be a selinux policy misalignment which will be tracked and fixed separately, but I believe there's work worth preserving in what we did in #323, so we go.
=> e2e fixes and cleanups

test/e2e/serial/tests/non_regression.go
The test creates a deployment, pins it selectively to a specific node. In addition to that,
it is checked that NRT objects are updated appropriately.
=> e2e: serial: schedule gu pod as part of a deployment to a specific node

test/e2e/serial/tests/resource_accounting.go
Test case: Daemonset with a non-gu (burstable) pod requesting resources
available on one node but not on a single numa.
No changes in NRT objects occur.
=> e2e: serial: daemonset with non-gu pod requesting resources on a node

hack/run-test-must-gather-e2e.sh, test/e2e/install/install_test.go, test/e2e/must-gather/must_gather_suite_test.go, test/e2e/must-gather/must_gather_test.go, test/utils/deploy/deploy.go, test/utils/objects/wait/numaresources.go
As must-gather PAO now collects information about NRO ( openshift-kni/performance-addon-operators#919 ) 
we need to add new test suite to check it.
issue: #330
=> Must gather e2e test

test/e2e/serial/tests/resource_accounting.go
grab bag of fixes for the resource accounting tests
=> e2e: fix resource accounting tests

rte/main.go
=> rte: print version earlier

test/e2e/serial/tests/workload_placement.go
Create a workload using TAS scheduler that is scheduled followed by
another similar workload using the default scheduler that stays pending.
=> e2e: serial: create workload with TAS followed by default scheduler

internal/baseload/baseload.go, test/e2e/serial/tests/workload_placement.go
This test involves modification (reduction) of requested resources
where resource requests are available from 2 NUMA nodes and verification
that the NRT instances are updated correctly.
=> e2e: serial: placement testing of a deployment with 2 replicas

test/e2e/serial/tests/workload_overhead.go
Test case where pod overhead is such that even though resources requested
by a pod are enough to be successfully allocated on the target node, the
amount of pod overhead impacts the fate of the pod keeping it in pending
state as the node zone doesn't have enough resources (pod resource request + pod
overhead).
=> e2e: serial: pod pending when (request + overhead) > zone allocatable

README.md
=> docs: Capturing that non-exclusive CPUs are not accounted in NRT objects

test/e2e/serial/tests/workload_placement_tmpol.go
Schedule a pod with 2 containers each requesting different device types. Enough resources are available on one node but distributed across NUMA nodes such that it is not possibile for the containers to obtain resources from a single numa and therefore the pod stays pending.
=> e2e: serial: negative-test: topology alignment of pod requesting devices

test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/non_regression_fundamentals.go
With this label we can easily run only the nonregression tests
=> e2e: serial: add label to group nonregression test

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manager/manager.yaml, controllers/numaresourcesoperator_controller.go, pkg/objectstate/rte/rte.go
Grab-bag of fixes emerged during the implementation of the scheduler cache support. Please see each commit for details.
=> miscelaneous fixes 20220927

go.mod, go.sum, vendor/github.com/k8stopologyawareschedwg/podfingerprint/podfingerprint.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go, vendor/modules.txt
=> deps: bump RTE to v0.7.3, PFP to v0.0.3

test/e2e/serial/tests/workload_placement_tmpol.go
Replace the explicit device name with the relevant function that gets this name from the environment variables for the device types.
=> serial: device resources cleanup

internal/nodes/nodes.go, test/e2e/install/install_test.go, test/e2e/install/test_suite_install_test.go, test/e2e/rte/rte_e2e_suite_test.go, test/e2e/rte/rte_test.go, test/e2e/sched/install/install_test.go, test/e2e/sched/install/test_suite_install_test.go, test/e2e/sched/sched_test.go, test/e2e/sched/test_suite_sched_test.go, test/e2e/sched/uninstall/test_suite_uninstall_test.go, test/e2e/sched/uninstall/uninstall_test.go, test/e2e/sched/utils/daemonset.go, test/e2e/sched/utils/deployment.go, test/e2e/sched/utils/node.go, test/e2e/sched/utils/replicaset.go, test/e2e/serial/e2e_serial_test.go, test/e2e/uninstall/test_suite_uninstall_test.go, test/e2e/uninstall/uninstall_test.go, test/utils/clients/clients.go, test/utils/configuration/configuration.go, test/utils/crds/crds.go, test/utils/fixture/fixture.go, test/utils/images/consts.go, test/utils/images/images.go, test/utils/noderesourcetopologies/noderesourcetopologies.go, test/utils/nrosched/nrosched.go, test/utils/objects/replicaset.go, test/utils/padder/padder.go, test/utils/runtime/runtime.go, tools/tools.go
=> adjust the copyright to Red Hat

hack/run-test-serial-e2e.sh, test/e2e/serial/tests/sched_removal.go
grab bag of minor fixes found while working on the sched-cache branch. Please check each commit for details.
=> Cleanup 20221013

controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go, main.go
backport of non-test-related commits in #324
=> [release-4.11][manual] partial backport of PR #324

.github/workflows/e2e-local.yaml, .github/workflows/e2e-tools.yml, .github/workflows/e2e.yml, hack/run-test-e2e.sh, test/utils/runtime/runtime.go
Add more troubleshooting logs when finding executables.
=> test: e2e: rte: move to dedicated GH actions lane

test/e2e/serial/tests/workload_placement_tmpol.go
Automate new tests involving device resources while the test pod is non-guaranteed.
Test cases id:
54022,54023,54025,55429,55430,55431
=> serial: add new tests with device resources

test/e2e/serial/README.md, test/utils/fixture/devices.go
minor grab bag of fixes. Please check the commit messages for details.
=> Cleanup 20221107

test/e2e/sched/install/install_test.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement_nodelabel.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go
Followup found after more field testing of #466 and #468
=> Cleanup 20221109

controllers/controllers_suite_test.go, controllers/kubeletconfig_controller.go, controllers/kubeletconfig_controller_test.go, controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go, controllers/numaresourcesscheduler_controller.go, controllers/numaresourcesscheduler_controller_test.go, test/e2e/sched/install/install_test.go, test/e2e/serial/config/fixture.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/sched_removal.go, test/e2e/serial/tests/workload_unschedulable.go, test/utils/nrosched/nrosched.go, test/utils/objects/objects.go
extract from https://github.com/openshift-kni/numaresources-operator/pull/443 code independent fixes that can be merged early
=> Cleanup 20221111

test/e2e/serial/tests/configuration.go
The NUMAResourceOperator spec may miss the NodeGroupConfig spec, and the tests should handle this state gracefully.
Additionally, wrap the main testing logic in a Eventually block, because the status can take nonzero time to be correctly populated, and this should not make the test fail.
=> e2e: serial: handle missing NodeGroupConfig in spec

internal/wait/daemonset.go, internal/wait/deployment.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_unschedulable.go
The PR addresses a fix for tests that failed because of checking empty pods that are related to resources like deployment/daemon sets. Please see the different commit messages for more details on each modification.
=> serial tests fixes

internal/noderesourcetopology/tostring.go, internal/noderesourcetopology/tostring_test.go, test/e2e/serial/config/infra.go, test/e2e/serial/tests/configuration.go, test/utils/noderesourcetopologies/noderesourcetopologies.go
test fixes and improvements which emerged during the tuning of e2e tests added in https://github.com/openshift-kni/numaresources-operator/pull/443 . Each commit is independent. Please refer to each commit for details.
=> e2e: test fixes 20221201

api/numaresourcesoperator/v1alpha1/helper/nodegroup/nodegroup.go
fix misplaced code (was a loop invariant) which cause unnecessary, albeit little, extra work.
Found during the review of #504
=> api: nodegroup: fix loop invariant

OWNERS, OWNERS_ALIASES
update aliases set and perform long due update to the names of the groups
=> Update prow configuration 20230131

controllers/numaresourcesoperator_controller_test.go
Add a unit test to verify that the controller reacts properly to the NodeGroup.Config updates.
We will evaluate e2e coverage in another PR.
=> controller: add test for nodegroup config changes

internal/machineconfigpools/machineconfigpools.go, test/e2e/rte/rte_test.go
remove dangling obsolete references to v1alpha1 API
=> remove NROP v1alpha1 remnants

pkg/numaresourcesscheduler/manifests/yaml/deployment.yaml
update the scheduler manifests to catch up with deployer, secondary-scheduler-operator and acknowledging the ongoing perf tests.
=> Update scheduler manifests

test/utils/nrosched/nrosched.go
We are getting a flake lately on which we see default scheduler events missing the `ReportingController` field populated which is unexpected and, well, makes the test flake.
Add extra logs and more precise filtering to narrow down the issue.
xref: https://github.com/openshift-kni/numaresources-operator/pull/551
=> e2e: nrosched: add extra logs and filters

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manifests/bases/numaresources-operator.clusterserviceversion.yaml
Acknowledge the operator is stable now
=> csv: fix operator maturity alpha->stable

controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go
cleanups and refinements post-merge
=> cleanup 20230523

.github/workflows/cibuild.yml, .github/workflows/ciformat.yml, .github/workflows/cilint-custom.yml, .github/workflows/cilint.yml, .github/workflows/e2e-local.yaml, .github/workflows/e2e-tools.yml, .github/workflows/e2e.yml, .github/workflows/release-operator.yaml, .github/workflows/release-testsuite.yaml
Move forward to fix deprecations
=> ghactions: update base actions

go.mod, go.sum, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go, vendor/modules.txt
trivial bump to consume u/s fixes.
=> deps: bump RTE to v0.11.2

internal/noderesourcetopology/tostring.go, test/e2e/serial/config/infra.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/utils/objects/pod.go, test/utils/padder/padder.go
log improvements: log more specialized data, make dump more concise
=> e2e: serial improve logs

internal/wait/noderesourcetopologies.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/workload_unschedulable.go, test/utils/noderesourcetopologies/noderesourcetopologies.go
Fixes to utilities to be more robust and to reduce flakiness, emerged during the review of #598
=> e2e: serial: resacct improve and generalize expectations, take 2

internal/noderesourcetopology/equality.go, internal/noderesourcetopology/equality_test.go, internal/noderesourcetopology/sorted.go, internal/noderesourcetopology/sorted_test.go, internal/wait/noderesourcetopologies.go, test/deviceplugin/pkg/numacell/api/numacell.go, test/e2e/serial/README.md, test/e2e/serial/config/config.go, test/e2e/serial/config/fixture.go, test/e2e/serial/config/infra.go, test/utils/fixture/fixture.go
further improvements and cleanups following the implementation of the NRT settlement support
=> e2e cleanup 20230628

Makefile, test/e2e/must-gather/README.md, test/e2e/must-gather/must_gather_suite_test.go, test/e2e/must-gather/must_gather_test.go, test/utils/deploy/deploy.go
overall cleanup and misc improvements.
enable the suite to easily run in development environments and/or existing clusters; also enable concurrent runs
=> must-gather: debuggability updates

api/numaresourcesoperator/v1/numaresourcesoperator_defaults.go, api/numaresourcesoperator/v1/numaresourcesoperator_defaults_test.go, api/numaresourcesoperator/v1/numaresourcesoperator_normalize_test.go, controllers/numaresourcesoperator_controller_test.go, pkg/objectupdate/rte/rte_test.go
We documented that the default InfoRefreshMode value should be "Periodic", not "PeriodicAndEvents", so let's fix the code accordingly.
=> operator: rte: default inforefreshmode=periodic

test/e2e/sched/sched_test.go
Add a test for verifying that cacheResyncPeriod
settings are propogated properly from the CR
to Status and the scheduler's ConfigMap
=> e2e:scheduler: verify cacheResyncPeriod settings

.github/workflows/cibuild.yml, .github/workflows/ciformat.yml, .github/workflows/cilint-custom.yml, .github/workflows/cilint.yml, .github/workflows/e2e-local.yaml, .github/workflows/e2e-tools.yml, .github/workflows/e2e.yml, .github/workflows/release-operator.yaml, Dockerfile, Dockerfile.pause, Dockerfile.tests, Dockerfile.tools, go.mod
RHAOS 4.14 is rhel9 and golang 1.20
=> golang: move to 1.20

tools/buildhelper/buildhelper.go, tools/catkubeletconfmap/catkubeletconfmap.go, tools/envsubst/envsubst.go, tools/lsplatform/lsplatform.go
Legally speaking probably redundant, but let's be consistent.
=> tools: add license boilerplate

.github/workflows/release-testsuite.yaml, Dockerfile.must-gather, Makefile, README.tests.md, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/numaresources-operator.clusterserviceversion.yaml, config/samples/nodetopology_v1_numaresourcesscheduler.yaml, config/samples/nodetopology_v1alpha1_numaresourcesscheduler.yaml, doc/examples/sched.yaml, test/e2e/must-gather/README.md, test/e2e/must-gather/must_gather_suite_test.go, test/utils/objects/objects.go
now that we branched off 4.14 we can move the main branch to 4.15
=> version: bump to 4.15

doc/examples/sched.debug.yaml, doc/examples/sched.nocache.yaml
use proper imageSpec. It's just an example, but still.
=> doc: fix examples

OWNERS_ALIASES
reflect user activity in the past few months
=> owners: update 20231012

Dockerfile, Dockerfile.pause, Dockerfile.tests, Dockerfile.tools
=> golang: bump toolchain

go.mod, go.sum, rte/main.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/prometheus/prometheus.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcetopologyexporter/resourcetopologyexporter.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/metrics.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/testenv/testenv.go, vendor/modules.txt
disable metrics by default until we can re-enable them safely.
=> rte: bump to 0.14.3

go.mod, go.sum, rte/main.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/prometheus/prometheus.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcetopologyexporter/resourcetopologyexporter.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/metrics.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/rte.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/topology_updater/topology_updater.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/nodes/nodes.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/testenv/testenv.go, vendor/modules.txt
include (trivial) API changes.
=> [release-4.13][manual] rte: bump to 0.11.5

go.mod, go.sum, rte/main.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/prometheus/prometheus.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcetopologyexporter/resourcetopologyexporter.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/metrics.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/rte.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/topology_updater/topology_updater.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/nodes/nodes.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/utils/testenv/testenv.go, vendor/modules.txt
include (trivial) API changes.
=> [release-4.12][manual] rte: bump to 0.11.5

Makefile
once again, no real reason to be stuck on ancient 1.24
=> envtest: bump to 1.27

.snyk
this code will never reach anything near production, so the checks are not helping.
=> snyk: e2e: ignore test code - unit and e2e

controllers/numaresourcesoperator_controller_test.go, internal/relatedobjects/objects_test.go, pkg/objectstate/objectstate_test.go, pkg/objectstate/rte/rte_test.go, test/utils/configuration/configuration.go
add unit tests to improve test coverage. No production level change.
=> improve test coverage 20231115

Dockerfile.tests, hack/render-e2e-runner.sh, hack/run-test-must-gather-e2e.sh, hack/run-test-tools-e2e.sh
This PR contains the modifications required to enable running the must gather tests in the NROP pipeline.
=> modified render to add must-gather tests

Dockerfile.pause, Dockerfile.pause.gcc, Makefile, hack/pause.c
Also add Makefile helpers, defaulting to the C-based (not the existing shell-based) implementation.
=> pause: add C-based implementation

.github/workflows/release-testsuite.yaml, Dockerfile.must-gather, Makefile, README.tests.md, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/numaresources-operator.clusterserviceversion.yaml, config/samples/nodetopology_v1_numaresourcesscheduler.yaml, config/samples/nodetopology_v1alpha1_numaresourcesscheduler.yaml, doc/examples/sched.debug.yaml, doc/examples/sched.nocache.yaml, doc/examples/sched.yaml, test/e2e/must-gather/README.md, test/e2e/must-gather/must_gather_suite_test.go, test/utils/objects/objects.go
=> tree: version: kickoff 4.16

go.mod, go.sum, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/sysinfo/hugepages.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/sysinfo/memory.go, vendor/modules.txt
trivial deps bump to consume sysinfo updates
=> [release-4.14] deps: consume RTE 0.15.3

README.md
add instructions to deploy using OLM in development clusters
=> docs: add OLM deployment quickstart

go.mod, go.sum, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.14.cil, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.15.cil, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/schedparams.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/objectupdate/sched/render.go, vendor/modules.txt
trivial dep bump to consume fixes and enhancements
=> deps: bump deployer to v0.17.3

.github/workflows/ciformat.yml, .github/workflows/cilint-custom.yml, .github/workflows/civerify-commit.yml, hack/verify-commits.sh, tools/verify-commit/verify-commit.go
add lane to do minimal verification of commits metadata.
=> ci: add minimal commit verification lane

go.mod, go.sum, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/assets/selinux/policy/ocp_v4.13.cil, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/kubeletconfig/configz.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/schedparams.go, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/objectupdate/sched/render.go, vendor/modules.txt
=> [release-0.13] deps: bump deployer to v0.14.2

go.mod, go.sum, vendor/github.com/jaypipes/ghw/README.md, vendor/github.com/jaypipes/ghw/doc.go, vendor/github.com/jaypipes/ghw/pkg/block/block.go, vendor/github.com/jaypipes/ghw/pkg/block/block_linux.go, vendor/github.com/jaypipes/ghw/pkg/block/block_windows.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu.go, vendor/github.com/jaypipes/ghw/pkg/cpu/cpu_linux.go, vendor/github.com/jaypipes/ghw/pkg/gpu/gpu_windows.go, vendor/github.com/jaypipes/ghw/pkg/linuxpath/path_linux.go, vendor/github.com/jaypipes/ghw/pkg/memory/memory_linux.go, vendor/github.com/jaypipes/ghw/pkg/net/net.go, vendor/github.com/jaypipes/ghw/pkg/net/net_linux.go, vendor/github.com/jaypipes/ghw/pkg/pci/pci_linux.go, vendor/github.com/jaypipes/ghw/pkg/util/util.go, vendor/modules.txt
bump to fetch the latest fixes
=> deps: ghw: bump to v0.12.0

controllers/numaresourcesoperator_controller.go, pkg/objectupdate/rte/rte.go
backport some of the minor fixes and cleanups included in #852
=> [release-4.15][manual] backport minor fixes and cleanups from RTE pause support

OWNERS_ALIASES
update to reflect contributors activity
=> tree: update owners 20240306

go.mod, test/deviceplugin/pkg/numacell/cmd/numacell.go, test/e2e/rte/rte_test.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_nodelabel.go, test/e2e/serial/tests/workload_unschedulable.go, test/utils/fixture/fixture.go, test/utils/objects/objects.go
sigs.k8s.io/yaml is a permanent fork of github.com/ghodss/yaml
Use consistently always the former in our code.
The latter will be still pulled from deps we have no control about.
=> deps: github.com/ghodss/yaml -> sigs.k8s.io/yaml

README.md
we actually support more than a single RH tracking board, reflect that in the docs.
=> docs: issues: generalize RH boards

controllers/numaresourcesoperator_controller.go
some of the changes in the daemonUpdater callback
are platform agnostic and should be performed anyway.
=> controller: fix daemonUpdater

internal/podlist/node.go, internal/wait/daemonset.go, test/e2e/serial/tests/tolerations.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_unschedulable.go
manual cherry pick of:
https://github.com/openshift-kni/numaresources-operator/pull/905/commits/dfd0feca7e0eebae2731cc29816e5d23a1b0ce2f
#910 
#900
=> [release-4.15] manual cherry-pick of 900,910,912

test/e2e/serial/tests/tolerations.go
Add two tests to check that when updating taints or tolerations in a way that shakes the matching criteria the RTE pod  will get evicted.
=> e2e: tolerations: test CR and taint updates

internal/wait/daemonset.go, test/e2e/serial/tests/tolerations.go
please see commits for the specific details.
=> e2e: fix toleration tests flakes

test/e2e/sched/sched_test.go
We need to always make sure we retry Update()s,
like inside Eventually() loops, to avoid flakes.
=> e2e: sched: ensure updates are retried

controllers/numaresourcesoperator_controller_test.go, controllers/numaresourcesscheduler_controller_test.go, test/e2e/install/install_test.go, test/e2e/rte/local/local.go, test/e2e/sched/sched_test.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/workload_placement_taint.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/tools/test_suite_tools_test.go, test/utils/deploy/deploy.go
rather than use WithOffset variants, which composes badly, let's leverage ginkgo.GinkgoHelper() to achieve the same result in a more composable and easier way.
=> e2e: WithOffset -> GinkgoHelper

internal/resourcelist/resourcelist.go, internal/resourcelist/resourcelist_test.go, test/e2e/serial/config/config.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/resource_hostlevel.go, test/e2e/serial/tests/workload_placement.go, test/utils/objects/pod.go
extend the existing non-regression test coverage to all possible QoSes besides Guaranteed.
=> e2e: hostlevel: cover all pod QoSes

Makefile, tools/watchnrtattr/watchnrtattr.go
mostly a demo for the watch client
=> tools: add new utility to watch NRT attrs

internal/resourcelist/resourcelist.go, internal/resourcelist/resourcelist_test.go, test/e2e/serial/tests/resource_hostlevel.go
Add a check to verify NRT is updated accordingly for gu pods or not
updated for non-gu pods.
=> e2e: host-level: verify NRT updates

test/e2e/serial/tests/resource_hostlevel.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go, test/utils/noderesourcetopologies/noderesourcetopologies.go, test/utils/nrosched/nrosched.go
Extend e2e tests coverage with negative tests with differnt QoS's.
=> e2e: hostlevel: add negative tests

.github/workflows/cibuild.yml, .github/workflows/ciformat.yml, .github/workflows/cilint-custom.yml, .github/workflows/cilint.yml, .github/workflows/civerify-commit.yml, .github/workflows/e2e-local.yaml, .github/workflows/e2e-tools.yml, .github/workflows/e2e.yml, .github/workflows/golangci-lint.yaml, .github/workflows/release-operator.yaml
=> golang: bump to 1.22.4

test/e2e/serial/tests/resource_hostlevel.go, test/e2e/serial/tests/workload_placement_resources.go
The tests sometimes fail because of "no event received for e2e-test-resource-hostlevel-XXX/testpod", this is because the automation fetches the test pod object from the cluster too early before it is being scheduled.
To fix this flakiness, wait for the pod's anticipated phase post creating it.
=> e2e: wait for pod phase post creation

.github/workflows/release-testsuite.yaml, Dockerfile.must-gather, Makefile, README.tests.md, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/numaresources-operator.clusterserviceversion.yaml, config/samples/nodetopology_v1_numaresourcesscheduler.yaml, config/samples/nodetopology_v1alpha1_numaresourcesscheduler.yaml, doc/examples/sched.debug.yaml, doc/examples/sched.nocache.yaml, doc/examples/sched.yaml, test/e2e/must-gather/README.md, test/e2e/must-gather/must_gather_suite_test.go, test/e2e/serial/README.md, test/utils/configuration/configuration.go, test/utils/objects/objects.go
=> tree: version: move to 4.17

controllers/kubeletconfig_controller.go, controllers/numaresourcesoperator_controller.go, controllers/numaresourcesscheduler_controller.go, doc/examples/pod.ephstor.yaml, pkg/apply/apply.go, pkg/apply/apply_test.go
internal cleanup of the reconciliation functions to enable future enhancements
xref: OCPBUGS-36314
=> numaresources: cleanup and modularize controller

go.mod, go.sum, internal/wait/pod.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/resource_accounting.go, test/e2e/serial/tests/resource_hostlevel.go, test/e2e/serial/tests/tolerations.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement_tmpol.go, test/e2e/serial/tests/workload_unschedulable.go, vendor/golang.org/x/sync/LICENSE, vendor/golang.org/x/sync/PATENTS, vendor/golang.org/x/sync/errgroup/errgroup.go, vendor/golang.org/x/sync/errgroup/go120.go, vendor/golang.org/x/sync/errgroup/pre_go120.go, vendor/modules.txt
This PR goal is to fix common issues we see in the d/s CI. Please check the commits for more details.
=> host-level and reboot-required tests stablization

hack/verify-commits.sh, tools/verify-commit/verify-commit.go
Add support for multiple signoff or for co-authorship
=> hack: workflow: support multiple commit authors

test/e2e/serial/tests/configuration.go
This test add automation coverage for OCPBUGS-34583
The numaresources secondary-scehduler doesn't account for topology-manager new configuration unless it gets deleted and restarted again. This means TAE can still occur if topology manager policy was updated to single-numa-node and the scheduler not restarted after that update.
This test checks that scenario by ensuring the TM policy is set to none then restarting the scheduler, setting back the TM policy to single-numa-node and then creating a TAE deployment to check if the deployment is pending
=> e2e: add test scheduler picks TM policy update without need to restart

Dockerfile.openshift.tests, Dockerfile.tests
include the topics.json generated at build time in the tests images.
=> Dockerfile: include topics

doc/features/README.md, internal/api/features/_topics.json, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/scheduler_removal.go, test/e2e/tools/mkginkgolabelfilter_test.go, tools/mkginkgolabelfilter/mkginkgolabelfilter.go
This is a followup for https://github.com/openshift-kni/numaresources-operator/pull/958, please see commits for more details.
=> upgrade ginkgo and additional feature introspection followup

controllers/numaresourcesscheduler_controller.go, controllers/numaresourcesscheduler_controller_test.go
=> sched: controller: set scheduler priority

.github/workflows/e2e-tools.yml, doc/features/README.md, internal/api/features/_topics.json, internal/api/features/topics.go, internal/api/features/topics_test.go, internal/api/features/types.go, internal/api/features/types_test.go, main.go, test/e2e/serial/README.md, test/e2e/tools/mkginkgolabelfilter_test.go, test/e2e/tools/tools_test.go, tools/mkginkgolabelfilter/mkginkgolabelfilter.go
manual backport of https://github.com/openshift-kni/numaresources-operator/pull/986
=> [release-4.14] add features introspection for e2e tests 

.github/workflows/e2e-tools.yml, doc/features/README.md, internal/api/features/_topics.json, internal/api/features/topics.go, internal/api/features/topics_test.go, internal/api/features/types.go, internal/api/features/types_test.go, main.go, test/e2e/serial/README.md, test/e2e/tools/mkginkgolabelfilter_test.go, test/e2e/tools/tools_test.go, tools/mkginkgolabelfilter/mkginkgolabelfilter.go
=> [release-4.13] add features introspection for e2e tests 

.github/workflows/release-testsuite.yaml, Dockerfile.must-gather, Makefile, README.tests.md, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/numaresources-operator.clusterserviceversion.yaml, config/samples/nodetopology_v1_numaresourcesscheduler.yaml, config/samples/nodetopology_v1alpha1_numaresourcesscheduler.yaml, doc/examples/sched.debug.yaml, doc/examples/sched.ha.yaml, doc/examples/sched.nocache.yaml, doc/examples/sched.yaml, internal/api/features/types.go, internal/api/features/types_test.go, test/e2e/must-gather/README.md, test/e2e/must-gather/must_gather_suite_test.go, test/e2e/serial/README.md, test/utils/objects/objects.go
=> tree: version: move to 4.18

api/numaresourcesoperator/v1/helper/nodegroup/nodegroup.go
=> api: docs: start documenting nodegroup and tree

controllers/numaresourcesoperator_controller.go, controllers/numaresourcesoperator_controller_test.go
grab bug of misc cleanups, please look at individual commits for details.
Nothing riskier than "low risk" here.
=> Cleanups 20241017

.github/workflows/ci.yaml, .github/workflows/e2e-local.yaml, .github/workflows/e2e-tools.yaml, .github/workflows/e2e.yaml, .github/workflows/golangci-lint.yaml, .github/workflows/release-operator.yaml, .github/workflows/release-testsuite.yaml, .github/workflows/support-tools.yaml
update CI github action versions for base images and for golang toolchain
=> CI: Update github actions versions

internal/dangling/dangling.go
After the new API for PoolName, we are now should detect DaemonSet by `PoolName` and not only by MCP selector.
This will resolve the:
```
E1111 10:46:31.948164       1 controller.go:329] "Reconciler error" err="FailedRTESync: failed to apply (apps/v1, Kind=DaemonSet) numaresources/numaresourcesoperator-hostedcluster02: could not update object (apps/v1, Kind=DaemonSet) numaresources/numaresourcesoperator-hostedcluster02: Operation cannot be fulfilled on daemonsets.apps \"numaresourcesoperator-hostedcluster02\": StorageError: invalid object, Code: 4, Key: /kubernetes.io/daemonsets/numaresources/numaresourcesoperator-hostedcluster02, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: a2590c0a-e367-4422-81af-0658b7ccec74, UID in object meta: " …
```
=> controller: handle dangling ds when using poolname

.github/workflows/ci.yaml, .github/workflows/e2e-local.yaml, .github/workflows/e2e-tools.yaml, .github/workflows/e2e.yaml, .github/workflows/golangci-lint.yaml, .github/workflows/release-operator.yaml, .github/workflows/support-tools.yaml, Dockerfile, Dockerfile.pause, Dockerfile.tests, Dockerfile.tools
bump golang builder images and versions to 1.23.3 in both github actions CI and Dockerfiles
=> Bump golang build 1.23

internal/kloglevel/kloglevel.go, main.go, tools/nrtcacheck/nrtcacheck.go
introduce the internal/kloglevel to clean up the existing handling of
=> add the internal/kloglevel package

.github/workflows/release-testsuite.yaml, Dockerfile.must-gather, Makefile, README.tests.md, bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/numaresources-operator.clusterserviceversion.yaml, config/samples/nodetopology_v1_numaresourcesscheduler.yaml, config/samples/nodetopology_v1alpha1_numaresourcesscheduler.yaml, doc/examples/sched.debug.yaml, doc/examples/sched.ha.yaml, doc/examples/sched.nocache.yaml, doc/examples/sched.yaml, internal/api/features/types.go, test/e2e/must-gather/must_gather_suite_test.go, test/utils/objects/objects.go
=> tree: version: move to 4.19

.github/workflows/ci.yaml, .github/workflows/e2e-local.yaml, .github/workflows/e2e-tools.yaml, .github/workflows/e2e.yaml, .github/workflows/golangci-lint.yaml
and uniform/clarify/simplify the workflow triggers which was different for silly historical reasons
=> ghactions: enable on stable branches

internal/api/buildinfo/types_test.go
add missing unit test coverage
=> internal: buildinfo: add missing test coverage

pkg/objectstate/api/api.go, pkg/objectstate/api/api_test.go
bootstrap unit tests for `pkg/objstate/api`
=> objstate: api: kickoff tests

.github/workflows/release-numacell.yml, test/deviceplugin/cmd/numacell/Dockerfile
Fix the dockerfile to be self-contained (use builder step) and add gh action release flow to make updating the CI image easier.
=> ci: numacell: fix dockerfile, add release flow

.github/workflows/release-numacell.yml, .github/workflows/release-testsuite.yaml
=> gh actions: fix release flows

test/e2e/serial/config/config.go
Some of the test pods are asking for an odd number of CPUs.
if SMT alignment enabled the test will fail in the middle of the
run and it will requires extra time and effort to understand the
root cause.
Lets avoid that and fail loudly in the beginning of the test
explaining that SMT alignment should be disabled.
The serial suite has a unique characteristics and it should
be running on a dedicated environment,
so although smt alignment should usually be enable
for the test purposes it make a complete sense to require
its disabelement.
=> serial:config: validate smt alignment is off

ARCHITECTURE.md
clarify package layout, minor text updates
=> docs: update architecture.md

internal/nodegroups/nodegroups.go, internal/nodegroups/nodegroups_test.go, test/e2e/serial/config/config.go, test/e2e/serial/tests/resource_hostlevel.go, test/e2e/serial/tests/workload_placement.go
fixes for issue running the serial suite against a classic OCP cluster. Please check each commit for details.
=> e2e serial fixes: 20250204

test/e2e/serial/tests/workload_placement.go
Even in case of failure, printing the scheduling logs is excessive, and it is anyway stored in the artifacts of the d/s CI.
=> e2e: don't print scheduler logs in tests

test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/resource_hostlevel.go, test/e2e/serial/tests/tolerations.go
please see commit messages for details.
=> serial tests fixes 

internal/dangling/dangling_test.go, test/internal/fixture/fixture.go
Add missing unit tests for dangling pkg with fake client.
=> internal: add unit tests for dangling

pkg/status/status.go, pkg/status/status_test.go
Similarly to https://github.com/kubernetes/kubernetes/issues/104821 , we use the go-cmp package in our non-test code. Problem is: this package reserves the right to panic, which is something we cannot accept in out non-test code. We need to replace to similar code which guarantee not to panic.
Replace go-cmp.Equal with reflect.DeepEqual in non-test code. more on reflect.DeepEqual: https://pkg.go.dev/reflect#DeepEqual.
=> OCPBUGS-49407: pkg: use go-cmp only in tests

.golangci.yml, api/v1/helper/nodegroup/nodegroup.go, internal/controller/numaresourcesscheduler_controller.go, internal/controller/numaresourcesscheduler_controller_test.go, internal/machineconfigpools/machineconfigpools_test.go, internal/wait/nodepool.go, nrovalidate/validator/validator.go, pkg/apply/apply_test.go, rte/main.go, rte/pkg/config/config_test.go, test/deviceplugin/pkg/numacell/plugin/numacell.go, test/e2e/must-gather/must_gather_test.go, test/e2e/sched/sched_test.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/internal/deploy/deploy.go, test/internal/nodepools/nodepools.go, test/internal/nodepools/nodepools_test.go, test/internal/noderesourcetopologies/nrts.go, test/internal/nrosched/nrosched.go, tools/verify-commit/verify-commit.go, tools/watchnrtattr/watchnrtattr.go
Add more linters: copyloopvar, errcheck, gocritic. Please see commits for detailed changes.
=> add linters: copyloopvar, errcheck, gocritic

test/e2e/serial/tests/configuration.go
This PR addresses flaky tests by ensuring NRO status is checked only after controller reconciliation, using Eventually blocks for reliable updates.
=> e2e: serial: Fix flaky NRO status updates

bundle/manifests/numaresources-operator.clusterserviceversion.yaml, config/rbac/role.yaml, controllers/numaresourcesoperator_controller.go, pkg/numaresourcesscheduler/controlplane/discover.go
HA autosizing need to know how many worker objects we have so we fix the RBAC permissions
=> [release-4.18][manual] sched: ha: rbac: fix autodetection

api/v1/helper/nodegroup/nodegroup.go, doc/examples/perfprofile-bm.yaml, internal/controller/kubeletconfig_controller_test.go, internal/controller/numaresourcesoperator_controller.go, pkg/objectstate/rte/machineconfigpool.go, pkg/objectstate/rte/nodegroup.go, pkg/objectstate/rte/rte.go, pkg/objectupdate/rte/rte.go, test/e2e/install/install_test.go, test/e2e/serial/config/config.go, test/e2e/serial/tests/configuration.go, test/e2e/serial/tests/version.go
grab bag of minor/cosmetic changes. Please check each commit for details.
=> chore: fixes 20250411

test/e2e/serial/tests/configuration.go
This PR introduces test cases specifically targeting NUMA functionality in a Hosted Control Plane (HyperShift) environment.
It implements the tests outlined in the associated test plan and ensures coverage for the intended scenarios.
=> e2e: serial: Add test cases for hypershift environment.

.golangci.yml, rte/pkg/config/config_test.go, test/e2e/serial/e2e_serial_test.go
fix linter warning and implement code suggestion
=> Golint fixes 20250515

internal/wait/pod.go, test/e2e/serial/tests/tolerations.go
As reboot triggered by NROP CR deletion and creation is not necessary for versions >= 4.18 since it causes tests 75854 and 75855 to fail unintentionally.
The changes here removes the wait for mcp updates and in addition ensures the before each function checks that the RTE pods are deleted properly.In addition to preserve the old behavior for versions <= 4.17 we're checking to see if the custom policysupport is enabled which then a waitForMcpUpdate is necessary.
=> e2e: serial: Update MCPs on NRO CR deletion when customPolicy is set

test/e2e/serial/tests/scheduler_cache_stall.go
Add more scheduler stall tests to check that we correctly handle the interference against jobs which create guaranteed and burstable pods.
A "scheduler stall" is when the secondary scheduler can't recover nodes from "invalid topology data" state. We say a given node is "stalled". If all the nodes, or "too many" nodes are stalled, we call a scheduler stall.
=> e2e: serial: more scheduler stall tests against burstable and guaranteed jobs

internal/baseload/baseload.go, internal/resourcelist/resourcelist.go, internal/resourcelist/resourcelist_test.go, internal/wait/deployment.go, test/e2e/serial/tests/non_regression.go, test/e2e/serial/tests/scheduler_cache.go, test/e2e/serial/tests/scheduler_removal.go, test/e2e/serial/tests/workload_overhead.go, test/e2e/serial/tests/workload_placement.go, test/e2e/serial/tests/workload_unschedulable.go, test/internal/fixture/fixture.go, test/internal/noderesourcetopologies/nrts.go, test/internal/nrosched/nrosched.go
rewrite tests which are flaky or known broken, to improve at least reliability and debuggability.
Add a scaleup non-regression test.
please check each commit for details.
=> e2e: serial: rewrite tests for reliability

tools/verify-commit/verify-commit.go
Manual cherry picks. Please review the commits.
=> [release-4.18] tools: pass on bots commits 

pkg/numaresourcesscheduler/objectstate/sched/sched.go, pkg/objectstate/api/api.go, pkg/objectstate/merge/merge.go
Extract the remaining easy/uncontroversial changes from #1194 . The next optimization will require a different approach. See: https://github.com/openshift-kni/numaresources-operator/pull/1194#issuecomment-2948265049
=> controller: minimize update calls (reduced)

.konflux/catalog/bundle.builds.in.yaml, .konflux/catalog/catalog-template.in.yaml
revert setting up 4.19.1 until first FBC is published
=> Revert "Merge pull request #1493 from yanirq/konflux_4_19_1"

.konflux/must-gather/rpms.lock.yaml, .tekton/numaresources-must-gather-4-19-pull-request.yaml, .tekton/numaresources-must-gather-4-19-push.yaml
This PR fixed the RPM prefetch process, which we found to be broken.
=> [release-4.19]: Konflux: fix must gather rpm fetching

.konflux/must-gather/rpms.lock.yaml, .tekton/numaresources-must-gather-4-14-pull-request.yaml, .tekton/numaresources-must-gather-4-14-push.yaml
This PR fixed the RPM prefetch process, which we found to be broken.
=> [release-4.14]: Konflux: fix must gather rpm fetching

.konflux/must-gather/rpms.lock.yaml, .tekton/numaresources-must-gather-4-15-pull-request.yaml, .tekton/numaresources-must-gather-4-15-push.yaml
This PR fixed the RPM prefetch process, which we found to be broken.
=> [release-4.15]: Konflux: fix must gather rpm fetching

.konflux/must-gather/rpms.lock.yaml, .tekton/numaresources-must-gather-4-17-pull-request.yaml, .tekton/numaresources-must-gather-4-17-push.yaml
This PR fixed the RPM prefetch process, which we found to be broken.
=> [release-4.17]: Konflux: fix must gather rpm fetching

.golangci.yml, Makefile, hack/sort-imports.py, internal/schedcache/synced.go
update infra and fix linter issues
=> chore: project: move to golangci-lint v2

controllers/numaresourcesoperator_controller_test.go, go.mod, go.sum, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/rte/daemonset.yaml, vendor/modules.txt
bump deployer and verify RTE has a critical priority class. see commits for details.
=> [release-4.17] controller: test: verify RTE has a critical priority class 

controllers/numaresourcesoperator_controller_test.go, go.mod, go.sum, vendor/github.com/k8stopologyawareschedwg/deployer/pkg/manifests/yaml/rte/daemonset.yaml, vendor/modules.txt
bump deployer and verify RTE has a critical priority class. see commits for details.
=> [release-4.16] controller: test: verify RTE has a critical priority class 

.konflux/catalog/bundle.builds.in.yaml, .konflux/catalog/catalog-template.in.yaml, .konflux/catalog/fbc-images-resolvable-integration-test-idms.yaml, .tekton/images-mirror-set.yaml, .tekton/numaresources-operator-fbc-4-18-pull-request.yaml, .tekton/numaresources-operator-fbc-4-18-push.yaml
- Catalog and image pinning alignments to SHA image
- Tekton: watch bundle image updates to trigger FBC
- Update IDMS api version
=> [release-4.18] Konflux: Catalog and fbc updates

.konflux/catalog/bundle.builds.in.yaml, .konflux/catalog/catalog-template.in.yaml, .konflux/catalog/fbc-images-resolvable-integration-test-idms.yaml, .tekton/images-mirror-set.yaml, .tekton/numaresources-operator-fbc-4-16-pull-request.yaml, .tekton/numaresources-operator-fbc-4-16-push.yaml
- Catalog and image pinning alignments to SHA image
- Tekton: watch bundle image updates to trigger FBC
- Update IDMS api version
=> [release-4.16] Konflux: Catalog and fbc updates 

.konflux/catalog/bundle.builds.in.yaml, .konflux/catalog/catalog-template.in.yaml, .konflux/catalog/fbc-images-resolvable-integration-test-idms.yaml, .tekton/images-mirror-set.yaml, .tekton/numaresources-operator-fbc-4-17-pull-request.yaml, .tekton/numaresources-operator-fbc-4-17-push.yaml
- Catalog and image pinning alignments to SHA image
- Tekton: watch bundle image updates to trigger FBC
- Update IDMS api version
=> [release-4.17] Konflux: Catalog and fbc updates

ARCHITECTURE.md
clarify the cluster entities we add and start sketching out the permission model.
=> docs: clarify architecture and add k8s RBAC notes

.konflux/catalog/fbc-images-resolvable-integration-test-idms.yaml, .tekton/images-mirror-set.yaml
=> [release-4.18][manual] Update IDMS api version

.cursor/rules/_project.mdc, PROMPTING.md, README.ai.md
Initial proposal for AI assistance guidelines.
=> AI: docs: formalize initial AI contributions guidelines

internal/controller/numaresourcesscheduler_controller_test.go
Add an integration test to verify CacheResyncDebug update is absorbed by scheduler deployment.
see https://github.com/openshift-kni/numaresources-operator/pull/1526#discussion_r2172212300
=> controller: sched: test CacheResyncDebug update

README.ai.md
=> AI: docs: clarify docs

.konflux/OWNERS, .tekton/OWNERS, OWNERS, OWNERS_ALIASES
Update OWNERS configuration
- Add additional konflux-approvers
- Create separate konflux-reviewers list
- Use the top level OWNERS file to define the configuration for the files and folders
- Apply yaml formatting to OWNERS & OWNERS_ALIASES files
Signed-off-by: Steven Skeard <sskeard@redhat.com>
=> Update OWNERS configuration

api/numaresourcesoperator/v1/numaresourcesscheduler_types.go, controllers/numaresourcesoperator_controller.go, controllers/numaresourcesscheduler_controller.go, controllers/numaresourcesscheduler_controller_test.go, internal/platforminfo/platforminfo.go, internal/platforminfo/platforminfo_test.go, internal/platforminfo/supportversion.go, internal/platforminfo/supportversion_test.go, main.go, pkg/status/status.go, pkg/status/status_test.go, test/e2e/sched/install/install_test.go
=> OCPBUGS-61676: [release-4.17]: controller: sched: conditionally enable Shared informer by default 

go.mod, go.sum, internal/controller/numaresourcesscheduler_controller_test.go, pkg/objectupdate/envvar/envvar.go, pkg/objectupdate/envvar/envvar_test.go, pkg/objectupdate/rte/rte.go, pkg/objectupdate/rte/rte_test.go, pkg/objectupdate/sched/sched.go, rte/main.go, vendor/github.com/k8stopologyawareschedwg/podfingerprint/.gitignore, vendor/github.com/k8stopologyawareschedwg/podfingerprint/tracing.go, vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/pkg/resourcemonitor/resourcemonitor.go, vendor/github.com/openshift-kni/debug-tools/LICENSE, vendor/github.com/openshift-kni/debug-tools/pkg/pfpstatus/README.md, vendor/github.com/openshift-kni/debug-tools/pkg/pfpstatus/pfpstatus.go, vendor/github.com/openshift-kni/debug-tools/pkg/pfpstatus/pfpstatus_file.go, vendor/github.com/openshift-kni/debug-tools/pkg/pfpstatus/record/codec.go, vendor/github.com/openshift-kni/debug-tools/pkg/pfpstatus/record/recorder.go, vendor/modules.txt
Use uniformly debug-tools/pfpstatus like we do in the scheduler This requires RTE >= 0.21.6
=> rte: consume v0.21.6 and plug debug-tools/pfpstatus
